import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const serviceRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const migrationsRoot = join(serviceRoot, "migrations", "domains");
const outputPath = join(serviceRoot, "src", "repositories", "models", "physical.ts");
const runtimeTables = new Set([
  "orders",
  "order_number_counters",
  "order_lines",
  "order_contacts",
  "order_addresses",
  "order_recipients",
  "order_delivery_groups",
  "order_delivery_group_lines",
  "order_delivery_methods",
  "order_payment_methods",
  "order_discount_applications",
  "idempotency_records",
  "order_fulfillment_orders",
  "order_fulfillment_event_inbox",
]);

const sqlFiles = (await walk(migrationsRoot)).filter((path) => path.endsWith(".sql")).sort();
const tables = new Map<string, Array<{ name: string; type: string }>>();

for (const path of sqlFiles) {
  const source = await readFile(path, "utf8");
  const pattern = /CREATE TABLE "orders"\."([^"]+)" \(([\s\S]*?)\n\);/g;
  for (const match of source.matchAll(pattern)) {
    const [, tableName, body] = match;
    const columns: Array<{ name: string; type: string }> = [];
    for (const line of body.split("\n")) {
      const column = line.match(/^\s+"([^"]+)"\s+(.+?)(?:,)?$/);
      if (!column || column[1] === "") continue;
      const type = sqlType(column[2]);
      if (type) columns.push({ name: column[1], type });
    }
    tables.set(tableName, columns);
  }
}

const generated = [
  "// Generated by scripts/generate-physical-models.ts. Do not edit by hand.",
  'import { customType } from "drizzle-orm/pg-core";',
  'import { ordersSchema } from "./schema.js";',
  "",
  "const physical = (type: string, name: string) =>",
  "  customType<{ data: unknown }>({ dataType: () => type })(name);",
  "",
  "export const canonicalPhysicalTables = {",
];

for (const [tableName, columns] of [...tables].sort(([left], [right]) =>
  left.localeCompare(right),
)) {
  if (runtimeTables.has(tableName)) continue;
  generated.push(`  ${camel(tableName)}: ordersSchema.table(${JSON.stringify(tableName)}, {`);
  for (const column of columns) {
    generated.push(
      `    ${camel(column.name)}: physical(${JSON.stringify(column.type)}, ${JSON.stringify(column.name)}),`,
    );
  }
  generated.push("  }),");
}
generated.push("} as const;", "");

await writeFile(outputPath, generated.join("\n"));
process.stdout.write(
  `Generated ${relative(serviceRoot, outputPath)} from ${sqlFiles.length} migration files (${tables.size} tables).\n`,
);

async function walk(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = join(root, entry.name);
      return entry.isDirectory() ? walk(path) : Promise.resolve([path]);
    }),
  );
  return nested.flat();
}

function camel(value: string): string {
  const result = value.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());
  return /^(?:class|delete|export|import|new|return|type)$/.test(result)
    ? `${result}Column`
    : result;
}

function sqlType(definition: string): string | null {
  const normalized = definition.replace(/,$/, "").trim();
  const match = normalized.match(
    /^(uuid|bigint|integer|boolean|text|bytea|jsonb|numeric(?:\([^)]*\))?|varchar(?:\([^)]*\))?|timestamp with time zone|timestamptz|text\[\]|"orders"\."[^"]+")/,
  );
  return match?.[1] ?? null;
}
