extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.7"
    import: ["@key", "@external", "@shareable", "@inaccessible"]
  )

type Query {
  """
  Loyalty Admin query namespace.
  """
  loyaltyQuery: LoyaltyQuery!
}

type Mutation {
  """
  Loyalty Admin mutation namespace.
  """
  loyaltyMutation: LoyaltyMutation!
}

type LoyaltyQuery {
  node(id: ID!): Node
  nodes(ids: [ID!]!): [Node]!

  program(id: ID!): LoyaltyProgram
  programVersion(id: ID!): LoyaltyProgramVersion
  earningRule(id: ID!): LoyaltyEarningRule
  rewardDefinition(id: ID!): LoyaltyRewardDefinition
  tier(id: ID!): LoyaltyTier
  tierPolicy(id: ID!): LoyaltyTierPolicy
  programs(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyProgramWhereInput
  ): LoyaltyProgramConnection!

  account(id: ID!): LoyaltyAccount
  customerAccount(customerId: ID!, programId: ID): LoyaltyAccount
  accounts(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyAccountWhereInput
  ): LoyaltyAccountConnection!

  transaction(id: ID!): LoyaltyTransaction
  transactions(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyTransactionWhereInput
  ): LoyaltyTransactionConnection!

  reservation(id: ID!): LoyaltyReservation
  reservations(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyReservationWhereInput
  ): LoyaltyReservationConnection!

  tierMembership(id: ID!): LoyaltyTierMembership
  tierMemberships(accountId: ID!, first: Int = 100): [LoyaltyTierMembership!]!

  eventFact(id: ID!): LoyaltyEventFact
  eventFacts(where: LoyaltyEventFactWhereInput, first: Int = 100): [LoyaltyEventFact!]!
  eventEvaluation(id: ID!): LoyaltyEventEvaluation
  eventEvaluations(
    where: LoyaltyEventEvaluationWhereInput!
    first: Int = 100
  ): [LoyaltyEventEvaluation!]!
  earningRuleUsages(
    where: LoyaltyEarningRuleUsageWhereInput!
    first: Int = 100
  ): [LoyaltyEarningRuleUsage!]!

  rewardEntitlement(id: ID!): LoyaltyRewardEntitlement
  rewardEntitlements(
    where: LoyaltyRewardEntitlementWhereInput!
    first: Int = 100
  ): [LoyaltyRewardEntitlement!]!

  monetaryWallet(id: ID!): LoyaltyMonetaryWallet
  monetaryWallets(
    where: LoyaltyMonetaryWalletWhereInput!
    first: Int = 100
  ): [LoyaltyMonetaryWallet!]!
  monetaryTransaction(id: ID!): LoyaltyMonetaryTransaction
  monetaryTransactions(walletId: ID!, first: Int = 100): [LoyaltyMonetaryTransaction!]!
}

type LoyaltyMutation {
  programCreate(input: LoyaltyProgramCreateInput!): LoyaltyProgramCreatePayload!
  programUpdate(
    programId: ID!
    operations: LoyaltyProgramUpdateInput!
  ): LoyaltyProgramUpdatePayload!
  accountUpdate(
    accountId: ID!
    operations: LoyaltyAccountUpdateInput!
  ): LoyaltyAccountUpdatePayload!
  reservationUpdate(
    reservationId: ID!
    operations: LoyaltyReservationUpdateInput!
  ): LoyaltyReservationUpdatePayload!
  monetaryWalletUpdate(
    monetaryWalletId: ID!
    operations: LoyaltyMonetaryWalletUpdateInput!
  ): LoyaltyMonetaryWalletUpdatePayload!

  maintenanceRun(input: LoyaltyMaintenanceRunInput!): LoyaltyMaintenanceRunPayload!
}
