extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.7"
    import: ["@key", "@external", "@shareable", "@inaccessible"]
  )

extend type Query {
  """
  Loyalty Admin query namespace.
  """
  loyaltyQuery: LoyaltyQuery!
}

extend type Mutation {
  """
  Loyalty Admin mutation namespace.
  """
  loyaltyMutation: LoyaltyMutation!
}

type LoyaltyQuery {
  node(id: ID!): Node
  nodes(ids: [ID!]!): [Node]!

  program(id: ID!): LoyaltyProgram
  programVersion(id: ID!): LoyaltyProgramVersion
  earningRule(id: ID!): LoyaltyEarningRule
  rewardDefinition(id: ID!): LoyaltyRewardDefinition
  tier(id: ID!): LoyaltyTier
  tierPolicy(id: ID!): LoyaltyTierPolicy
  programs(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyProgramWhereInput
    orderBy: [LoyaltyProgramOrderByInput!]
  ): LoyaltyProgramConnection!

  account(id: ID!): LoyaltyAccount
  customerAccount(customerId: ID!, programId: ID): LoyaltyAccount
  accounts(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyAccountWhereInput
    orderBy: [LoyaltyAccountOrderByInput!]
  ): LoyaltyAccountConnection!

  transaction(id: ID!): LoyaltyTransaction
  transactions(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyTransactionWhereInput
    orderBy: [LoyaltyTransactionOrderByInput!]
  ): LoyaltyTransactionConnection!

  reservation(id: ID!): LoyaltyReservation
  reservations(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyReservationWhereInput
    orderBy: [LoyaltyReservationOrderByInput!]
  ): LoyaltyReservationConnection!

  tierMembership(id: ID!): LoyaltyTierMembership
  tierMemberships(
    accountId: ID!
    first: Int
    after: String
    last: Int
    before: String
    orderBy: [LoyaltyTierMembershipOrderByInput!]
  ): LoyaltyTierMembershipConnection!

  eventFact(id: ID!): LoyaltyEventFact
  eventFacts(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyEventFactWhereInput
    orderBy: [LoyaltyEventFactOrderByInput!]
  ): LoyaltyEventFactConnection!
  eventEvaluation(id: ID!): LoyaltyEventEvaluation
  eventEvaluations(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyEventEvaluationWhereInput!
    orderBy: [LoyaltyEventEvaluationOrderByInput!]
  ): LoyaltyEventEvaluationConnection!
  earningRuleUsages(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyEarningRuleUsageWhereInput!
    orderBy: [LoyaltyEarningRuleUsageOrderByInput!]
  ): LoyaltyEarningRuleUsageConnection!

  rewardEntitlement(id: ID!): LoyaltyRewardEntitlement
  rewardEntitlements(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyRewardEntitlementWhereInput!
    orderBy: [LoyaltyRewardEntitlementOrderByInput!]
  ): LoyaltyRewardEntitlementConnection!

  monetaryWallet(id: ID!): LoyaltyMonetaryWallet
  monetaryWallets(
    first: Int
    after: String
    last: Int
    before: String
    where: LoyaltyMonetaryWalletWhereInput!
    orderBy: [LoyaltyMonetaryWalletOrderByInput!]
  ): LoyaltyMonetaryWalletConnection!
  monetaryTransaction(id: ID!): LoyaltyMonetaryTransaction
  monetaryTransactions(
    walletId: ID!
    first: Int
    after: String
    last: Int
    before: String
    orderBy: [LoyaltyMonetaryTransactionOrderByInput!]
  ): LoyaltyMonetaryTransactionConnection!
}

type LoyaltyMutation {
  programCreate(input: LoyaltyProgramCreateInput!): LoyaltyProgramCreatePayload!
  programUpdate(
    programId: ID!
    operations: LoyaltyProgramUpdateInput!
  ): LoyaltyProgramUpdatePayload!
  accountUpdate(
    accountId: ID!
    operations: LoyaltyAccountUpdateInput!
  ): LoyaltyAccountUpdatePayload!
  reservationUpdate(
    reservationId: ID!
    operations: LoyaltyReservationUpdateInput!
  ): LoyaltyReservationUpdatePayload!
  monetaryWalletUpdate(
    monetaryWalletId: ID!
    operations: LoyaltyMonetaryWalletUpdateInput!
  ): LoyaltyMonetaryWalletUpdatePayload!

  maintenanceRun(input: LoyaltyMaintenanceRunInput!): LoyaltyMaintenanceRunPayload!
}
