query CategoryCategoryProducts(
  $id: ID!
  $first: Int
  $after: String
  $where: ListingWhereInput
  $orderBy: [ListingOrderByInput!]
) {
  catalogQuery {
    category(id: $id) {
      id
      handle
      name
      defaultSort
      defaultSortDirection
      listing(first: $first, after: $after, where: $where, orderBy: $orderBy) {
        edges {
          node {
            id
            kind
            title
            handle
            isPublished
            ... on Product {
              variants(first: 1) {
                edges {
                  node {
                    id
                    price {
                      amountMinor
                      currency
                    }
                    inventoryItem {
                      id
                      totalAvailable
                    }
                  }
                }
              }
            }
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }
  }
}
