mutation CategoryRebalance($input: CategoryRebalanceInput!) {
  catalogMutation {
    categoryRebalance(input: $input) {
      category {
        id
        handle
        productsCount
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
