mutation CategoryMoveProduct(
  $productId: ID!
  $categoryId: ID!
  $afterProductId: ID
  $beforeProductId: ID
  $expectedRevision: Int
) {
  catalogMutation {
    productUpdate(
      productId: $productId
      expectedRevision: $expectedRevision
      operations: {
        categories: [
          {
            categoryId: $categoryId
            action: MOVE
            afterProductId: $afterProductId
            beforeProductId: $beforeProductId
          }
        ]
      }
    ) {
      product {
        id
        handle
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
