mutation CategoryUpdate(
  $categoryId: ID!
  $expectedRevision: Int
  $operations: CategoryUpdateInput
) {
  catalogMutation {
    categoryUpdate(
      categoryId: $categoryId
      expectedRevision: $expectedRevision
      operations: $operations
    ) {
      category {
        id
        handle
        revision
        name
        description {
          html
          text
          json
        }
        excerpt {
          html
          text
          json
        }
        defaultSort
        defaultSortDirection
        isPublished
        publishedAt
        updatedAt
        seo {
          seoTitle
          seoDescription
          ogTitle
          ogDescription
          ogImage {
            id
          }
        }
        media {
          file {
            id
          }
          sortIndex
        }
      }
      operationResults {
        type
        applied
        errors {
          message
          code
          field
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
