mutation CategoryAddProduct($productId: ID!, $categoryId: ID!, $expectedRevision: Int) {
  catalogMutation {
    productUpdate(
      productId: $productId
      expectedRevision: $expectedRevision
      operations: { categories: [{ categoryId: $categoryId, action: ADD }] }
    ) {
      product {
        id
        handle
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
