#!/usr/bin/env python3
"""Generate the pinned Unicode normalization tables used by DSL v1."""

from __future__ import annotations

import hashlib
import json
import pathlib
import unicodedata


UNICODE_VERSION = "16.0.0"
OUTPUT = pathlib.Path(__file__).parents[1] / "src" / "unicode-normalization-data.ts"


def encoded_map(values: dict[int, tuple[int, ...]]) -> str:
    return ";".join(
        f"{base36(code_point)}:{'.'.join(base36(item) for item in mapping)}"
        for code_point, mapping in sorted(values.items())
    )


def encoded_scalar_map(values: dict[int, int]) -> str:
    return ";".join(
        f"{base36(code_point)}:{base36(value)}"
        for code_point, value in sorted(values.items())
    )


def encoded_compositions(values: dict[tuple[int, int], int]) -> str:
    return ";".join(
        f"{base36(left)}.{base36(right)}:{base36(composite)}"
        for (left, right), composite in sorted(values.items())
    )


def base36(value: int) -> str:
    alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"
    if value == 0:
        return "0"
    digits: list[str] = []
    while value:
        value, remainder = divmod(value, 36)
        digits.append(alphabet[remainder])
    return "".join(reversed(digits))


def typescript_string(name: str, value: str) -> str:
    entries = value.split(";") if value else []
    chunks: list[str] = []
    current = ""
    for index, entry in enumerate(entries):
        token = entry + (";" if index + 1 < len(entries) else "")
        if current and len(current) + len(token) > 108:
            chunks.append(current)
            current = token
        else:
            current += token
    if current:
        chunks.append(current)
    lines = "\n".join(f"  {json.dumps(chunk)}," for chunk in chunks)
    return f"export const {name} = [\n{lines}\n].join(\"\");"


def main() -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"Expected Python Unicode {UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    canonical: dict[int, tuple[int, ...]] = {}
    compatibility: dict[int, tuple[int, ...]] = {}
    combining_classes: dict[int, int] = {}
    compositions: dict[tuple[int, int], int] = {}

    for code_point in range(0x110000):
        character = chr(code_point)
        combining_class = unicodedata.combining(character)
        if combining_class:
            combining_classes[code_point] = combining_class
        decomposition = unicodedata.decomposition(character)
        if not decomposition:
            continue
        parts = decomposition.split()
        tagged = parts[0].startswith("<")
        mapping = tuple(int(part, 16) for part in (parts[1:] if tagged else parts))
        compatibility[code_point] = mapping
        if tagged:
            continue
        canonical[code_point] = mapping
        if len(mapping) == 2 and unicodedata.normalize("NFC", "".join(map(chr, mapping))) == character:
            compositions[mapping] = code_point

    encoded = {
        "canonical": encoded_map(canonical),
        "compatibility": encoded_map(compatibility),
        "combining": encoded_scalar_map(combining_classes),
        "compositions": encoded_compositions(compositions),
    }
    checksum = hashlib.sha256(
        json.dumps(encoded, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()
    ).hexdigest()
    output = "\n\n".join(
        [
            "// Generated by scripts/generate-unicode-normalization.py; do not edit by hand.",
            f'export const UNICODE_NORMALIZATION_VERSION = "{UNICODE_VERSION}";',
            f'export const UNICODE_NORMALIZATION_SHA256 = "{checksum}";',
            typescript_string("UNICODE_CANONICAL_DECOMPOSITION_DATA", encoded["canonical"]),
            typescript_string("UNICODE_COMPATIBILITY_DECOMPOSITION_DATA", encoded["compatibility"]),
            typescript_string("UNICODE_COMBINING_CLASS_DATA", encoded["combining"]),
            typescript_string("UNICODE_COMPOSITION_DATA", encoded["compositions"]),
            "",
        ]
    )
    OUTPUT.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
