#!/usr/bin/env python3
"""Generate the pinned Unicode full default case-fold table used at runtime."""

from hashlib import sha256
from pathlib import Path
import json
import unicodedata


UNICODE_VERSION = "16.0.0"
TARGET = Path(__file__).resolve().parents[1] / "src" / "case-fold.ts"


def main() -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise RuntimeError(
            f"Expected Unicode {UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )
    rows: list[tuple[int, str]] = []
    for code_point in range(0x110000):
        if 0xD800 <= code_point <= 0xDFFF:
            continue
        value = chr(code_point)
        folded = value.casefold()
        if folded != value:
            rows.append((code_point, folded))
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    checksum = sha256(payload.encode("utf-8")).hexdigest()
    entries = "\n".join(
        f"  [0x{code_point:X}, {json.dumps(folded, ensure_ascii=False)}],"
        for code_point, folded in rows
    )
    TARGET.write_text(
        f'''// Generated by scripts/generate-case-fold.py. Do not edit manually.
export const UNICODE_CASE_FOLD_VERSION = "{UNICODE_VERSION}" as const;
export const UNICODE_CASE_FOLD_SHA256 = "{checksum}" as const;

const FULL_CASE_FOLD = new Map<number, string>([
{entries}
]);

export function fullUnicodeCaseFold(value: string): string {{
  return [...value].map((character) =>
    FULL_CASE_FOLD.get(character.codePointAt(0)!) ?? character
  ).join("");
}}
''',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
