// Mock data for admin panel based on GraphQL schema

const now = new Date().toISOString();

// User type
export const mockUsers = [
  {
    __typename: 'User',
    id: '1',
    tenantId: 'tenant-1',
    email: 'admin@shopana.io',
    firstName: 'Admin',
    lastName: 'User',
    isReady: true,
    isVerified: true,
    phoneNumber: '+1234567890',
    language: 'en',
    timezone: 'UTC',
    createdAt: now,
    updatedAt: now,
  },
  {
    __typename: 'User',
    id: '2',
    tenantId: 'tenant-1',
    email: 'test@shopana.io',
    firstName: 'Test',
    lastName: 'User',
    isReady: true,
    isVerified: true,
    phoneNumber: null,
    language: 'en',
    timezone: 'UTC',
    createdAt: now,
    updatedAt: now,
  },
];

// Project type
export const mockProjects = [
  {
    id: 'proj-1',
    name: 'Demo Store',
    slug: 'demo-store',
    status: 'ACTIVE',
  },
  {
    id: 'proj-2',
    name: 'Test Shop',
    slug: 'test-shop',
    status: 'ACTIVE',
  },
];

// ProjectInfo type
export const mockProjectInfo = {
  name: 'Demo Store',
  timezone: 'America/New_York',
  country: 'US',
  phoneNumber: '+1234567890',
  email: 'demo@shopana.io',
  currency: 'USD',
  locale: 'en-US',
};

// Locale type
export const mockLocales = [
  { title: 'English', code: 'en', isActive: true },
  { title: 'Russian', code: 'ru', isActive: true },
  { title: 'Spanish', code: 'es', isActive: false },
];

// Currency type
export const mockCurrencies = [
  {
    title: 'US Dollar',
    code: 'USD',
    isActive: true,
    decimalPlaces: 2,
    exchangeRate: 1.0,
    symbolLeft: '$',
    symbolRight: '',
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    title: 'Euro',
    code: 'EUR',
    isActive: true,
    decimalPlaces: 2,
    exchangeRate: 0.85,
    symbolLeft: '',
    symbolRight: '€',
    decimalSeparator: ',',
    thousandsSeparator: ' ',
  },
  {
    title: 'Russian Ruble',
    code: 'RUB',
    isActive: true,
    decimalPlaces: 2,
    exchangeRate: 90.0,
    symbolLeft: '',
    symbolRight: '₽',
    decimalSeparator: ',',
    thousandsSeparator: ' ',
  },
];

// ApiKey type
export const mockApiKeys = [
  {
    id: 'key-1',
    name: 'Production API Key',
    createdAt: now,
    createdBy: mockUsers[0],
    dueDate: null,
    lastUsedAt: now,
    isBanned: false,
  },
];

// File type
const mockFile = (id: string, name: string) => ({
  __typename: 'File',
  id,
  driver: 'S3',
  name,
  url: `https://picsum.photos/seed/${id}/400/400`,
  size: 1024,
  ext: 'jpg',
  key: `files/${id}.jpg`,
  createdAt: now,
  updatedAt: now,
});

// Category type
export const mockCategories = [
  {
    __typename: 'Category',
    id: 'cat-1',
    slug: 'electronics',
    title: 'Electronics',
    status: 'ACTIVE',
    description: 'Electronic devices and gadgets',
    excerpt: 'Electronics',
    cover: mockFile('cat-1-cover', 'electronics.jpg'),
    gallery: [],
    children: [],
    parent: null,
    createdAt: now,
    updatedAt: now,
    includeChildrenProducts: true,
    listingFilters: [],
    labels: [],
    tags: [],
    listingOrderBy: 'CREATED_AT_DESC',
    listingOrderByStatus: true,
    listingPlacement: 0,
    listingType: 'GRID',
    seoTitle: 'Electronics',
    seoDescription: 'Shop electronics',
  },
  {
    __typename: 'Category',
    id: 'cat-2',
    slug: 'clothing',
    title: 'Clothing',
    status: 'ACTIVE',
    description: 'Fashion and apparel',
    excerpt: 'Clothing',
    cover: mockFile('cat-2-cover', 'clothing.jpg'),
    gallery: [],
    children: [],
    parent: null,
    createdAt: now,
    updatedAt: now,
    includeChildrenProducts: true,
    listingFilters: [],
    labels: [],
    tags: [],
    listingOrderBy: 'CREATED_AT_DESC',
    listingOrderByStatus: true,
    listingPlacement: 1,
    listingType: 'GRID',
    seoTitle: 'Clothing',
    seoDescription: 'Shop clothing',
  },
  {
    __typename: 'Category',
    id: 'cat-3',
    slug: 'phones',
    title: 'Phones',
    status: 'ACTIVE',
    description: 'Smartphones and accessories',
    excerpt: 'Phones',
    cover: mockFile('cat-3-cover', 'phones.jpg'),
    gallery: [],
    children: [],
    parent: { __typename: 'Category', id: 'cat-1', slug: 'electronics', title: 'Electronics' },
    createdAt: now,
    updatedAt: now,
    includeChildrenProducts: true,
    listingFilters: [],
    labels: [],
    tags: [],
    listingOrderBy: 'CREATED_AT_DESC',
    listingOrderByStatus: true,
    listingPlacement: 0,
    listingType: 'GRID',
    seoTitle: 'Phones',
    seoDescription: 'Shop phones',
  },
];

// Feature groups for options
const mockFeatureGroups = {
  color: {
    __typename: 'FeatureGroup',
    id: 'fg-color',
    slug: 'color',
    title: 'Color',
    featureStyleType: 'SWATCH',
  },
  size: {
    __typename: 'FeatureGroup',
    id: 'fg-size',
    slug: 'size',
    title: 'Size',
    featureStyleType: 'BUTTON',
  },
  storage: {
    __typename: 'FeatureGroup',
    id: 'fg-storage',
    slug: 'storage',
    title: 'Storage',
    featureStyleType: 'BUTTON',
  },
};

// Features (option values)
const mockFeatures = {
  black: {
    featureId: 'feat-black',
    title: 'Black',
    slug: 'black',
    group: mockFeatureGroups.color,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 0,
    attributeSortIndex: 0,
    swatch: { color: '#000000', image: null },
  },
  white: {
    featureId: 'feat-white',
    title: 'White',
    slug: 'white',
    group: mockFeatureGroups.color,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 1,
    attributeSortIndex: 1,
    swatch: { color: '#FFFFFF', image: null },
  },
  blue: {
    featureId: 'feat-blue',
    title: 'Blue',
    slug: 'blue',
    group: mockFeatureGroups.color,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 2,
    attributeSortIndex: 2,
    swatch: { color: '#0066CC', image: null },
  },
  sizeS: {
    featureId: 'feat-size-s',
    title: 'S',
    slug: 's',
    group: mockFeatureGroups.size,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 0,
    attributeSortIndex: 0,
    swatch: null,
  },
  sizeM: {
    featureId: 'feat-size-m',
    title: 'M',
    slug: 'm',
    group: mockFeatureGroups.size,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 1,
    attributeSortIndex: 1,
    swatch: null,
  },
  sizeL: {
    featureId: 'feat-size-l',
    title: 'L',
    slug: 'l',
    group: mockFeatureGroups.size,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 2,
    attributeSortIndex: 2,
    swatch: null,
  },
  sizeXL: {
    featureId: 'feat-size-xl',
    title: 'XL',
    slug: 'xl',
    group: mockFeatureGroups.size,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 3,
    attributeSortIndex: 3,
    swatch: null,
  },
  storage128: {
    featureId: 'feat-128gb',
    title: '128GB',
    slug: '128gb',
    group: mockFeatureGroups.storage,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 0,
    attributeSortIndex: 0,
    swatch: null,
  },
  storage256: {
    featureId: 'feat-256gb',
    title: '256GB',
    slug: '256gb',
    group: mockFeatureGroups.storage,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 1,
    attributeSortIndex: 1,
    swatch: null,
  },
  storage512: {
    featureId: 'feat-512gb',
    title: '512GB',
    slug: '512gb',
    group: mockFeatureGroups.storage,
    isOption: true,
    isAttribute: true,
    optionSortIndex: 2,
    attributeSortIndex: 2,
    swatch: null,
  },
};

// Variant type
interface CreateVariantOptions {
  id: string;
  productId: string;
  productTitle: string;
  title: string;
  price: number;
  sku: string;
  categories?: typeof mockCategories;
  featuresV2?: any[];
  variantSortIndex?: number;
  stockStatus?: string;
  weight?: number;
  weightUnit?: string;
  length?: number;
  width?: number;
  height?: number;
  dimensionUnit?: string;
  oldPrice?: number;
  costPrice?: number;
  inListing?: boolean;
}

const createVariant = ({
  id,
  productId,
  productTitle,
  title,
  price,
  sku,
  categories = [],
  featuresV2 = [],
  variantSortIndex = 0,
  stockStatus = 'IN_STOCK',
  weight = 500,
  weightUnit = 'GR',
  length = 150,
  width = 100,
  height = 50,
  dimensionUnit = 'MM',
  oldPrice,
  costPrice,
  inListing = true,
}: CreateVariantOptions) => ({
  __typename: 'Variant',
  id,
  containerId: productId,
  containerTitle: productTitle,
  title,
  slug: title.toLowerCase().replace(/\s+/g, '-'),
  price,
  oldPrice: oldPrice ?? Math.round(price * 1.2),
  costPrice: costPrice ?? Math.round(price * 0.6),
  sku,
  barcode: `BAR${id}`,
  stockStatus,
  cover: mockFile(`var-${id}`, `${title}.jpg`),
  gallery: [
    mockFile(`var-${id}-1`, `${title}-1.jpg`),
    mockFile(`var-${id}-2`, `${title}-2.jpg`),
    mockFile(`var-${id}-3`, `${title}-3.jpg`),
  ],
  categories,
  features: featuresV2,
  featuresV2,
  inListing,
  listingSortIndex: String(variantSortIndex),
  variantSortIndex,
  weight,
  weightUnit,
  width,
  length,
  height,
  dimensionUnit,
  createdAt: now,
  updatedAt: now,
});

// Product type
export const mockProducts = [
  {
    __typename: 'Product',
    id: 'prod-1',
    slug: 'iphone-15-pro',
    title: 'iPhone 15 Pro',
    description: 'The latest iPhone with A17 Pro chip',
    excerpt: 'Latest iPhone',
    status: 'PUBLISHED',
    requiresShipping: true,
    seoTitle: 'iPhone 15 Pro',
    seoDescription: 'Buy iPhone 15 Pro',
    groups: [],
    labels: [],
    tags: [{ id: 'tag-1', title: 'New', slug: 'new' }, { id: 'tag-2', title: 'Popular', slug: 'popular' }],
    primaryCategory: mockCategories[2],
    featuresV2: [],
    optionsV2: [],
    variants: [
      createVariant({
        id: 'var-1',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '128GB Black',
        price: 9990000,
        sku: 'IPH15-128-BLK',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage128, mockFeatures.black],
        variantSortIndex: 0,
        stockStatus: 'IN_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-2',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '256GB Black',
        price: 10990000,
        sku: 'IPH15-256-BLK',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage256, mockFeatures.black],
        variantSortIndex: 1,
        stockStatus: 'IN_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-3',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '512GB Black',
        price: 12990000,
        sku: 'IPH15-512-BLK',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage512, mockFeatures.black],
        variantSortIndex: 2,
        stockStatus: 'LOW_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-4',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '128GB White',
        price: 9990000,
        sku: 'IPH15-128-WHT',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage128, mockFeatures.white],
        variantSortIndex: 3,
        stockStatus: 'IN_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-5',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '256GB White',
        price: 10990000,
        sku: 'IPH15-256-WHT',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage256, mockFeatures.white],
        variantSortIndex: 4,
        stockStatus: 'OUT_OF_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-6',
        productId: 'prod-1',
        productTitle: 'iPhone 15 Pro',
        title: '128GB Blue',
        price: 10290000,
        sku: 'IPH15-128-BLU',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage128, mockFeatures.blue],
        variantSortIndex: 5,
        stockStatus: 'IN_STOCK',
        weight: 187,
        weightUnit: 'GR',
        length: 146,
        width: 70,
        height: 8,
        dimensionUnit: 'MM',
      }),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    __typename: 'Product',
    id: 'prod-2',
    slug: 'samsung-galaxy-s24',
    title: 'Samsung Galaxy S24',
    description: 'Samsung flagship smartphone',
    excerpt: 'Samsung flagship',
    status: 'PUBLISHED',
    requiresShipping: true,
    seoTitle: 'Samsung Galaxy S24',
    seoDescription: 'Buy Samsung Galaxy S24',
    groups: [],
    labels: [],
    tags: [{ id: 'tag-2', title: 'Popular', slug: 'popular' }],
    primaryCategory: mockCategories[2],
    featuresV2: [],
    optionsV2: [],
    variants: [
      createVariant({
        id: 'var-10',
        productId: 'prod-2',
        productTitle: 'Samsung Galaxy S24',
        title: '128GB Black',
        price: 7990000,
        sku: 'SAM-S24-128-BLK',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage128, mockFeatures.black],
        variantSortIndex: 0,
        stockStatus: 'IN_STOCK',
        weight: 168,
        weightUnit: 'GR',
        length: 147,
        width: 71,
        height: 7,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-11',
        productId: 'prod-2',
        productTitle: 'Samsung Galaxy S24',
        title: '256GB Black',
        price: 8990000,
        sku: 'SAM-S24-256-BLK',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage256, mockFeatures.black],
        variantSortIndex: 1,
        stockStatus: 'IN_STOCK',
        weight: 168,
        weightUnit: 'GR',
        length: 147,
        width: 71,
        height: 7,
        dimensionUnit: 'MM',
      }),
      createVariant({
        id: 'var-12',
        productId: 'prod-2',
        productTitle: 'Samsung Galaxy S24',
        title: '256GB Blue',
        price: 8990000,
        sku: 'SAM-S24-256-BLU',
        categories: [mockCategories[2]],
        featuresV2: [mockFeatures.storage256, mockFeatures.blue],
        variantSortIndex: 2,
        stockStatus: 'LOW_STOCK',
        weight: 168,
        weightUnit: 'GR',
        length: 147,
        width: 71,
        height: 7,
        dimensionUnit: 'MM',
      }),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    __typename: 'Product',
    id: 'prod-3',
    slug: 'cotton-t-shirt',
    title: 'Cotton T-Shirt',
    description: 'Comfortable cotton t-shirt',
    excerpt: 'Cotton t-shirt',
    status: 'PUBLISHED',
    requiresShipping: true,
    seoTitle: 'Cotton T-Shirt',
    seoDescription: 'Buy Cotton T-Shirt',
    groups: [],
    labels: [],
    tags: [],
    primaryCategory: mockCategories[1],
    featuresV2: [],
    optionsV2: [],
    variants: [
      createVariant({
        id: 'var-20',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'S White',
        price: 290000,
        sku: 'TSH-S-WHT',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeS, mockFeatures.white],
        variantSortIndex: 0,
        stockStatus: 'IN_STOCK',
        weight: 150,
        weightUnit: 'GR',
        length: 70,
        width: 50,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-21',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'M White',
        price: 290000,
        sku: 'TSH-M-WHT',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeM, mockFeatures.white],
        variantSortIndex: 1,
        stockStatus: 'IN_STOCK',
        weight: 160,
        weightUnit: 'GR',
        length: 72,
        width: 52,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-22',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'L White',
        price: 290000,
        sku: 'TSH-L-WHT',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeL, mockFeatures.white],
        variantSortIndex: 2,
        stockStatus: 'IN_STOCK',
        weight: 170,
        weightUnit: 'GR',
        length: 74,
        width: 54,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-23',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'XL White',
        price: 310000,
        sku: 'TSH-XL-WHT',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeXL, mockFeatures.white],
        variantSortIndex: 3,
        stockStatus: 'LOW_STOCK',
        weight: 180,
        weightUnit: 'GR',
        length: 76,
        width: 56,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-24',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'S Black',
        price: 290000,
        sku: 'TSH-S-BLK',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeS, mockFeatures.black],
        variantSortIndex: 4,
        stockStatus: 'IN_STOCK',
        weight: 150,
        weightUnit: 'GR',
        length: 70,
        width: 50,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-25',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'M Black',
        price: 290000,
        sku: 'TSH-M-BLK',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeM, mockFeatures.black],
        variantSortIndex: 5,
        stockStatus: 'IN_STOCK',
        weight: 160,
        weightUnit: 'GR',
        length: 72,
        width: 52,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-26',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'L Black',
        price: 290000,
        sku: 'TSH-L-BLK',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeL, mockFeatures.black],
        variantSortIndex: 6,
        stockStatus: 'OUT_OF_STOCK',
        weight: 170,
        weightUnit: 'GR',
        length: 74,
        width: 54,
        height: 2,
        dimensionUnit: 'CM',
      }),
      createVariant({
        id: 'var-27',
        productId: 'prod-3',
        productTitle: 'Cotton T-Shirt',
        title: 'XL Black',
        price: 310000,
        sku: 'TSH-XL-BLK',
        categories: [mockCategories[1]],
        featuresV2: [mockFeatures.sizeXL, mockFeatures.black],
        variantSortIndex: 7,
        stockStatus: 'IN_STOCK',
        weight: 180,
        weightUnit: 'GR',
        length: 76,
        width: 56,
        height: 2,
        dimensionUnit: 'CM',
      }),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    __typename: 'Product',
    id: 'prod-4',
    slug: 'leather-wallet',
    title: 'Leather Wallet',
    description: 'Premium genuine leather wallet with multiple card slots',
    excerpt: 'Leather wallet',
    status: 'PUBLISHED',
    requiresShipping: true,
    seoTitle: 'Leather Wallet',
    seoDescription: 'Buy Premium Leather Wallet',
    groups: [],
    labels: [],
    tags: [{ id: 'tag-3', title: 'Premium', slug: 'premium' }],
    primaryCategory: mockCategories[1],
    featuresV2: [],
    optionsV2: [],
    variants: [
      createVariant({
        id: 'var-30',
        productId: 'prod-4',
        productTitle: 'Leather Wallet',
        title: 'Default',
        price: 450000,
        sku: 'WALLET-BLK',
        categories: [mockCategories[1]],
        featuresV2: [],
        variantSortIndex: 0,
        stockStatus: 'IN_STOCK',
        weight: 80,
        weightUnit: 'GR',
        length: 110,
        width: 90,
        height: 15,
        dimensionUnit: 'MM',
      }),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    __typename: 'Product',
    id: 'prod-5',
    slug: 'wireless-charger',
    title: 'Wireless Charger',
    description: 'Fast wireless charging pad compatible with all Qi devices',
    excerpt: 'Wireless charger',
    status: 'PUBLISHED',
    requiresShipping: true,
    seoTitle: 'Wireless Charger',
    seoDescription: 'Buy Wireless Charger',
    groups: [],
    labels: [],
    tags: [{ id: 'tag-1', title: 'New', slug: 'new' }],
    primaryCategory: mockCategories[0],
    featuresV2: [],
    optionsV2: [],
    variants: [
      createVariant({
        id: 'var-31',
        productId: 'prod-5',
        productTitle: 'Wireless Charger',
        title: 'Default',
        price: 290000,
        sku: 'CHARGER-WHT',
        categories: [mockCategories[0]],
        featuresV2: [],
        variantSortIndex: 0,
        stockStatus: 'IN_STOCK',
        weight: 120,
        weightUnit: 'GR',
        length: 100,
        width: 100,
        height: 8,
        dimensionUnit: 'MM',
      }),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// All variants flat list
export const mockVariants = mockProducts.flatMap((p) => p.variants);

// Current logged in user
export const currentUser = mockUsers[0];
