mutation MemberRemove($input: MemberRemoveInput!) {
  organizationMutation {
    memberRemove(input: $input) {
      removedMemberId
      userErrors {
        code
        message
        field
      }
    }
  }
}
