query OrganizationRoles {
  storeQuery {
    currentStore {
      id
      name
      slug
      membership {
        domain
        roles {
          id
          name
          displayName
          description
          isSystem
          domain
          permissions {
            resource
            actions
            effect
          }
          createdAt
        }
      }
    }
  }
}
