mutation OrganizationCreate($input: OrganizationCreateInput!) {
  organizationMutation {
    organizationCreate(input: $input) {
      organization {
        id
        name
        displayName
        createdAt
        updatedAt
        membership {
          domain
          roles {
            id
            name
            displayName
            isSystem
          }
          members {
            id
            user {
              id
              email
            }
            role
            grantedAt
          }
        }
      }
      userErrors {
        field
        message
        code
      }
    }
  }
}
