mutation OrganizationDelete($id: ID!) {
  organizationMutation {
    organizationDelete(id: $id) {
      deletedOrganizationId
      userErrors {
        code
        message
        field
      }
    }
  }
}
