query Organizations(
  $first: Int
  $after: String
  $last: Int
  $before: String
  $where: OrganizationWhereInput
  $orderBy: [OrganizationOrderByInput!]
) {
  organizationQuery {
    organizations(
      first: $first
      after: $after
      last: $last
      before: $before
      where: $where
      orderBy: $orderBy
    ) {
      edges {
        cursor
        node {
          id
          name
          displayName
          createdAt
          updatedAt
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
}
