mutation OwnershipTransfer($input: OwnershipTransferInput!) {
  organizationMutation {
    ownershipTransfer(input: $input) {
      success
      userErrors {
        code
        message
        field
      }
    }
  }
}
