"use client";
import { useCallback, useMemo, useState } from "react";
import { Alert, Button, Flex, Select, Tag, Typography } from "antd"; import { PlusOutlined } from "@ant-design/icons";
import { AgGridReact, type CustomCellRendererProps } from "ag-grid-react"; import { AllCommunityModule, ModuleRegistry, type ColDef } from "ag-grid-community";
import { DataLayout } from "@/layouts/data"; import { useAgGridTheme } from "@/hooks"; import { CursorPagination } from "@/ui-kit/cursor-pagination";
import { CustomerMergeOrderField, CustomerMergeStatus, SortDirection, type ApiCustomerMerge } from "@/graphql/types";
import { useCustomerMerges } from "../hooks"; import { useCustomerMergeModal } from "../modals";
ModuleRegistry.registerModules([AllCommunityModule]);
function PairCell({ data }: CustomCellRendererProps<ApiCustomerMerge>) { return data ? <Flex vertical><Typography.Text strong>{data.sourceCustomer.displayName} → {data.targetCustomer.displayName}</Typography.Text><Typography.Text type="secondary">{data.reason ?? "No reason"}</Typography.Text></Flex> : null; }
export default function CustomerMergesPage() { const theme = useAgGridTheme(); const [status, setStatus] = useState<CustomerMergeStatus | null>(null); const [history, setHistory] = useState<Array<string | null>>([null]); const [page, setPage] = useState(0); const query = useCustomerMerges({ first: 20, after: history[page], where: status ? { status: { _eq: status } } : null, orderBy: [{ field: CustomerMergeOrderField.RequestedAt, direction: SortDirection.Desc }] }); const { push } = useCustomerMergeModal(); const create = useCallback(() => push({ mode: "create", onSaved: query.refetch }), [push, query.refetch]); const edit = useCallback((merge: ApiCustomerMerge) => push({ mode: "edit", entityId: merge.id, onSaved: query.refetch }), [push, query.refetch]); const columns = useMemo<ColDef<ApiCustomerMerge>[]>(() => [{ headerName: "Customers", cellRenderer: PairCell, minWidth: 360, flex: 2 }, { headerName: "Status", field: "status", cellRenderer: ({ value }: CustomCellRendererProps<ApiCustomerMerge>) => <Tag>{String(value).toLowerCase().replaceAll("_", " ")}</Tag>, width: 150 }, { headerName: "Requested", field: "requestedAt", valueFormatter: ({ value }) => value ? new Date(value).toLocaleString() : "", width: 190 }, { headerName: "Finished", field: "finishedAt", valueFormatter: ({ value }) => value ? new Date(value).toLocaleString() : "—", width: 190 }], []); return <DataLayout fullWidth name="customer-merges" title="Customer merges" count={query.totalCount} actions={<Button icon={<PlusOutlined />} onClick={create}>Merge customers</Button>}><DataLayout.Toolbar left={<Select allowClear placeholder="All statuses" value={status} options={Object.values(CustomerMergeStatus).map((value) => ({ value, label: value.toLowerCase().replaceAll("_", " ") }))} onChange={(value) => { setStatus(value ?? null); setPage(0); setHistory([null]); }} style={{ width: 220 }} />} /><div style={{ height: "100%", paddingBottom: 16, display: "flex", flexDirection: "column" }}>{query.error ? <Alert type="error" showIcon message={query.error.message} /> : null}<div style={{ flex: 1 }} data-testid="customer-merges-table"><AgGridReact<ApiCustomerMerge> theme={theme} rowData={query.merges} loading={query.loading} columnDefs={columns} getRowId={({ data }) => data.id} rowHeight={58} onRowClicked={({ data }) => data && edit(data)} rowStyle={{ cursor: "pointer" }} /></div><CursorPagination name="customer-merges" total={query.totalCount} rangeStart={page * 20 + (query.merges.length ? 1 : 0)} rangeEnd={page * 20 + query.merges.length} pageSize={20} pageSizeOptions={[20]} hasNext={query.pageInfo?.hasNextPage ?? false} hasPrev={page > 0} onNext={() => { const cursor = query.pageInfo?.endCursor; if (!cursor) return; setHistory((items) => [...items.slice(0, page + 1), cursor]); setPage((value) => value + 1); }} onPrev={() => setPage((value) => Math.max(0, value - 1))} onPageSizeChange={() => undefined} /></div></DataLayout>; }
