export const allowedCountries = ['UA', 'US', 'GB', 'DE', 'FR'];

export const shopCountries = [
  { value: 'AF', name: 'Afghanistan' },
  { value: 'AL', name: 'Albania' },
  { value: 'DZ', name: 'Algeria' },
  { value: 'AD', name: 'Andorra' },
  { value: 'AO', name: 'Angola' },
  { value: 'AR', name: 'Argentina' },
  { value: 'AM', name: 'Armenia' },
  { value: 'AU', name: 'Australia' },
  { value: 'AT', name: 'Austria' },
  { value: 'AZ', name: 'Azerbaijan' },
  { value: 'BS', name: 'Bahamas' },
  { value: 'BH', name: 'Bahrain' },
  { value: 'BD', name: 'Bangladesh' },
  { value: 'BE', name: 'Belgium' },
  { value: 'BR', name: 'Brazil' },
  { value: 'BG', name: 'Bulgaria' },
  { value: 'CA', name: 'Canada' },
  { value: 'CL', name: 'Chile' },
  { value: 'CN', name: 'China' },
  { value: 'CO', name: 'Colombia' },
  { value: 'HR', name: 'Croatia' },
  { value: 'CY', name: 'Cyprus' },
  { value: 'CZ', name: 'Czechia' },
  { value: 'DK', name: 'Denmark' },
  { value: 'EG', name: 'Egypt' },
  { value: 'EE', name: 'Estonia' },
  { value: 'FI', name: 'Finland' },
  { value: 'FR', name: 'France' },
  { value: 'GE', name: 'Georgia' },
  { value: 'DE', name: 'Germany' },
  { value: 'GR', name: 'Greece' },
  { value: 'HK', name: 'Hong Kong' },
  { value: 'HU', name: 'Hungary' },
  { value: 'IS', name: 'Iceland' },
  { value: 'IN', name: 'India' },
  { value: 'ID', name: 'Indonesia' },
  { value: 'IE', name: 'Ireland' },
  { value: 'IL', name: 'Israel' },
  { value: 'IT', name: 'Italy' },
  { value: 'JP', name: 'Japan' },
  { value: 'KZ', name: 'Kazakhstan' },
  { value: 'KE', name: 'Kenya' },
  { value: 'KR', name: 'South Korea' },
  { value: 'KW', name: 'Kuwait' },
  { value: 'LV', name: 'Latvia' },
  { value: 'LB', name: 'Lebanon' },
  { value: 'LT', name: 'Lithuania' },
  { value: 'LU', name: 'Luxembourg' },
  { value: 'MY', name: 'Malaysia' },
  { value: 'MT', name: 'Malta' },
  { value: 'MX', name: 'Mexico' },
  { value: 'MD', name: 'Moldova' },
  { value: 'MC', name: 'Monaco' },
  { value: 'MA', name: 'Morocco' },
  { value: 'NL', name: 'Netherlands' },
  { value: 'NZ', name: 'New Zealand' },
  { value: 'NG', name: 'Nigeria' },
  { value: 'NO', name: 'Norway' },
  { value: 'PK', name: 'Pakistan' },
  { value: 'PE', name: 'Peru' },
  { value: 'PH', name: 'Philippines' },
  { value: 'PL', name: 'Poland' },
  { value: 'PT', name: 'Portugal' },
  { value: 'QA', name: 'Qatar' },
  { value: 'RO', name: 'Romania' },
  { value: 'SA', name: 'Saudi Arabia' },
  { value: 'RS', name: 'Serbia' },
  { value: 'SG', name: 'Singapore' },
  { value: 'SK', name: 'Slovakia' },
  { value: 'SI', name: 'Slovenia' },
  { value: 'ZA', name: 'South Africa' },
  { value: 'ES', name: 'Spain' },
  { value: 'SE', name: 'Sweden' },
  { value: 'CH', name: 'Switzerland' },
  { value: 'TW', name: 'Taiwan' },
  { value: 'TH', name: 'Thailand' },
  { value: 'TR', name: 'Turkey' },
  { value: 'UA', name: 'Ukraine' },
  { value: 'AE', name: 'United Arab Emirates' },
  { value: 'GB', name: 'United Kingdom' },
  { value: 'US', name: 'United States' },
  { value: 'UY', name: 'Uruguay' },
  { value: 'VN', name: 'Vietnam' },
];
