export const allowedCurrencies = ['UAH', 'USD', 'EUR', 'GBP'];

export const currencies = [
  { value: 'USD', name: 'US Dollar (USD)' },
  { value: 'EUR', name: 'Euro (EUR)' },
  { value: 'GBP', name: 'British Pound (GBP)' },
  { value: 'UAH', name: 'Ukrainian Hryvnia (UAH)' },
  { value: 'CAD', name: 'Canadian Dollar (CAD)' },
  { value: 'AUD', name: 'Australian Dollar (AUD)' },
  { value: 'JPY', name: 'Japanese Yen (JPY)' },
  { value: 'CHF', name: 'Swiss Franc (CHF)' },
  { value: 'CNY', name: 'Chinese Yuan (CNY)' },
  { value: 'INR', name: 'Indian Rupee (INR)' },
  { value: 'BRL', name: 'Brazilian Real (BRL)' },
  { value: 'MXN', name: 'Mexican Peso (MXN)' },
  { value: 'PLN', name: 'Polish Zloty (PLN)' },
  { value: 'SEK', name: 'Swedish Krona (SEK)' },
  { value: 'NOK', name: 'Norwegian Krone (NOK)' },
  { value: 'DKK', name: 'Danish Krone (DKK)' },
  { value: 'CZK', name: 'Czech Koruna (CZK)' },
  { value: 'HUF', name: 'Hungarian Forint (HUF)' },
  { value: 'RON', name: 'Romanian Leu (RON)' },
  { value: 'TRY', name: 'Turkish Lira (TRY)' },
  { value: 'ZAR', name: 'South African Rand (ZAR)' },
  { value: 'SGD', name: 'Singapore Dollar (SGD)' },
  { value: 'HKD', name: 'Hong Kong Dollar (HKD)' },
  { value: 'KRW', name: 'South Korean Won (KRW)' },
  { value: 'NZD', name: 'New Zealand Dollar (NZD)' },
];
