export const currenciesSettings = {
  AFN: {
    code: 'AFN',
    decimalPlaces: 0,
    name: 'Afghan Afghani',
    namePlural: 'Afghan Afghanis',
    symbol: 'Af',
    symbolNative: '؋',
  },
  ALL: {
    code: 'ALL',
    decimalPlaces: 0,
    name: 'Albanian Lek',
    namePlural: 'Albanian lekë',
    symbol: 'ALL',
    symbolNative: 'Lek',
  },
  DZD: {
    code: 'DZD',
    decimalPlaces: 2,
    name: 'Algerian Dinar',
    namePlural: 'Algerian dinars',
    symbol: 'DA',
    symbolNative: 'د.ج.',
  },
  ARS: {
    code: 'ARS',
    decimalPlaces: 2,
    name: 'Argentine Peso',
    namePlural: 'Argentine pesos',
    symbol: 'AR$',
    symbolNative: '$',
  },
  AMD: {
    code: 'AMD',
    decimalPlaces: 0,
    name: 'Armenian Dram',
    namePlural: 'Armenian drams',
    symbol: 'AMD',
    symbolNative: 'դր.',
  },
  AUD: {
    code: 'AUD',
    decimalPlaces: 2,
    name: 'Australian Dollar',
    namePlural: 'Australian dollars',
    symbol: 'AU$',
    symbolNative: '$',
  },
  AZN: {
    code: 'AZN',
    decimalPlaces: 2,
    name: 'Azerbaijani Manat',
    namePlural: 'Azerbaijani manats',
    symbol: 'man.',
    symbolNative: 'ман.',
  },
  BHD: {
    code: 'BHD',
    decimalPlaces: 3,
    name: 'Bahraini Dinar',
    namePlural: 'Bahraini dinars',
    symbol: 'BD',
    symbolNative: 'د.ب.',
  },
  BDT: {
    code: 'BDT',
    decimalPlaces: 2,
    name: 'Bangladeshi Taka',
    namePlural: 'Bangladeshi takas',
    symbol: 'Tk',
    symbolNative: '৳',
  },
  BYN: {
    code: 'BYN',
    decimalPlaces: 2,
    name: 'Belarusian Ruble',
    namePlural: 'Belarusian rubles',
    symbol: 'Br',
    symbolNative: 'руб.',
  },
  BZD: {
    code: 'BZD',
    decimalPlaces: 2,
    name: 'Belize Dollar',
    namePlural: 'Belize dollars',
    symbol: 'BZ$',
    symbolNative: '$',
  },
  BOB: {
    code: 'BOB',
    decimalPlaces: 2,
    name: 'Bolivian Boliviano',
    namePlural: 'Bolivian bolivianos',
    symbol: 'Bs',
    symbolNative: 'Bs',
  },
  BAM: {
    code: 'BAM',
    decimalPlaces: 2,
    name: 'Bosnia-Herzegovina Convertible Mark',
    namePlural: 'Bosnia-Herzegovina convertible marks',
    symbol: 'KM',
    symbolNative: 'KM',
  },
  BWP: {
    code: 'BWP',
    decimalPlaces: 2,
    name: 'Botswanan Pula',
    namePlural: 'Botswanan pulas',
    symbol: 'BWP',
    symbolNative: 'P',
  },
  BRL: {
    code: 'BRL',
    decimalPlaces: 2,
    name: 'Brazilian Real',
    namePlural: 'Brazilian reals',
    symbol: 'R$',
    symbolNative: 'R$',
  },
  GBP: {
    code: 'GBP',
    decimalPlaces: 2,
    name: 'British Pound',
    namePlural: 'British pounds sterling',
    symbol: '£',
    symbolNative: '£',
  },
  BND: {
    code: 'BND',
    decimalPlaces: 2,
    name: 'Brunei Dollar',
    namePlural: 'Brunei dollars',
    symbol: 'BN$',
    symbolNative: '$',
  },
  BGN: {
    code: 'BGN',
    decimalPlaces: 2,
    name: 'Bulgarian Lev',
    namePlural: 'Bulgarian leva',
    symbol: 'BGN',
    symbolNative: 'лв.',
  },
  BIF: {
    code: 'BIF',
    decimalPlaces: 0,
    name: 'Burundian Franc',
    namePlural: 'Burundian francs',
    symbol: 'FBu',
    symbolNative: 'FBu',
  },
  KHR: {
    code: 'KHR',
    decimalPlaces: 2,
    name: 'Cambodian Riel',
    namePlural: 'Cambodian riels',
    symbol: 'KHR',
    symbolNative: '៛',
  },
  CAD: {
    code: 'CAD',
    decimalPlaces: 2,
    name: 'Canadian Dollar',
    namePlural: 'Canadian dollars',
    symbol: 'CA$',
    symbolNative: '$',
  },
  CVE: {
    code: 'CVE',
    decimalPlaces: 2,
    name: 'Cape Verdean Escudo',
    namePlural: 'Cape Verdean escudos',
    symbol: 'CV$',
    symbolNative: 'CV$',
  },
  XAF: {
    code: 'XAF',
    decimalPlaces: 0,
    name: 'Central African CFA Franc',
    namePlural: 'CFA francs BEAC',
    symbol: 'FCFA',
    symbolNative: 'FCFA',
  },
  CLP: {
    code: 'CLP',
    decimalPlaces: 0,
    name: 'Chilean Peso',
    namePlural: 'Chilean pesos',
    symbol: 'CL$',
    symbolNative: '$',
  },
  CNY: {
    code: 'CNY',
    decimalPlaces: 2,
    name: 'Chinese Yuan',
    namePlural: 'Chinese yuan',
    symbol: 'CN¥',
    symbolNative: 'CN¥',
  },
  COP: {
    code: 'COP',
    decimalPlaces: 0,
    name: 'Colombian Peso',
    namePlural: 'Colombian pesos',
    symbol: 'CO$',
    symbolNative: '$',
  },
  KMF: {
    code: 'KMF',
    decimalPlaces: 0,
    name: 'Comorian Franc',
    namePlural: 'Comorian francs',
    symbol: 'CF',
    symbolNative: 'FC',
  },
  CDF: {
    code: 'CDF',
    decimalPlaces: 2,
    name: 'Congolese Franc',
    namePlural: 'Congolese francs',
    symbol: 'CDF',
    symbolNative: 'FrCD',
  },
  CRC: {
    code: 'CRC',
    decimalPlaces: 0,
    name: 'Costa Rican Colón',
    namePlural: 'Costa Rican colóns',
    symbol: '₡',
    symbolNative: '₡',
  },
  HRK: {
    code: 'HRK',
    decimalPlaces: 2,
    name: 'Croatian Kuna',
    namePlural: 'Croatian kunas',
    symbol: 'kn',
    symbolNative: 'kn',
  },
  CZK: {
    code: 'CZK',
    decimalPlaces: 2,
    name: 'Czech Koruna',
    namePlural: 'Czech Republic korunas',
    symbol: 'Kč',
    symbolNative: 'Kč',
  },
  DKK: {
    code: 'DKK',
    decimalPlaces: 2,
    name: 'Danish Krone',
    namePlural: 'Danish kroner',
    symbol: 'Dkr',
    symbolNative: 'kr',
  },
  DJF: {
    code: 'DJF',
    decimalPlaces: 0,
    name: 'Djiboutian Franc',
    namePlural: 'Djiboutian francs',
    symbol: 'Fdj',
    symbolNative: 'Fdj',
  },
  DOP: {
    code: 'DOP',
    decimalPlaces: 2,
    name: 'Dominican Peso',
    namePlural: 'Dominican pesos',
    symbol: 'RD$',
    symbolNative: 'RD$',
  },
  EGP: {
    code: 'EGP',
    decimalPlaces: 2,
    name: 'Egyptian Pound',
    namePlural: 'Egyptian pounds',
    symbol: 'EGP',
    symbolNative: 'ج.م.',
  },
  ERN: {
    code: 'ERN',
    decimalPlaces: 2,
    name: 'Eritrean Nakfa',
    namePlural: 'Eritrean nakfas',
    symbol: 'Nfk',
    symbolNative: 'Nfk',
  },
  EEK: {
    code: 'EEK',
    decimalPlaces: 2,
    name: 'Estonian Kroon',
    namePlural: 'Estonian kroons',
    symbol: 'Ekr',
    symbolNative: 'kr',
  },
  ETB: {
    code: 'ETB',
    decimalPlaces: 2,
    name: 'Ethiopian Birr',
    namePlural: 'Ethiopian birrs',
    symbol: 'Br',
    symbolNative: 'Br',
  },
  EUR: {
    code: 'EUR',
    decimalPlaces: 2,
    name: 'Euro',
    namePlural: 'euros',
    symbol: '€',
    symbolNative: '€',
  },
  GEL: {
    code: 'GEL',
    decimalPlaces: 2,
    name: 'Georgian Lari',
    namePlural: 'Georgian laris',
    symbol: 'GEL',
    symbolNative: 'GEL',
  },
  GHS: {
    code: 'GHS',
    decimalPlaces: 2,
    name: 'Ghanaian Cedi',
    namePlural: 'Ghanaian cedis',
    symbol: 'GH₵',
    symbolNative: 'GH₵',
  },
  GTQ: {
    code: 'GTQ',
    decimalPlaces: 2,
    name: 'Guatemalan Quetzal',
    namePlural: 'Guatemalan quetzals',
    symbol: 'GTQ',
    symbolNative: 'Q',
  },
  GNF: {
    code: 'GNF',
    decimalPlaces: 0,
    name: 'Guinean Franc',
    namePlural: 'Guinean francs',
    symbol: 'FG',
    symbolNative: 'FG',
  },
  HNL: {
    code: 'HNL',
    decimalPlaces: 2,
    name: 'Honduran Lempira',
    namePlural: 'Honduran lempiras',
    symbol: 'HNL',
    symbolNative: 'L',
  },
  HKD: {
    code: 'HKD',
    decimalPlaces: 2,
    name: 'Hong Kong Dollar',
    namePlural: 'Hong Kong dollars',
    symbol: 'HK$',
    symbolNative: '$',
  },
  HUF: {
    code: 'HUF',
    decimalPlaces: 0,
    name: 'Hungarian Forint',
    namePlural: 'Hungarian forints',
    symbol: 'Ft',
    symbolNative: 'Ft',
  },
  ISK: {
    code: 'ISK',
    decimalPlaces: 0,
    name: 'Icelandic Króna',
    namePlural: 'Icelandic krónur',
    symbol: 'Ikr',
    symbolNative: 'kr',
  },
  INR: {
    code: 'INR',
    decimalPlaces: 2,
    name: 'Indian Rupee',
    namePlural: 'Indian rupees',
    symbol: 'Rs',
    symbolNative: 'টকা',
  },
  IDR: {
    code: 'IDR',
    decimalPlaces: 0,
    name: 'Indonesian Rupiah',
    namePlural: 'Indonesian rupiahs',
    symbol: 'Rp',
    symbolNative: 'Rp',
  },
  IRR: {
    code: 'IRR',
    decimalPlaces: 0,
    name: 'Iranian Rial',
    namePlural: 'Iranian rials',
    symbol: 'IRR',
    symbolNative: '﷼',
  },
  IQD: {
    code: 'IQD',
    decimalPlaces: 0,
    name: 'Iraqi Dinar',
    namePlural: 'Iraqi dinars',
    symbol: 'IQD',
    symbolNative: 'د.ع.',
  },
  ILS: {
    code: 'ILS',
    decimalPlaces: 2,
    name: 'Israeli New Shekel',
    namePlural: 'Israeli new sheqels',
    symbol: '₪',
    symbolNative: '₪',
  },
  JMD: {
    code: 'JMD',
    decimalPlaces: 2,
    name: 'Jamaican Dollar',
    namePlural: 'Jamaican dollars',
    symbol: 'J$',
    symbolNative: '$',
  },
  JPY: {
    code: 'JPY',
    decimalPlaces: 0,
    name: 'Japanese Yen',
    namePlural: 'Japanese yen',
    symbol: '¥',
    symbolNative: '￥',
  },
  JOD: {
    code: 'JOD',
    decimalPlaces: 3,
    name: 'Jordanian Dinar',
    namePlural: 'Jordanian dinars',
    symbol: 'JD',
    symbolNative: 'د.أ.',
  },
  KZT: {
    code: 'KZT',
    decimalPlaces: 2,
    name: 'Kazakhstani Tenge',
    namePlural: 'Kazakhstani tenges',
    symbol: 'KZT',
    symbolNative: 'тңг.',
  },
  KES: {
    code: 'KES',
    decimalPlaces: 2,
    name: 'Kenyan Shilling',
    namePlural: 'Kenyan shillings',
    symbol: 'Ksh',
    symbolNative: 'Ksh',
  },
  KWD: {
    code: 'KWD',
    decimalPlaces: 3,
    name: 'Kuwaiti Dinar',
    namePlural: 'Kuwaiti dinars',
    symbol: 'KD',
    symbolNative: 'د.ك.',
  },
  LVL: {
    code: 'LVL',
    decimalPlaces: 2,
    name: 'Latvian Lats',
    namePlural: 'Latvian lati',
    symbol: 'Ls',
    symbolNative: 'Ls',
  },
  LBP: {
    code: 'LBP',
    decimalPlaces: 0,
    name: 'Lebanese Pound',
    namePlural: 'Lebanese pounds',
    symbol: 'LB£',
    symbolNative: 'ل.ل.',
  },
  LYD: {
    code: 'LYD',
    decimalPlaces: 3,
    name: 'Libyan Dinar',
    namePlural: 'Libyan dinars',
    symbol: 'LD',
    symbolNative: 'د.ل.',
  },
  LTL: {
    code: 'LTL',
    decimalPlaces: 2,
    name: 'Lithuanian Litas',
    namePlural: 'Lithuanian litai',
    symbol: 'Lt',
    symbolNative: 'Lt',
  },
  MOP: {
    code: 'MOP',
    decimalPlaces: 2,
    name: 'Macanese Pataca',
    namePlural: 'Macanese patacas',
    symbol: 'MOP$',
    symbolNative: 'MOP$',
  },
  MKD: {
    code: 'MKD',
    decimalPlaces: 2,
    name: 'Macedonian Denar',
    namePlural: 'Macedonian denari',
    symbol: 'MKD',
    symbolNative: 'MKD',
  },
  MGA: {
    code: 'MGA',
    decimalPlaces: 0,
    name: 'Malagasy Ariary',
    namePlural: 'Malagasy Ariaries',
    symbol: 'MGA',
    symbolNative: 'MGA',
  },
  MYR: {
    code: 'MYR',
    decimalPlaces: 2,
    name: 'Malaysian Ringgit',
    namePlural: 'Malaysian ringgits',
    symbol: 'RM',
    symbolNative: 'RM',
  },
  MUR: {
    code: 'MUR',
    decimalPlaces: 0,
    name: 'Mauritian Rupee',
    namePlural: 'Mauritian rupees',
    symbol: 'MURs',
    symbolNative: 'MURs',
  },
  MXN: {
    code: 'MXN',
    decimalPlaces: 2,
    name: 'Mexican Peso',
    namePlural: 'Mexican pesos',
    symbol: 'MX$',
    symbolNative: '$',
  },
  MDL: {
    code: 'MDL',
    decimalPlaces: 2,
    name: 'Moldovan Leu',
    namePlural: 'Moldovan lei',
    symbol: 'MDL',
    symbolNative: 'MDL',
  },
  MAD: {
    code: 'MAD',
    decimalPlaces: 2,
    name: 'Moroccan Dirham',
    namePlural: 'Moroccan dirhams',
    symbol: 'MAD',
    symbolNative: 'د.م.',
  },
  MZN: {
    code: 'MZN',
    decimalPlaces: 2,
    name: 'Mozambican Metical',
    namePlural: 'Mozambican meticals',
    symbol: 'MTn',
    symbolNative: 'MTn',
  },
  MMK: {
    code: 'MMK',
    decimalPlaces: 0,
    name: 'Myanmar Kyat',
    namePlural: 'Myanma kyats',
    symbol: 'MMK',
    symbolNative: 'K',
  },
  NAD: {
    code: 'NAD',
    decimalPlaces: 2,
    name: 'Namibian Dollar',
    namePlural: 'Namibian dollars',
    symbol: 'N$',
    symbolNative: 'N$',
  },
  NPR: {
    code: 'NPR',
    decimalPlaces: 2,
    name: 'Nepalese Rupee',
    namePlural: 'Nepalese rupees',
    symbol: 'NPRs',
    symbolNative: 'नेरू',
  },
  TWD: {
    code: 'TWD',
    decimalPlaces: 2,
    name: 'New Taiwan Dollar',
    namePlural: 'New Taiwan dollars',
    symbol: 'NT$',
    symbolNative: 'NT$',
  },
  NZD: {
    code: 'NZD',
    decimalPlaces: 2,
    name: 'New Zealand Dollar',
    namePlural: 'New Zealand dollars',
    symbol: 'NZ$',
    symbolNative: '$',
  },
  NIO: {
    code: 'NIO',
    decimalPlaces: 2,
    name: 'Nicaraguan Córdoba',
    namePlural: 'Nicaraguan córdobas',
    symbol: 'C$',
    symbolNative: 'C$',
  },
  NGN: {
    code: 'NGN',
    decimalPlaces: 2,
    name: 'Nigerian Naira',
    namePlural: 'Nigerian nairas',
    symbol: '₦',
    symbolNative: '₦',
  },
  NOK: {
    code: 'NOK',
    decimalPlaces: 2,
    name: 'Norwegian Krone',
    namePlural: 'Norwegian kroner',
    symbol: 'Nkr',
    symbolNative: 'kr',
  },
  OMR: {
    code: 'OMR',
    decimalPlaces: 3,
    name: 'Omani Rial',
    namePlural: 'Omani rials',
    symbol: 'OMR',
    symbolNative: 'ر.ع.',
  },
  PKR: {
    code: 'PKR',
    decimalPlaces: 0,
    name: 'Pakistani Rupee',
    namePlural: 'Pakistani rupees',
    symbol: 'PKRs',
    symbolNative: '₨',
  },
  PAB: {
    code: 'PAB',
    decimalPlaces: 2,
    name: 'Panamanian Balboa',
    namePlural: 'Panamanian balboas',
    symbol: 'B/.',
    symbolNative: 'B/.',
  },
  PYG: {
    code: 'PYG',
    decimalPlaces: 0,
    name: 'Paraguayan Guarani',
    namePlural: 'Paraguayan guaranis',
    symbol: '₲',
    symbolNative: '₲',
  },
  PEN: {
    code: 'PEN',
    decimalPlaces: 2,
    name: 'Peruvian Sol',
    namePlural: 'Peruvian nuevos soles',
    symbol: 'S/.',
    symbolNative: 'S/.',
  },
  PHP: {
    code: 'PHP',
    decimalPlaces: 2,
    name: 'Philippine Peso',
    namePlural: 'Philippine pesos',
    symbol: '₱',
    symbolNative: '₱',
  },
  PLN: {
    code: 'PLN',
    decimalPlaces: 2,
    name: 'Polish Zloty',
    namePlural: 'Polish zlotys',
    symbol: 'zł',
    symbolNative: 'zł',
  },
  QAR: {
    code: 'QAR',
    decimalPlaces: 2,
    name: 'Qatari Rial',
    namePlural: 'Qatari rials',
    symbol: 'QR',
    symbolNative: 'ر.ق.',
  },
  RON: {
    code: 'RON',
    decimalPlaces: 2,
    name: 'Romanian Leu',
    namePlural: 'Romanian lei',
    symbol: 'RON',
    symbolNative: 'RON',
  },
  RUB: {
    code: 'RUB',
    decimalPlaces: 2,
    name: 'Russian Ruble',
    namePlural: 'Russian rubles',
    symbol: 'RUB',
    symbolNative: '₽.',
  },
  RWF: {
    code: 'RWF',
    decimalPlaces: 0,
    name: 'Rwandan Franc',
    namePlural: 'Rwandan francs',
    symbol: 'RWF',
    symbolNative: 'FR',
  },
  SAR: {
    code: 'SAR',
    decimalPlaces: 2,
    name: 'Saudi Riyal',
    namePlural: 'Saudi riyals',
    symbol: 'SR',
    symbolNative: 'ر.س.',
  },
  RSD: {
    code: 'RSD',
    decimalPlaces: 0,
    name: 'Serbian Dinar',
    namePlural: 'Serbian dinars',
    symbol: 'din.',
    symbolNative: 'дин.',
  },
  SGD: {
    code: 'SGD',
    decimalPlaces: 2,
    name: 'Singapore Dollar',
    namePlural: 'Singapore dollars',
    symbol: 'S$',
    symbolNative: '$',
  },
  SOS: {
    code: 'SOS',
    decimalPlaces: 0,
    name: 'Somali Shilling',
    namePlural: 'Somali shillings',
    symbol: 'Ssh',
    symbolNative: 'Ssh',
  },
  ZAR: {
    code: 'ZAR',
    decimalPlaces: 2,
    name: 'South African Rand',
    namePlural: 'South African rand',
    symbol: 'R',
    symbolNative: 'R',
  },
  KRW: {
    code: 'KRW',
    decimalPlaces: 0,
    name: 'South Korean Won',
    namePlural: 'South Korean won',
    symbol: '₩',
    symbolNative: '₩',
  },
  LKR: {
    code: 'LKR',
    decimalPlaces: 2,
    name: 'Sri Lankan Rupee',
    namePlural: 'Sri Lankan rupees',
    symbol: 'SLRs',
    symbolNative: 'SL Re',
  },
  SDG: {
    code: 'SDG',
    decimalPlaces: 2,
    name: 'Sudanese Pound',
    namePlural: 'Sudanese pounds',
    symbol: 'SDG',
    symbolNative: 'SDG',
  },
  SEK: {
    code: 'SEK',
    decimalPlaces: 2,
    name: 'Swedish Krona',
    namePlural: 'Swedish kronor',
    symbol: 'Skr',
    symbolNative: 'kr',
  },
  CHF: {
    code: 'CHF',
    name: 'Swiss Franc',
    decimalPlaces: 2,
    namePlural: 'Swiss francs',
    symbol: 'CHF',
    symbolNative: 'CHF',
    rounding: 0.05,
  },
  SYP: {
    code: 'SYP',
    decimalPlaces: 0,
    name: 'Syrian Pound',
    namePlural: 'Syrian pounds',
    symbol: 'SY£',
    symbolNative: 'ل.س.',
  },
  TZS: {
    code: 'TZS',
    decimalPlaces: 0,
    name: 'Tanzanian Shilling',
    namePlural: 'Tanzanian shillings',
    symbol: 'TSh',
    symbolNative: 'TSh',
  },
  THB: {
    code: 'THB',
    decimalPlaces: 2,
    name: 'Thai Baht',
    namePlural: 'Thai baht',
    symbol: '฿',
    symbolNative: '฿',
  },
  TOP: {
    code: 'TOP',
    decimalPlaces: 2,
    name: 'Tongan Paʻanga',
    namePlural: 'Tongan paʻanga',
    symbol: 'T$',
    symbolNative: 'T$',
  },
  TTD: {
    code: 'TTD',
    decimalPlaces: 2,
    name: 'Trinidad & Tobago Dollar',
    namePlural: 'Trinidad and Tobago dollars',
    symbol: 'TT$',
    symbolNative: '$',
  },
  TND: {
    code: 'TND',
    decimalPlaces: 3,
    name: 'Tunisian Dinar',
    namePlural: 'Tunisian dinars',
    symbol: 'DT',
    symbolNative: 'د.ت.',
  },
  TRY: {
    code: 'TRY',
    decimalPlaces: 2,
    name: 'Turkish Lira',
    namePlural: 'Turkish Lira',
    symbol: 'TL',
    symbolNative: '₺',
  },
  USD: {
    code: 'USD',
    decimalPlaces: 2,
    name: 'US Dollar',
    namePlural: 'US dollars',
    symbol: '$',
    symbolNative: '$',
  },
  UGX: {
    code: 'UGX',
    decimalPlaces: 0,
    name: 'Ugandan Shilling',
    namePlural: 'Ugandan shillings',
    symbol: 'USh',
    symbolNative: 'USh',
  },
  UAH: {
    code: 'UAH',
    decimalPlaces: 2,
    name: 'Ukrainian Hryvnia',
    namePlural: 'Ukrainian hryvnias',
    symbol: '₴',
    symbolNative: '₴',
  },
  AED: {
    code: 'AED',
    decimalPlaces: 2,
    name: 'United Arab Emirates Dirham',
    namePlural: 'UAE dirhams',
    symbol: 'AED',
    symbolNative: 'د.إ.',
  },
  UYU: {
    code: 'UYU',
    decimalPlaces: 2,
    name: 'Uruguayan Peso',
    namePlural: 'Uruguayan pesos',
    symbol: '$U',
    symbolNative: '$',
  },
  UZS: {
    code: 'UZS',
    decimalPlaces: 0,
    name: 'Uzbekistani Som',
    namePlural: 'Uzbekistan som',
    symbol: 'UZS',
    symbolNative: 'UZS',
  },
  VEF: {
    code: 'VEF',
    decimalPlaces: 2,
    name: 'Venezuelan Bolívar',
    namePlural: 'Venezuelan bolívars',
    symbol: 'Bs.F.',
    symbolNative: 'Bs.F.',
  },
  VND: {
    code: 'VND',
    decimalPlaces: 0,
    name: 'Vietnamese Dong',
    namePlural: 'Vietnamese dong',
    symbol: '₫',
    symbolNative: '₫',
  },
  XOF: {
    code: 'XOF',
    decimalPlaces: 0,
    name: 'West African CFA Franc',
    namePlural: 'CFA francs BCEAO',
    symbol: 'CFA',
    symbolNative: 'CFA',
  },
  YER: {
    code: 'YER',
    decimalPlaces: 0,
    name: 'Yemeni Rial',
    namePlural: 'Yemeni rials',
    symbol: 'YR',
    symbolNative: 'ر.ي.',
  },
  ZMK: {
    code: 'ZMK',
    decimalPlaces: 0,
    name: 'Zambian Kwacha',
    namePlural: 'Zambian kwachas',
    symbol: 'ZK',
    symbolNative: 'ZK',
  },
  ZWL: {
    code: 'ZWL',
    decimalPlaces: 0,
    name: 'Zimbabwean Dollar',
    namePlural: 'Zimbabwean Dollar',
    symbol: 'ZWL$',
    symbolNative: 'ZWL$',
  },
};
