export const allowedCurrencies = ['UAH', 'USD', 'EUR'];

export const currencies = [
  { value: 'USD', name: 'US dollars (USD)' },
  { value: 'EUR', name: 'Euros (EUR)' },
  { value: 'GBP', name: 'British pounds (GBP)' },
  { value: 'CAD', name: 'Canadian dollars (CAD)' },
  { value: 'AFN', name: 'Afghan Afghanis (AFN)' },
  { value: 'ALL', name: 'Albanian lekë (ALL)' },
  { value: 'DZD', name: 'Algerian dinars (DZD)' },
  { value: 'AOA', name: 'Angolan kwanzas (AOA)' },
  { value: 'ARS', name: 'Argentine pesos (ARS)' },
  { value: 'AMD', name: 'Armenian drams (AMD)' },
  { value: 'AWG', name: 'Aruban florin (AWG)' },
  { value: 'AUD', name: 'Australian dollars (AUD)' },
  { value: 'BBD', name: 'Barbadian dollars (BBD)' },
  { value: 'AZN', name: 'Azerbaijani manats (AZN)' },
  { value: 'BDT', name: 'Bangladeshi takas (BDT)' },
  { value: 'BSD', name: 'Bahamian dollars (BSD)' },
  { value: 'BHD', name: 'Bahraini dinars (BHD)' },
  { value: 'BIF', name: 'Burundian francs (BIF)' },
  { value: 'BYN', name: 'Belarusian rubles (BYN)' },
  { value: 'BZD', name: 'Belize dollars (BZD)' },
  { value: 'BMD', name: 'Bermudan dollars (BMD)' },
  { value: 'BTN', name: 'Bhutanese ngultrums (BTN)' },
  { value: 'BAM', name: 'Bosnia-Herzegovina convertible marks (BAM)' },
  { value: 'BRL', name: 'Brazilian reals (BRL)' },
  { value: 'BOB', name: 'Bolivian bolivianos (BOB)' },
  { value: 'BWP', name: 'Botswanan pulas (BWP)' },
  { value: 'BND', name: 'Brunei dollars (BND)' },
  { value: 'BGN', name: 'Bulgarian leva (BGN)' },
  { value: 'MMK', name: 'Myanmar kyats (MMK)' },
  { value: 'KHR', name: 'Cambodian riels (KHR)' },
  { value: 'CVE', name: 'Cape Verdean escudos (CVE)' },
  { value: 'KYD', name: 'Cayman Islands dollars (KYD)' },
  { value: 'XAF', name: 'Central African CFA francs (XAF)' },
  { value: 'CLP', name: 'Chilean pesos (CLP)' },
  { value: 'CNY', name: 'Chinese yuan (CNY)' },
  { value: 'COP', name: 'Colombian pesos (COP)' },
  { value: 'KMF', name: 'Comorian francs (KMF)' },
  { value: 'CDF', name: 'Congolese francs (CDF)' },
  { value: 'CRC', name: 'Costa Rican colóns (CRC)' },
  { value: 'HRK', name: 'Croatian kunas (HRK)' },
  { value: 'CZK', name: 'Czech korunas (CZK)' },
  { value: 'DKK', name: 'Danish kroner (DKK)' },
  { value: 'DJF', name: 'Djiboutian francs (DJF)' },
  { value: 'DOP', name: 'Dominican pesos (DOP)' },
  { value: 'XCD', name: 'East Caribbean dollars (XCD)' },
  { value: 'EGP', name: 'Egyptian pounds (EGP)' },
  { value: 'ERN', name: 'Eritrean nakfas (ERN)' },
  { value: 'ETB', name: 'Ethiopian birrs (ETB)' },
  { value: 'FKP', name: 'Falkland Islands pounds (FKP)' },
  { value: 'XPF', name: 'CFP francs (XPF)' },
  { value: 'FJD', name: 'Fijian dollars (FJD)' },
  { value: 'GIP', name: 'Gibraltar pounds (GIP)' },
  { value: 'GMD', name: 'Gambian dalasis (GMD)' },
  { value: 'GHS', name: 'Ghanaian cedis (GHS)' },
  { value: 'GTQ', name: 'Guatemalan quetzals (GTQ)' },
  { value: 'GYD', name: 'Guyanaese dollars (GYD)' },
  { value: 'GEL', name: 'Georgian laris (GEL)' },
  { value: 'GNF', name: 'Guinean francs (GNF)' },
  { value: 'HTG', name: 'Haitian gourdes (HTG)' },
  { value: 'HNL', name: 'Honduran lempiras (HNL)' },
  { value: 'HKD', name: 'Hong Kong dollars (HKD)' },
  { value: 'HUF', name: 'Hungarian forints (HUF)' },
  { value: 'ISK', name: 'Icelandic krónur (ISK)' },
  { value: 'INR', name: 'Indian rupees (INR)' },
  { value: 'IDR', name: 'Indonesian rupiahs (IDR)' },
  { value: 'ILS', name: 'Israeli new shekels (ILS)' },
  { value: 'IRR', name: 'Iranian rials (IRR)' },
  { value: 'IQD', name: 'Iraqi dinars (IQD)' },
  { value: 'JMD', name: 'Jamaican dollars (JMD)' },
  { value: 'JPY', name: 'Japanese yen (JPY)' },
  { value: 'JEP', name: 'JEP (JEP)' },
  { value: 'JOD', name: 'Jordanian dinars (JOD)' },
  { value: 'KZT', name: 'Kazakhstani tenges (KZT)' },
  { value: 'KES', name: 'Kenyan shillings (KES)' },
  { value: 'KID', name: 'KID (KID)' },
  { value: 'KWD', name: 'Kuwaiti dinars (KWD)' },
  { value: 'KGS', name: 'Kyrgystani soms (KGS)' },
  { value: 'LAK', name: 'Laotian kips (LAK)' },
  { value: 'LVL', name: 'LVL (LVL)' },
  { value: 'LBP', name: 'Lebanese pounds (LBP)' },
  { value: 'LSL', name: 'Lesotho lotis (LSL)' },
  { value: 'LRD', name: 'Liberian dollars (LRD)' },
  { value: 'LYD', name: 'Libyan dinars (LYD)' },
  { value: 'LTL', name: 'LTL (LTL)' },
  { value: 'MGA', name: 'Malagasy ariaries (MGA)' },
  { value: 'MKD', name: 'Macedonian denari (MKD)' },
  { value: 'MOP', name: 'Macanese patacas (MOP)' },
  { value: 'MWK', name: 'Malawian kwachas (MWK)' },
  { value: 'MVR', name: 'Maldivian rufiyaas (MVR)' },
  { value: 'MRU', name: 'Mauritanian ouguiyas (MRU)' },
  { value: 'MXN', name: 'Mexican pesos (MXN)' },
  { value: 'MYR', name: 'Malaysian ringgits (MYR)' },
  { value: 'MUR', name: 'Mauritian rupees (MUR)' },
  { value: 'MDL', name: 'Moldovan lei (MDL)' },
  { value: 'MAD', name: 'Moroccan dirhams (MAD)' },
  { value: 'MNT', name: 'Mongolian tugriks (MNT)' },
  { value: 'MZN', name: 'Mozambican meticals (MZN)' },
  { value: 'NAD', name: 'Namibian dollars (NAD)' },
  { value: 'NPR', name: 'Nepalese rupees (NPR)' },
  { value: 'ANG', name: 'Netherlands Antillean guilders (ANG)' },
  { value: 'NZD', name: 'New Zealand dollars (NZD)' },
  { value: 'NIO', name: 'Nicaraguan córdobas (NIO)' },
  { value: 'NGN', name: 'Nigerian nairas (NGN)' },
  { value: 'NOK', name: 'Norwegian kroner (NOK)' },
  { value: 'OMR', name: 'Omani rials (OMR)' },
  { value: 'PAB', name: 'Panamanian balboas (PAB)' },
  { value: 'PKR', name: 'Pakistani rupees (PKR)' },
  { value: 'PGK', name: 'Papua New Guinean kina (PGK)' },
  { value: 'PYG', name: 'Paraguayan guaranis (PYG)' },
  { value: 'PEN', name: 'Peruvian soles (PEN)' },
  { value: 'PHP', name: 'Philippine pesos (PHP)' },
  { value: 'PLN', name: 'Polish zlotys (PLN)' },
  { value: 'QAR', name: 'Qatari riyals (QAR)' },
  { value: 'RON', name: 'Romanian lei (RON)' },
  { value: 'RUB', name: 'Russian rubles (RUB)' },
  { value: 'RWF', name: 'Rwandan francs (RWF)' },
  { value: 'WST', name: 'Samoan tala (WST)' },
  { value: 'SHP', name: 'St. Helena pounds (SHP)' },
  { value: 'SAR', name: 'Saudi riyals (SAR)' },
  { value: 'RSD', name: 'Serbian dinars (RSD)' },
  { value: 'SCR', name: 'Seychellois rupees (SCR)' },
  { value: 'SLL', name: 'Sierra Leonean leones (1964—2 (SLL)' },
  { value: 'SGD', name: 'Singapore dollars (SGD)' },
  { value: 'SDG', name: 'Sudanese pounds (SDG)' },
  { value: 'SOS', name: 'Somali shillings (SOS)' },
  { value: 'SYP', name: 'Syrian pounds (SYP)' },
  { value: 'ZAR', name: 'South African rand (ZAR)' },
  { value: 'KRW', name: 'South Korean won (KRW)' },
  { value: 'SSP', name: 'South Sudanese pounds (SSP)' },
  { value: 'SBD', name: 'Solomon Islands dollars (SBD)' },
  { value: 'LKR', name: 'Sri Lankan rupees (LKR)' },
  { value: 'SRD', name: 'Surinamese dollars (SRD)' },
  { value: 'SZL', name: 'Swazi emalangeni (SZL)' },
  { value: 'SEK', name: 'Swedish kronor (SEK)' },
  { value: 'CHF', name: 'Swiss francs (CHF)' },
  { value: 'TWD', name: 'New Taiwan dollars (TWD)' },
  { value: 'THB', name: 'Thai baht (THB)' },
  { value: 'TJS', name: 'Tajikistani somonis (TJS)' },
  { value: 'TZS', name: 'Tanzanian shillings (TZS)' },
  { value: 'TOP', name: 'Tongan paʻanga (TOP)' },
  { value: 'TTD', name: 'Trinidad &amp; Tobago dollars (TTD)' },
  { value: 'TND', name: 'Tunisian dinars (TND)' },
  { value: 'TRY', name: 'Turkish Lira (TRY)' },
  { value: 'TMT', name: 'Turkmenistani manat (TMT)' },
  { value: 'UGX', name: 'Ugandan shillings (UGX)' },
  { value: 'UAH', name: 'Ukrainian hryvnias (UAH)' },
  { value: 'AED', name: 'UAE dirhams (AED)' },
  { value: 'UYU', name: 'Uruguayan pesos (UYU)' },
  { value: 'UZS', name: 'Uzbekistani som (UZS)' },
  { value: 'VUV', name: 'Vanuatu vatus (VUV)' },
  { value: 'VES', name: 'Venezuelan bolívars (VES)' },
  { value: 'VND', name: 'Vietnamese dong (VND)' },
  { value: 'XOF', name: 'West African CFA francs (XOF)' },
  { value: 'YER', name: 'Yemeni rials (YER)' },
  { value: 'ZMW', name: 'Zambian kwachas (ZMW)' },
  { value: 'BYR', name: 'BYR (BYR)' },
  { value: 'STD', name: 'STD (STD)' },
  { value: 'STN', name: 'São Tomé &amp; Príncipe dobras (STN)' },
  { value: 'VED', name: 'VED (VED)' },
  { value: 'VEF', name: 'VEF (VEF)' },
];
