"use client";
import { useCallback, useMemo, useState } from "react";
import { Alert, Button, Input, Typography } from "antd";
import { LuPlus as PlusOutlined } from "react-icons/lu";
import { AgGridReact, type CustomCellRendererProps } from "ag-grid-react";
import { AllCommunityModule, ModuleRegistry, type ColDef } from "ag-grid-community";
import { DataLayout } from "@/layouts/data"; import { useAgGridTheme } from "@/hooks"; import { CursorPagination } from "@/ui-kit/cursor-pagination";
import { CustomerTagOrderField, SortDirection, type ApiCustomerTag } from "@/graphql/types";
import { useCustomerTags } from "../hooks"; import { useCustomerTagModal } from "../modals";
ModuleRegistry.registerModules([AllCommunityModule]);
function TagCell({ data }: CustomCellRendererProps<ApiCustomerTag>) { return data ? <div><Typography.Text strong>{data.name}</Typography.Text><br /><Typography.Text type="secondary">{data.normalizedName}</Typography.Text></div> : null; }
export default function CustomerTagsPage() { const theme = useAgGridTheme(); const [search, setSearch] = useState(""); const [history, setHistory] = useState<Array<string | null>>([null]); const [page, setPage] = useState(0); const query = useCustomerTags({ first: 20, after: history[page], where: search ? { name: { _containsi: search } } : null, orderBy: [{ field: CustomerTagOrderField.Name, direction: SortDirection.Asc }] }); const { push } = useCustomerTagModal(); const create = useCallback(() => push({ mode: "create", onSaved: query.refetch }), [push, query.refetch]); const edit = useCallback((tag: ApiCustomerTag) => push({ mode: "edit", entityId: tag.id, onSaved: query.refetch }), [push, query.refetch]); const columns = useMemo<ColDef<ApiCustomerTag>[]>(() => [{ headerName: "Tag", cellRenderer: TagCell, minWidth: 280, flex: 2 }, { headerName: "Customers", field: "customersCount", width: 140 }, { headerName: "Updated", field: "updatedAt", valueFormatter: ({ value }) => value ? new Date(value).toLocaleDateString() : "", width: 160 }], []); return <DataLayout fullWidth name="customer-tags" title="Customer tags" count={query.totalCount} actions={<Button icon={<PlusOutlined />} onClick={create}>Create tag</Button>}><DataLayout.Toolbar left={<Input.Search allowClear placeholder="Search tags..." onSearch={(value) => { setSearch(value.trim()); setPage(0); setHistory([null]); }} style={{ width: 320 }} />} /><div style={{ height: "100%", paddingBottom: 16, display: "flex", flexDirection: "column" }}>{query.error ? <Alert type="error" showIcon message={query.error.message} /> : null}<div style={{ flex: 1 }} data-testid="customer-tags-table"><AgGridReact<ApiCustomerTag> theme={theme} rowData={query.tags} loading={query.loading} columnDefs={columns} getRowId={({ data }) => data.id} rowHeight={58} onRowClicked={({ data }) => data && edit(data)} rowStyle={{ cursor: "pointer" }} /></div><CursorPagination name="customer-tags" total={query.totalCount} rangeStart={page * 20 + (query.tags.length ? 1 : 0)} rangeEnd={page * 20 + query.tags.length} pageSize={20} pageSizeOptions={[20]} hasNext={query.pageInfo?.hasNextPage ?? false} hasPrev={page > 0} onNext={() => { const cursor = query.pageInfo?.endCursor; if (!cursor) return; setHistory((items) => [...items.slice(0, page + 1), cursor]); setPage((value) => value + 1); }} onPrev={() => setPage((value) => Math.max(0, value - 1))} onPageSizeChange={() => undefined} /></div></DataLayout>; }
