query BundleItem($id: ID!) {
  catalogQuery {
    node(id: $id) {
      ... on BundleItem {
        id
        groupId
        itemType
        sortIndex
        refProductId
        refVariantId
        title
        featuredImage {
          id
        }
        minQty
        maxQty
        defaultQty
        pricingTemplate {
          id
          name
          priceRule {
            id
            priceType
          }
        }
        visible
        selected
        createdAt
        updatedAt
      }
    }
  }
}
