mutation BundlePricingTemplateDelete($input: BundlePricingTemplatesSyncInput!) {
  catalogMutation {
    bundlePricingTemplatesSync(input: $input) {
      configuration {
        id
      }
      pricingTemplates {
        id
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
