mutation BundlePricingTemplateCreate($input: BundlePricingTemplatesSyncInput!) {
  catalogMutation {
    bundlePricingTemplatesSync(input: $input) {
      pricingTemplates {
        id
        name
        sortIndex
        priceRule {
          id
          priceType
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
