query BundlePricingTemplates($productId: ID!) {
  catalogQuery {
    bundle(id: $productId) {
      id
      configurations {
        id
        pricingTemplates {
          id
          name
          sortIndex
          priceRule {
            id
            priceType
          }
        }
      }
    }
  }
}
