mutation BundleItemUpdate($input: BundleGroupsSyncInput!) {
  catalogMutation {
    bundleGroupsSync(input: $input) {
      groups {
        id
        items {
          id
          groupId
          itemType
          sortIndex
          refProductId
          refVariantId
          title
          minQty
          maxQty
          defaultQty
          pricingTemplate {
            id
            name
          }
          visible
          selected
          createdAt
          updatedAt
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
