mutation BundleItemDelete($input: BundleGroupsSyncInput!) {
  catalogMutation {
    bundleGroupsSync(input: $input) {
      configuration {
        id
      }
      groups {
        id
        items {
          id
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
