query BundleGroup($id: ID!) {
  catalogQuery {
    node(id: $id) {
      ... on BundleGroup {
        id
        title
        sortIndex
        minSelection
        maxSelection
        items {
          id
          groupId
          itemType
          sortIndex
          refProductId
          refVariantId
          title
          minQty
          maxQty
          defaultQty
          pricingTemplate {
            id
            name
          }
          visible
          selected
        }
        createdAt
        updatedAt
      }
    }
  }
}
