query BundleGroups($productId: ID!) {
  catalogQuery {
    bundle(id: $productId) {
      id
      configurations {
        id
        groups {
          id
          title
          sortIndex
          minSelection
          maxSelection
          items {
            id
            groupId
            itemType
            sortIndex
            refProductId
            refVariantId
            title
            featuredImage {
              id
            }
            minQty
            maxQty
            defaultQty
            pricingTemplate {
              id
              name
              priceRule {
                id
                priceType
              }
            }
            visible
            selected
            createdAt
            updatedAt
          }
          createdAt
          updatedAt
        }
      }
    }
  }
}
