mutation BundleGroupDelete($input: BundleGroupsSyncInput!) {
  catalogMutation {
    bundleGroupsSync(input: $input) {
      configuration {
        id
      }
      groups {
        id
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
