query BundlePricingTemplate($id: ID!) {
  catalogQuery {
    node(id: $id) {
      ... on BundlePricingTemplate {
        id
        name
        sortIndex
        priceRule {
          id
          priceType
        }
      }
    }
  }
}
