mutation ConditionGroupUpdate($input: ConditionGroupUpdateInput!) {
  catalogMutation {
    conditionGroupUpdate(input: $input) {
      conditionGroup {
        id
        ruleId
        logicOperator
        sortIndex
        conditions {
          id
          groupId
          category
          subject
          operator
          targetType
          targetId
          value
          sortIndex
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
