mutation ConditionGroupDelete($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      dependencyRules {
        id
        conditionGroups {
          id
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
