mutation ConditionGroupCreate($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      dependencyRules {
        id
        conditionGroups {
          id
          logicOperator
          sortIndex
          conditions {
            id
            category
            subject
            operator
            targetType
            targetId
            value
            sortIndex
          }
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
