mutation ConditionDelete($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      dependencyRules {
        id
        conditionGroups {
          id
          conditions {
            id
          }
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
