mutation ConditionUpdate($input: ConditionUpdateInput!) {
  catalogMutation {
    conditionUpdate(input: $input) {
      condition {
        id
        groupId
        category
        subject
        operator
        targetType
        targetId
        value
        sortIndex
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
