mutation DependencyRuleDelete($input: DeleteInput!) {
  catalogMutation {
    dependencyRuleDelete(input: $input) {
      deletedId
      userErrors {
        message
        code
        field
      }
    }
  }
}
