mutation DependencyRuleDelete($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      configuration {
        id
      }
      dependencyRules {
        id
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
