mutation DependencyActionCreate($input: DependencyActionCreateInput!) {
  catalogMutation {
    dependencyActionCreate(input: $input) {
      dependencyAction {
        id
        ruleId
        actionType
        targetType
        targetId
        requiredValue
        priceType
        priceValue
        stackable
        sortIndex
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
