mutation DependencyActionUpdate($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      dependencyRules {
        id
        actions {
          id
          actionType
          targetType
          targetId
          requiredValue
          stackable
          sortIndex
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
