mutation DependencyRuleUpdate($input: DependencyRuleUpdateInput!) {
  catalogMutation {
    dependencyRuleUpdate(input: $input) {
      dependencyRule {
        id
        productId
        name
        enabled
        priority
        logicOperator
        conditionGroups {
          id
          ruleId
          logicOperator
          sortIndex
          conditions {
            id
            groupId
            category
            subject
            operator
            targetType
            targetId
            value
            sortIndex
          }
        }
        actions {
          id
          ruleId
          actionType
          targetType
          targetId
          requiredValue
          priceType
          priceValue
          stackable
          sortIndex
        }
        createdAt
        updatedAt
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
