mutation DependencyRuleUpdate($input: BundleDependencyRulesSyncInput!) {
  catalogMutation {
    bundleDependencyRulesSync(input: $input) {
      dependencyRules {
        id
        name
        enabled
        priority
        logicOperator
        conditionGroups {
          id
          logicOperator
          sortIndex
        }
        actions {
          id
          actionType
          targetType
          targetId
          requiredValue
          stackable
          sortIndex
        }
        createdAt
        updatedAt
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
