query DependencyRules($productId: ID!) {
  catalogQuery {
    bundle(id: $productId) {
      id
      configurations {
        id
        dependencyRules {
          id
          name
          enabled
          priority
          logicOperator
          conditionGroups {
            id
            logicOperator
            sortIndex
            conditions {
              id
              category
              subject
              operator
              targetType
              targetId
              value
              sortIndex
            }
          }
          actions {
            id
            actionType
            targetType
            targetId
            requiredValue
            stackable
            sortIndex
          }
          createdAt
          updatedAt
        }
      }
    }
  }
}
