"use client";

import { useEffect, useState } from "react";
import { Alert, App, Button, Collapse, Descriptions, Flex, Input, Select, Skeleton, Tag, Typography } from "antd";
import { LuTrash2 as DeleteOutlined, LuBan as StopOutlined, LuUser as UserOutlined } from "react-icons/lu";
import { CustomerDataRequestStatus, CustomerDataRequestType } from "@/graphql/types";
import { ModalHeader, ModalLayout, useModalStackContext } from "@/layouts/modals";
import { Paper, PaperHeader } from "@/ui-kit/paper";
import { useEntityPicker } from "@/shared/components/entity-picker-modal";
import type { IPickableEntity } from "@/shared/components/entity-picker-modal/types";
import { useCustomer } from "@/domains/customers/all-customers/hooks";
import "@/domains/customers/all-customers/picker/customer-picker-config";
import { useCustomerDataRequest, useCustomerDataRequestMutations } from "../../hooks";
import type { CustomerDataRequestModalPayload } from "../../modals";

export function CustomerDataRequestModal() {
  const { message, modal } = App.useApp(); const { payload, pop, forcePop, setDirty } = useModalStackContext(); const value = payload as CustomerDataRequestModalPayload; const isEdit = value.mode === "edit"; const scopedCustomer = !isEdit && Boolean(value.customerId); const query = useCustomerDataRequest(isEdit ? value.entityId : undefined); const customerQuery = useCustomer(scopedCustomer ? value.customerId : undefined); const mutations = useCustomerDataRequestMutations();
  const [customerId, setCustomerId] = useState(value.customerId ?? ""); const [customerLabel, setCustomerLabel] = useState(value.customerId ?? ""); const [type, setType] = useState(CustomerDataRequestType.Access); const [legalBasis, setLegalBasis] = useState(""); const [dueAt, setDueAt] = useState(""); const [metadata, setMetadata] = useState("{}"); const [cancelReason, setCancelReason] = useState(""); const [dirty, setLocalDirty] = useState(false); const [error, setError] = useState<string | null>(null); const request = query.request;
  const displayedCustomerLabel = scopedCustomer && customerQuery.customer ? [customerQuery.customer.displayName, customerQuery.customer.email].filter(Boolean).join(" · ") : customerLabel;
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate the editable workflow record when it arrives.
  useEffect(() => { if (!request) return; setCustomerId(request.customer.id); setCustomerLabel(request.customer.displayName); setType(request.type); setLegalBasis(request.legalBasis ?? ""); setDueAt(request.dueAt ? request.dueAt.slice(0, 16) : ""); setMetadata(JSON.stringify(request.requestMetadata, null, 2)); setLocalDirty(false); }, [request]);
  useEffect(() => setDirty(dirty), [dirty, setDirty]);
  const picker = useEntityPicker<IPickableEntity>({ entityType: "customer", selectionMode: "single", initialSelection: customerId ? [customerId] : [], onConfirm: (items, ids) => { setCustomerId(ids[0] ?? ""); setCustomerLabel(items[0]?.title ?? ids[0] ?? ""); setLocalDirty(true); } });
  const parseMetadata = () => { try { const parsed = JSON.parse(metadata); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error(); return parsed; } catch { setError("Request metadata must be a valid JSON object."); return null; } };
  const save = async () => { setError(null); if (!customerId) return setError("Select a customer."); const requestMetadata = parseMetadata(); if (!requestMetadata) return; const input = { customerId, type, legalBasis: legalBasis.trim() || null, dueAt: dueAt ? new Date(dueAt).toISOString() : null, requestMetadata }; const result = request ? await mutations.updateRequest(request.id, input) : await mutations.createRequest(input); if (!result.dataRequest || result.userErrors.length) return setError(result.userErrors.map((item) => item.message).join(" ") || "Unable to save request"); await value.onSaved?.(); setDirty(false); message.success(request ? "Privacy request updated" : "Privacy request created"); forcePop(); };
  const cancel = async () => { if (!request) return; const result = await mutations.updateRequest(request.id, { cancel: { reason: cancelReason.trim() || null } }); if (!result.dataRequest) return setError(result.userErrors.map((item) => item.message).join(" ") || "Unable to cancel request"); await value.onSaved?.(); message.success("Privacy request cancelled"); forcePop(); };
  const remove = async () => { if (!request) return; const confirmed = await modal.confirm({ title: "Delete privacy request?", okText: "Delete", okButtonProps: { danger: true } }); if (!confirmed) return; const result = await mutations.deleteRequest({ id: request.id }); if (!result.deletedDataRequestId) return setError(result.userErrors.map((item) => item.message).join(" ") || "Unable to delete request"); await value.onSaved?.(); forcePop(); };
  if (isEdit && query.loading && !request) return <ModalLayout name="customer-data-request" headerProps={{ title: "Privacy request", onClose: pop, submitButtonProps: null }}><Skeleton active /></ModalLayout>;
  const terminal = request && [CustomerDataRequestStatus.Completed, CustomerDataRequestStatus.Cancelled, CustomerDataRequestStatus.Rejected].includes(request.status);
  return <ModalLayout name="customer-data-request" header={<ModalHeader name="customer-data-request" title={request ? "Privacy request" : "New privacy request"} onClose={pop} extra={request ? <Tag>{request.status.toLowerCase()}</Tag> : null} submitButtonProps={terminal ? null : { children: request ? "Save" : "Create", loading: mutations.loading, disabled: Boolean(request && !dirty), onClick: save }} />}>
    {query.error || customerQuery.error || mutations.error ? <Alert type="error" showIcon message={(query.error ?? customerQuery.error ?? mutations.error)?.message} /> : null}{error ? <Alert type="error" showIcon message={error} /> : null}
    <Alert type="info" showIcon message="Privacy erasure and ordinary customer deletion are different actions." description="A privacy request follows the legal data workflow; deleting a customer only removes it from active customer views." />
    <Paper><PaperHeader title="Request" /><Flex vertical gap="middle"><div><Typography.Text strong>Customer</Typography.Text><Flex gap="small" style={{ marginTop: 8 }}><Input readOnly value={displayedCustomerLabel} suffix={scopedCustomer ? <Typography.Text type="secondary">read-only</Typography.Text> : null} />{!scopedCustomer ? <Button icon={<UserOutlined />} onClick={picker.openPicker} disabled={Boolean(terminal)}>Select</Button> : null}</Flex></div><div><Typography.Text strong>Type</Typography.Text><Select value={type} disabled={Boolean(terminal)} options={Object.values(CustomerDataRequestType).map((item) => ({ value: item, label: item.toLowerCase() }))} onChange={(item) => { setType(item); setLocalDirty(true); }} style={{ width: "100%", marginTop: 8 }} /></div><div><Typography.Text strong>Legal basis</Typography.Text><Input.TextArea value={legalBasis} disabled={Boolean(terminal)} onChange={(event) => { setLegalBasis(event.target.value); setLocalDirty(true); }} rows={3} style={{ marginTop: 8 }} /></div><div><Typography.Text strong>Due at</Typography.Text><Input type="datetime-local" value={dueAt} disabled={Boolean(terminal)} onChange={(event) => { setDueAt(event.target.value); setLocalDirty(true); }} style={{ marginTop: 8 }} /></div></Flex></Paper>
    <Collapse items={[{ key: "advanced", label: "Advanced", children: <div><Typography.Text strong>Request metadata (JSON)</Typography.Text><Input.TextArea value={metadata} disabled={Boolean(terminal)} onChange={(event) => { setMetadata(event.target.value); setLocalDirty(true); }} rows={6} style={{ marginTop: 8, fontFamily: "monospace" }} /></div> }]} />
    {request ? <Paper><PaperHeader title="Processing & result" /><Descriptions column={1} items={[{ key: "requested", label: "Requested", children: new Date(request.requestedAt).toLocaleString() }, { key: "started", label: "Started", children: request.startedAt ? new Date(request.startedAt).toLocaleString() : "—" }, { key: "finished", label: "Finished", children: request.finishedAt ? new Date(request.finishedAt).toLocaleString() : "—" }, { key: "result", label: "Result", children: request.resultFile ? <a href={request.resultFile.url} target="_blank" rel="noreferrer">{request.resultFile.originalName ?? "Open result file"}</a> : "—" }, { key: "rejection", label: "Rejection reason", children: request.rejectionReason ?? "—" }]} /></Paper> : null}
    {request && !terminal ? <Paper><PaperHeader title="Cancel request" icon={<StopOutlined />} /><Input.TextArea value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} placeholder="Optional cancellation reason" rows={3} /><Button danger style={{ marginTop: 12 }} onClick={cancel}>Cancel request</Button></Paper> : null}
    {request ? <Paper><PaperHeader title="Danger zone" /><Button danger icon={<DeleteOutlined />} onClick={remove}>Delete request</Button></Paper> : null}
  </ModalLayout>;
}
