compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableTelemetry: false

httpTimeout: 100000

networkConcurrency: 8

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
