extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.7"
    import: [
      "@key"
      "@requires"
      "@provides"
      "@external"
      "@shareable"
      "@override"
      "@inaccessible"
    ]
  )

# Federated IAM user reference used by OrderActor.
extend type User @key(fields: "id", resolvable: false) {
  """
  Federated User ID.
  """
  id: ID! @external
}

# Federated Customers reference attached to an Order.
extend type Customer @key(fields: "id", resolvable: false) {
  """
  Federated Customer ID.
  """
  id: ID! @external
}
