enum OrderStatus {
  DRAFT
  ACTIVE
  CLOSED
  CANCELLED
}

union OrderActor = User | ApiKey

type OrderCustomerIdentity {
  customer: Customer
  email: Email
  phone: String
  countryCode: CountryCode
  data: JSON
}

type Order {
  id: ID!
  createdBy: OrderActor!
  status: OrderStatus!
  number: BigInt!
  # Currency
  currencyCode: String!
  # Amounts
  subtotal: BigInt!
  shippingTotal: BigInt
  discountTotal: BigInt
  taxTotal: BigInt
  grandTotal: BigInt!
  # customerId: ID
  customerIdentity: OrderCustomerIdentity!
  customerStatistic: OrderCustomerStatistic!
  adminNote: String
  customerNote: String
  # Tags
  tags: [Tag!]!
  labels: [Label!]!
  # Order items
  lines: [OrderLine!]!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
}

type OrderLine {
  id: ID!
  quantity: Int!
  unitPrice: Int!
  unitComparePrice: Int!
  discountAmount: Int!
  subtotalAmount: Int!
  taxAmount: Int
  totalAmount: Int!
  purchasableId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type OrderDeliveryAddress {
  id: ID!
  address1: String!
  address2: String
  city: String!
  countryCode: CountryCode!
  provinceCode: String
  postalCode: String
  email: Email
  firstName: String
  lastName: String
  data: JSON
}

type OrderCustomerStatistic {
  totalRevenue: Int!
  totalGuestOrders: Int!
  totalAuthorizedOrders: Int!
}

input OrdersInput {
  where: JSON
  order: String
  page: Int
  pageSize: Int
}

type OrdersOutput {
  data: [Order!]!
  meta: CollectionMeta!
}

type OrderQuery {
  orders(input: OrdersInput): OrdersOutput!
  order(id: ID!): Order
}

extend type Query {
  orderQuery: OrderQuery!
}
