import { test } from '@fixtures/base.extend';
import type { ApiCategory, ApiCategoryQueryFindOneArgs } from '@codegen/admin-gql';

import * as Yup from 'yup';
import { randomUUID } from 'node:crypto';
import { expect } from '@playwright/test';

test.describe('Categories API', () => {
  let category = {} as ApiCategory;

  const categoryInput = {
    title: 'Category',
    slug: randomUUID(),
    status: 'PUBLISHED',
    excerpt: '',
    includeChildrenProducts: true,
    listingFilters: [],
    listingOrderBy: 'CREATED_AT_ASC',
    listingOrderByStatus: true,
    listingType: 'MANUAL',
    gallery: [],
  };

  const categoryUpdateInput = {
    description: {
      html: '<p style="">Product description</p>',
      json: '{"data":{"type":"doc","content":[{"type":"paragraph","attrs":{"nodeIndent":null,"nodeTextAlignment":null,"nodeLineHeight":null,"style":""},"content":[{"type":"text","text":"Description"}]}]}}',
      text: 'Product description',
    },
    excerpt: 'Product except',
  };

  const newCategoryDescAsnExc = {
    description: {
      html: '<p style="">New Category description</p>',
      json: '{"data":{"type":"doc","content":[{"type":"paragraph","attrs":{"nodeIndent":null,"nodeTextAlignment":null,"nodeLineHeight":null,"style":""},"content":[{"type":"text","text":"Description"}]}]}}',
      text: 'New Category description',
    },
    excerpt: 'New Category excerpt',
  };

  test('Create Category', async ({ api }) => {
    let categoryId: string;

    const updateCategoryListingOrder = (listingOrderBy: string, id: string) =>
      api.admin.mutation('admin/CategoryUpdate', {
        variables: {
          input: {
            listingOrderBy,
            id,
          },
        },
      });

    await test.step('Create a new user with a store', async () => {
      await api.session.setupUserAndProject();
    });
    await test.step('Fill the title and check slug is autogenerated', async () => {
      category = await api.admin.category.create({
        input: { ...categoryInput },
      });

      categoryId = category.id;
    });

    await test.step('Change slug', async () => {
      await api.admin.mutation('admin/CategoryUpdate', {
        variables: {
          input: { id: categoryId, slug: 'edited-slug' },
        },
      });
      expect(await api.admin.category.findOne(categoryId)).toMatchSchema(
        Yup.object({
          slug: Yup.string().equals(['edited-slug']).required(),
        }),
      );
    });

    await test.step('Fills all info', async () => {
      await api.admin.mutation('admin/CategoryUpdate', {
        variables: {
          input: { ...categoryUpdateInput, id: categoryId },
        },
      });
      expect(await api.admin.category.findOne(categoryId)).toMatchSchema(
        Yup.object({
          description: Yup.string().required(),
          excerpt: Yup.string().equals([categoryUpdateInput.excerpt]).required(),
        }),
      );
    });

    //await test.step('Upload image', async () => { });

    await test.step('Select listing order', async () => {
      await updateCategoryListingOrder('CREATED_AT_DESC', categoryId);
      expect(await api.admin.category.findOne(categoryId)).toMatchSchema(
        Yup.object({
          listingOrderBy: Yup.string().equals(['CREATED_AT_DESC']).required(),
        }),
      );
    });

    await test.step('Submit, reload, open and check values', async () => {
      const { data } = await api.admin.query<ApiCategoryQueryFindOneArgs>('admin/CategoryFindOne', {
        variables: {
          id: categoryId,
        },
      });
      expect(data.categoryQuery.findOne).toMatchSchema(
        Yup.object({
          title: Yup.string().equals([categoryInput.title]).required(),
          slug: Yup.string().equals(['edited-slug']).required(),
          status: Yup.string().equals([categoryInput.status]).required(),
          description: Yup.string().required(),
          excerpt: Yup.string().equals([categoryUpdateInput.excerpt]).required(),
          listingOrderBy: Yup.string().equals(['CREATED_AT_DESC']).required(),
          includeChildrenProducts: Yup.boolean()
            .equals([categoryInput.includeChildrenProducts])
            .required(),
          listingOrderByStatus: Yup.boolean()
            .equals([categoryInput.listingOrderByStatus])
            .required(),
          listingType: Yup.string().equals([categoryInput.listingType]).required(),
        }),
      );
    });

    // --- Update categories ---

    await test.step('Change title and check that api handle didn’t change', async () => {
      await api.admin.mutation('admin/CategoryUpdate', {
        variables: {
          input: {
            id: categoryId,
            title: 'Category title updated',
          },
        },
      });

      expect(await api.admin.category.findOne(categoryId)).toMatchSchema(
        Yup.object({
          title: Yup.string().equals(['Category title updated']).required(),
          slug: Yup.string().equals(['edited-slug']).required(),
        }),
      );
    });

    await test.step('Change description and excerpt', async () => {
      await api.admin.mutation('admin/CategoryUpdate', {
        variables: {
          input: { ...newCategoryDescAsnExc, id: categoryId },
        },
      });

      expect(await api.admin.category.findOne(categoryId)).toMatchSchema(
        Yup.object({
          description: Yup.string().required(),
          excerpt: Yup.string().equals([newCategoryDescAsnExc.excerpt]).required(),
        }),
      );
    });

    //await test.step('Remove image and upload another', async () => { });

    await test.step('Check updated values', async () => {
      const { data } = await api.admin.query<ApiCategoryQueryFindOneArgs>('admin/CategoryFindOne', {
        variables: {
          id: categoryId,
        },
      });

      expect(data.categoryQuery.findOne).toMatchSchema(
        Yup.object({
          title: Yup.string().equals(['Category title updated']).required(),
          slug: Yup.string().equals(['edited-slug']).required(),
          description: Yup.string().required(),
          excerpt: Yup.string().equals(['New Category excerpt']).required(),
        }),
      );
    });
  });
});
