CREATE EXTENSION IF NOT EXISTS btree_gin SCHEMA platform;

CREATE EXTENSION IF NOT EXISTS btree_gist SCHEMA platform;

CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA platform;

CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA platform;

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch SCHEMA platform;

CREATE EXTENSION IF NOT EXISTS citext;
