query LoyaltyEarningRuleUsages($where: LoyaltyEarningRuleUsageWhereInput!, $first: Int) {
  loyaltyQuery {
    earningRuleUsages(where: $where, first: $first) { id scopeKey windowStartedAt windowEndedAt occurrenceCount pointsAwarded monetaryAmounts revision earningRule { id code } }
  }
}
