mutation LoyaltyRewardDefinitionDelete($input: LoyaltyRewardDefinitionDeleteInput!) {
  loyaltyMutation { rewardDefinitionDelete(input: $input) { deletedId userErrors { code field message retryable } } }
}
