mutation LoyaltyRewardEntitlementRevoke($input: LoyaltyRewardEntitlementTransitionInput!) {
  loyaltyMutation { rewardEntitlementRevoke(input: $input) { rewardEntitlement { id status revision revokedAt events { eventType previousStatus status reasonCode } } userErrors { code field message retryable } } }
}
