mutation LoyaltyTierRewardBenefitDelete($input: LoyaltyTierRewardBenefitDeleteInput!) {
  loyaltyMutation {
    tierRewardBenefitDelete(input: $input) {
      deletedId
      userErrors { code field message retryable }
    }
  }
}
