export { MediaSection } from "./media-section";
export { CategoriesSection } from "./categories-section";
export { TagsSection } from "./tags-section";
export { ReviewsSection } from "./reviews-section";
export { OptionsSection } from "./options-section";
export { ShippingSection } from "./shipping-section";
export { ComponentsSection } from "./components-section";
export { InventorySection } from "./inventory-section";
export { VariantsTableSection } from "./variants-table-section";
