import { test } from '@fixtures/base.extend';

test.describe('Categories UI test 1', () => {
  test('Create Categories', async ({ api, storesPage, categoriesPage, signInPage }) => {
    await test.step('Create a user and login', async () => {
      await test.step('Create a new user with a store', async () => {
        await api.session.setupUserAndProject();
      });
      await test.step('LogIn', async () => {
        await signInPage.signIn(api.session.user.data.email, api.session.user.data.password);
        await storesPage.waitFor();
        await storesPage.openProject();
      });
    });

    await test.step('Check validation error messages', async () => {
      await categoriesPage.openCategories();

      await categoriesPage.openCreate();
      await categoriesPage.fillCategoriesTitle('');
      await categoriesPage.changeStatus('Published'); //'Published' | 'Draft' | 'Archived'

      await categoriesPage.clickSaveCategories();
      //await categoriesPage.checkValidationMessage();
    });
    await test.step('Fill the title and check slug is autogenerated', async () => {
      await categoriesPage.fillCategoriesTitle(categoriesPage.title);
      await categoriesPage.saveTitleInConstructor();

      await categoriesPage.clickSlugLockButton();
      await categoriesPage.saveSlugInConstructor();
      await categoriesPage.checkSlugAccordingTitle();

      await categoriesPage.clickSlugLockButton();
      await categoriesPage.changeSlug('edited-slug');
      await categoriesPage.saveSlugInConstructor();
    });
    await test.step('Fills all info', async () => {
      await categoriesPage.fillDescription('Description');
      await categoriesPage.clickSaveDescription();

      await categoriesPage.clickExcerpt();
      await categoriesPage.fillExcerpt('Excerpt');
    });
    await test.step('Upload image', async () => {
      await categoriesPage.clickUploadCover();
      await categoriesPage.uploadCover(
        'https://upload.wikimedia.org/wikipedia/commons/b/b8/Chinese_vase.jpg',
      );
    });
    await test.step('Select listing order', async () => {
      await categoriesPage.selectOrder('Oldest', 'Newest'); // 'Newest' | 'Oldest' | 'Product title: A-Z' | 'Product title: Z-A' | 'Lowest price' | 'Highest price' | 'Custom'
      await categoriesPage.changeAvailable();
    });
    await test.step('Submit, reload, open and check values', async () => {
      await categoriesPage.saveAndExitCategory();
      await categoriesPage.reloadPage();

      await categoriesPage.openEditCategory(categoriesPage.title);

      await categoriesPage.checkTitle();
      await categoriesPage.checkSlugAccordingEditedSlug();
      await categoriesPage.checkDescription();
      await categoriesPage.clickExcerpt();
      await categoriesPage.checkExcerpt();

      await categoriesPage.reloadPage();
    });

    // --- Update categories ---

    await test.step('Create Parent and Children categories', async () => {
      await categoriesPage.openCreate();
      await categoriesPage.fillCategoriesTitle('Parent category');
      await categoriesPage.saveAndExitCategory();

      await categoriesPage.openCreate();
      await categoriesPage.fillCategoriesTitle('Children category');
      await categoriesPage.saveAndExitCategory();
    });

    await test.step('Change title and check that api handle didn’t change', async () => {
      await categoriesPage.openEditCategory(categoriesPage.title);
      await categoriesPage.fillCategoriesTitle('Category title updated');
      await categoriesPage.saveTitleInConstructor();
    });
    await test.step('Unlock api handle and change', async () => {
      await categoriesPage.changeSlug('edit-2');
      await categoriesPage.saveSlugInConstructor();
    });
    await test.step('Change description and excerpt', async () => {
      await categoriesPage.fillDescription('Changed Description');

      await categoriesPage.clickExcerpt();
      await categoriesPage.fillExcerpt('Change Excerpt');
    });
    await test.step('Remove image and upload another', async () => {
      await categoriesPage.removeImg();
      await categoriesPage.clickUploadCover();
      await categoriesPage.uploadCover(
        'https://upload.wikimedia.org/wikipedia/commons/8/8f/Portland_Vase_BM_Gem4036_n5.jpg',
      );
      await categoriesPage.clickUploadGallery();
      await categoriesPage.uploadGalleryImg('fixtures/images/vase.jpg');
      await categoriesPage.clickUploadGallery();
      await categoriesPage.uploadGalleryImg('fixtures/images/lamp.jpg');
    });
    await test.step('Change category type, parent and children category', async () => {
      await categoriesPage.clickSelectCategoryType();
      await categoriesPage.fillCategoryType('Category type');
      await categoriesPage.clickSelectParent();
      await categoriesPage.selectParentInModal();
      await categoriesPage.clickOkInModalBrowseCategories();
      await categoriesPage.clickSelectChildren();
      await categoriesPage.selectChildrenInModalAndClickOk();
      await categoriesPage.clickSaveCategories();
    });
    await test.step('Check updated values', async () => {
      await categoriesPage.checkParent('Parent category');
      await categoriesPage.checkChildren('Children category');
      await categoriesPage.checkTitle();
      await categoriesPage.checkSlugAccordingEditedSlug();
      await categoriesPage.clickDescription();
      await categoriesPage.checkDescription();
      await categoriesPage.clickExcerpt();
      await categoriesPage.checkExcerpt();
    });
  });
});
