query FacetValues($facetId: ID!) {
  listingQuery {
    facetValues(facetId: $facetId) {
      id
      kind
      handle
      label
      sourceValues {
        id
        handle
      }
      sortIndex
      enabled
      swatch {
        id
        swatchType
        colorOne
        colorTwo
      }
      facet {
        id
        slug
      }
    }
  }
}
