mutation FacetValueUpdate($input: FacetValueUpdateInput!) {
  listingMutation {
    facetValueUpdate(input: $input) {
      facetValue {
        id
        slug
        label
        sourceHandles
        sortIndex
        enabled
        swatch {
          id
          swatchType
          colorOne
          colorTwo
        }
        facet {
          id
          slug
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
