query FacetValues($facetId: ID!) {
  listingQuery {
    facetValues(facetId: $facetId) {
      id
      slug
      label
      sourceHandles
      sortIndex
      enabled
      swatch {
        id
        swatchType
        colorOne
        colorTwo
      }
      facet {
        id
        slug
      }
    }
  }
}
