query FacetValue($id: ID!) {
  listingQuery {
    facetValue(id: $id) {
      id
      kind
      handle
      label
      sourceValues {
        id
        handle
      }
      sortIndex
      enabled
      swatch {
        id
        swatchType
        colorOne
        colorTwo
      }
      facet {
        id
        slug
      }
    }
  }
}
