mutation FacetDelete($input: FacetDeleteInput!) {
  listingMutation {
    facetDelete(input: $input) {
      deletedFacetId
      userErrors {
        message
        code
        field
      }
    }
  }
}
