mutation FacetGroupCreate($input: FacetGroupCreateInput!) {
  catalogMutation {
    facetGroupCreate(input: $input) {
      facetGroup {
        id
        name
        sortIndex
        createdAt
        updatedAt
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
