query Facet($id: ID!) {
  catalogQuery {
    facet(id: $id) {
      id
      facetType
      slug
      label
      uiType
      selectionMode
      sortIndex
      sourceHandles
      group {
        id
        name
      }
      values {
        id
        slug
        label
      }
    }
  }
}
