query FacetGroup($id: ID!) {
  catalogQuery {
    facetGroup(id: $id) {
      id
      name
      sortIndex
      facets {
        id
        slug
        label
      }
      createdAt
      updatedAt
    }
  }
}
