query Facets {
  catalogQuery {
    facets {
      id
      facetType
      slug
      label
      uiType
      selectionMode
      lexoRank
      sourceHandles
      values {
        id
        slug
        label
      }
    }
  }
}
