mutation FacetCreate($input: FacetCreateInput!) {
  catalogMutation {
    facetCreate(input: $input) {
      facet {
        id
        facetType
        slug
        label
        uiType
        selectionMode
        lexoRank
        values {
          id
          handle
          label
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
