query Facet($id: ID!) {
  listingQuery {
    facet(id: $id) {
      id
      facetType
      slug
      label
      uiType
      selectionMode
      lexoRank
      sources {
        handle
        name
      }
      values {
        id
        handle
        label
      }
    }
  }
}
