mutation FacetValueUnmerge($input: FacetValueUnmergeInput!) {
  listingMutation {
    facetValueUnmerge(input: $input) {
      sourceValues {
        id
        handle
      }
      affectedGroupValues {
        id
        handle
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
