mutation FacetSwatchUpdate($input: FacetSwatchUpdateInput!) {
  listingMutation {
    facetSwatchUpdate(input: $input) {
      facetSwatch {
        id
        swatchType
        colorOne
        colorTwo
        file {
          id
        }
        metadata
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
