query FacetGroups {
  catalogQuery {
    facetGroups {
      id
      name
      sortIndex
      collapsed
      facets {
        id
        slug
        label
      }
      createdAt
      updatedAt
    }
  }
}
