mutation FacetGroupUpdate($input: FacetGroupUpdateInput!) {
  catalogMutation {
    facetGroupUpdate(input: $input) {
      facetGroup {
        id
        name
        sortIndex
        collapsed
        createdAt
        updatedAt
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
