mutation FacetUpdate($input: FacetUpdateInput!) {
  listingMutation {
    facetUpdate(input: $input) {
      facet {
        id
        facetType
        slug
        label
        uiType
        selectionMode
        lexoRank
        sources {
          handle
          name
        }
        values {
          id
          handle
          label
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
