mutation ProjectMemberRemove($input: ProjectMemberRemoveInput!) {
  projectMutation {
    projectMemberRemove(input: $input) {
      removedUserId
      userErrors {
        code
        message
        field
      }
    }
  }
}
