mutation MemberAccessRemove($input: MemberAccessRemoveInput!) {
  organizationMutation {
    memberAccessRemove(input: $input) {
      success
      userErrors {
        code
        message
        field
      }
    }
  }
}
