mutation RoleUpdate($input: RoleUpdateInput!) {
  roleMutation {
    roleUpdate(input: $input) {
      role {
        name
        displayName
        description
        isSystem
        permissions {
          resource
          actions
          effect
        }
        createdAt
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
