import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { oauthProvider } from "@better-auth/oauth-provider";
import {
  listSessions,
  requestPasswordReset,
  requestPasswordResetCallback,
  resetPassword,
  revokeSession,
  sendVerificationEmail,
  signInEmail,
  signInSocial,
  signOut,
  signUpEmail,
  verifyEmail,
} from "better-auth/api";
import { emailOTP, jwt } from "better-auth/plugins";
import { generator } from "better-call";
import YAML from "yaml";
import { createEffectiveApplicationAuthRouteManifest } from "../src/auth/applicationAuthRouteManifest.js";
import {
  APPLICATION_OAUTH_GRANT_TYPES,
  APPLICATION_OAUTH_SCOPES,
} from "../src/auth/applicationOAuthPolicy.js";

type JsonObject = Record<string, unknown>;

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const serviceDirectory = resolve(scriptDirectory, "..");
const overridesPath = resolve(
  serviceDirectory,
  "docs/application-auth.openapi.overrides.yaml",
);
const outputPath = resolve(
  serviceDirectory,
  "docs/application-auth.openapi.yaml",
);
const applicationPathPrefix = "/auth/applications/{applicationId}";

const manifest = createEffectiveApplicationAuthRouteManifest({
  policy: {
    realmEnabled: true,
    passwordSignInAllowed: true,
    passwordSignUpAllowed: true,
    passwordResetAllowed: true,
    emailOtpSignInAllowed: true,
    emailOtpSignUpAllowed: true,
    socialProviders: [
      {
        provider: "google",
        configured: true,
        enabled: true,
        signInAllowed: true,
        signUpAllowed: true,
      },
      {
        provider: "facebook",
        configured: true,
        enabled: true,
        signInAllowed: true,
        signUpAllowed: true,
      },
    ],
  },
  emailVerificationEnabled: true,
  enabledSocialProviders: ["google", "facebook"],
});

const emailOtpPlugin = emailOTP({
  otpLength: 6,
  expiresIn: 5 * 60,
  allowedAttempts: 3,
  disableSignUp: false,
  sendVerificationOTP: async () => undefined,
});
const oauthPlugin = oauthProvider({
  loginPage: "/login",
  consentPage: "/consent",
  signup: { page: "/signup" },
  scopes: [...APPLICATION_OAUTH_SCOPES],
  grantTypes: [...APPLICATION_OAUTH_GRANT_TYPES],
  allowDynamicClientRegistration: false,
  allowUnauthenticatedClientRegistration: false,
  allowPublicClientPrelogin: false,
});

const upstreamEndpoints = {
  signInEmail: signInEmail(),
  signInSocial: signInSocial(),
  signUpEmail: signUpEmail(),
  sendVerificationEmail,
  verifyEmail,
  requestPasswordReset,
  requestPasswordResetCallback,
  resetPassword,
  listSessions: listSessions(),
  revokeSession,
  signOut,
  ...emailOtpPlugin.endpoints,
  ...oauthPlugin.endpoints,
  ...jwt().endpoints,
};

const generated = (await generator(upstreamEndpoints)) as JsonObject;
const overrides = YAML.parse(
  await readFile(overridesPath, "utf8"),
) as JsonObject;
const generatedPaths = generated.paths as JsonObject;
const filteredPaths: JsonObject = {};

for (const [rawPath, rawPathItem] of Object.entries(generatedPaths)) {
  const relativePath = normalizeGeneratedPath(rawPath);
  const pathItem = rawPathItem as JsonObject;
  const filteredPathItem: JsonObject = {};

  for (const [method, operation] of Object.entries(pathItem)) {
    const upperMethod = method.toUpperCase();
    if (upperMethod !== "GET" && upperMethod !== "POST") continue;
    if (!manifestAllows(upperMethod, relativePath)) continue;
    filteredPathItem[method] = withApplicationIdParameter(
      operation as JsonObject,
    );
  }

  if (Object.keys(filteredPathItem).length > 0) {
    filteredPaths[`${applicationPathPrefix}${relativePath}`] = filteredPathItem;
  }
}

generated.paths = filteredPaths;
generated.info = overrides.info;
generated.servers = overrides.servers;
generated.tags = overrides.tags;

const document = deepMerge(generated, overrides) as JsonObject;
document.openapi = "3.0.3";
document.paths = filterFinalPaths(document.paths as JsonObject);
document.components = deepMerge(
  (generated.components as JsonObject | undefined) ?? {},
  (overrides.components as JsonObject | undefined) ?? {},
);
const components = document.components as JsonObject;
const schemas = (components.schemas as JsonObject | undefined) ?? {};
schemas.User = { $ref: "#/components/schemas/ApplicationUser" };
schemas.Session = { $ref: "#/components/schemas/ApplicationSession" };
components.schemas = schemas;

assertContract(document);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `# Generated by: yarn iam:openapi\n# Do not edit this file; edit the route/schema sources or application-auth.openapi.overrides.yaml.\n${YAML.stringify(document, { lineWidth: 100 })}`,
  "utf8",
);

console.log(`Generated ${outputPath}`);

function normalizeGeneratedPath(path: string): string {
  return path.replaceAll(/:([A-Za-z_][A-Za-z0-9_]*)/gu, "{$1}");
}

function manifestAllows(method: string, path: string): boolean {
  return manifest.allowedRoutes.some((route) => {
    if (route.method !== method) return false;
    if (route.pathKind === "exact") return route.path === path;
    if (route.pathKind === "reset-token") {
      return path === "/reset-password/{token}";
    }
    return false;
  });
}

function withApplicationIdParameter(operation: JsonObject): JsonObject {
  const parameters = Array.isArray(operation.parameters)
    ? operation.parameters
    : [];
  return {
    ...operation,
    parameters: [
      { $ref: "#/components/parameters/ApplicationId" },
      ...parameters,
    ],
  };
}

function filterFinalPaths(paths: JsonObject): JsonObject {
  const result: JsonObject = {};
  const rootMetadataPath =
    "/.well-known/oauth-authorization-server/auth/applications/{applicationId}";

  for (const [path, pathItem] of Object.entries(paths)) {
    if (path === rootMetadataPath) {
      result[path] = pathItem;
      continue;
    }
    if (!path.startsWith(applicationPathPrefix)) continue;

    const relativePath = path.slice(applicationPathPrefix.length);
    const item = pathItem as JsonObject;
    const filteredItem: JsonObject = {};
    for (const [method, operation] of Object.entries(item)) {
      const upperMethod = method.toUpperCase();
      if (
        (upperMethod === "GET" || upperMethod === "POST") &&
        manifestAllows(upperMethod, relativePath)
      ) {
        filteredItem[method] = operation;
      }
    }
    if (Object.keys(filteredItem).length > 0) result[path] = filteredItem;
  }
  return result;
}

function deepMerge(base: unknown, overlay: unknown): unknown {
  if (!isObject(base) || !isObject(overlay)) return structuredClone(overlay);
  const result: JsonObject = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    result[key] =
      key in result
        ? deepMerge(result[key], value)
        : structuredClone(value);
  }
  return result;
}

function isObject(value: unknown): value is JsonObject {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function assertContract(document: JsonObject): void {
  const paths = document.paths;
  if (!isObject(paths) || Object.keys(paths).length === 0) {
    throw new Error("Generated application auth OpenAPI has no paths");
  }

  const operationIds = new Set<string>();
  for (const [path, pathItem] of Object.entries(paths)) {
    if (!isObject(pathItem)) continue;
    for (const [method, operation] of Object.entries(pathItem)) {
      if (method !== "get" && method !== "post") continue;
      if (!isObject(operation) || typeof operation.operationId !== "string") {
        throw new Error(`Missing operationId for ${method.toUpperCase()} ${path}`);
      }
      if (operationIds.has(operation.operationId)) {
        throw new Error(`Duplicate operationId ${operation.operationId}`);
      }
      operationIds.add(operation.operationId);
    }
  }

  assertLocalReferences(document, document);
}

function assertLocalReferences(value: unknown, document: JsonObject): void {
  if (Array.isArray(value)) {
    for (const item of value) assertLocalReferences(item, document);
    return;
  }
  if (!isObject(value)) return;

  if (typeof value.$ref === "string" && value.$ref.startsWith("#/")) {
    let target: unknown = document;
    for (const rawPart of value.$ref.slice(2).split("/")) {
      const part = rawPart.replaceAll("~1", "/").replaceAll("~0", "~");
      target = isObject(target) ? target[part] : undefined;
    }
    if (target === undefined) {
      throw new Error(`Unresolved OpenAPI reference ${value.$ref}`);
    }
  }

  for (const child of Object.values(value)) {
    assertLocalReferences(child, document);
  }
}
