import { test } from '@fixtures/base.extend';

test.describe('Pages UI', () => {
  test('Create pages', async ({ api, storesPage, signInPage, pagesPage }) => {
    await test.step('Create a user and login', async () => {
      await test.step('Create a new user with a store', async () => {
        await api.session.setupUserAndProject();
      });
      await test.step('LogIn', async () => {
        await signInPage.signIn(api.session.user.data.email, api.session.user.data.password);
        await storesPage.waitFor();
        await storesPage.openProject();
      })
    });

    await test.step('Check validation error messages', async () => {
      await pagesPage.openPages();

      await pagesPage.openCreate();
      await pagesPage.fillPagesTitle('');
      await pagesPage.changeStatus('Published'); //'Published' | 'Draft' | 'Archived'

      await pagesPage.clickSavePages();
    });
    await test.step('Fill the title and check slug is autogenerated', async () => {
      await pagesPage.fillPagesTitle(pagesPage.title);
      await pagesPage.saveTitleInConstructor();

      await pagesPage.clickSlugLockButton();
      await pagesPage.saveSlugInConstructor();
      await pagesPage.checkSlugAccordingTitle();

      await pagesPage.clickSlugLockButton();
      await pagesPage.changeSlug('edited-slug');
      await pagesPage.saveSlugInConstructor();
    });
    await test.step('Fills all info', async () => {
      await pagesPage.fillDescription('Description of pages');
      await pagesPage.clickSaveDescription();

      await pagesPage.clickExcerpt();
      await pagesPage.fillExcerpt('Excerpt of pages');
    });
    await test.step('Upload image', async () => {
      await pagesPage.clickUploadCover();
      await pagesPage.uploadCover(
        'https://upload.wikimedia.org/wikipedia/commons/b/b8/Chinese_vase.jpg',
      );
    });
    await test.step('Submit, reload, open and check values', async () => {
      await pagesPage.saveAndExitPages();
      await pagesPage.reloadPage();

      await pagesPage.openEditPage(pagesPage.title);

      await pagesPage.checkTitle();
      await pagesPage.checkSlugAccordingEditedSlug();
      await pagesPage.checkDescription();
      await pagesPage.clickExcerpt();
      await pagesPage.checkExcerpt();

      await pagesPage.reloadPage();
    });

    // --- Update categories ---

    await test.step('Change title and check that api handle didn’t change', async () => {
      await pagesPage.openEditPage(pagesPage.title);
      await pagesPage.fillPagesTitle('Pages title updated');
      await pagesPage.saveTitleInConstructor();
    });
    await test.step('Unlock api handle and change', async () => {
      await pagesPage.changeSlug('edit-2');
      await pagesPage.saveSlugInConstructor();
    });
    await test.step('Change description and excerpt', async () => {
      await pagesPage.fillDescription('Changed Description');

      await pagesPage.clickExcerpt();
      await pagesPage.fillExcerpt('Change Excerpt');
    });
    await test.step('Remove image and upload another', async () => {
      await pagesPage.removeImg();
      await pagesPage.clickUploadCover();
      await pagesPage.uploadCover(
        'https://upload.wikimedia.org/wikipedia/commons/8/8f/Portland_Vase_BM_Gem4036_n5.jpg',
      );
      await pagesPage.clickUploadGallery();
      await pagesPage.uploadGalleryImg('fixtures/images/vase.jpg');
      await pagesPage.clickUploadGallery();
      await pagesPage.uploadGalleryImg('fixtures/images/lamp.jpg');
    });
    await test.step('Check updated values', async () => {
      await pagesPage.checkTitle();
      await pagesPage.checkSlugAccordingEditedSlug();
      await pagesPage.clickDescription();
      await pagesPage.checkDescription();
      await pagesPage.clickExcerpt();
      await pagesPage.checkExcerpt();
    });
  });
});
