export type GraphQLFileName =
  // users-api
  | 'users-api/SignUp'
  | 'users-api/SignIn'
  | 'users-api/UserCurrent'
  // project-api
  | 'project-api/ProjectCreate'
  | 'project-api/ProjectUpdate'
  | 'project-api/ProjectDelete'
  | 'project-api/Project'
  | 'project-api/Projects'
  | 'project-api/ProjectRoles'
  | 'project-api/ProjectMembers'
  | 'project-api/ProjectAvailableResources'
  // iam-api
  | 'iam-api/OrganizationCreate'
  | 'iam-api/OrganizationRoles'
  | 'iam-api/OrganizationMembership'
  | 'iam-api/MemberInvite'
  | 'iam-api/MemberRemove'
  // roles-api
  | 'roles-api/RoleCreate'
  | 'roles-api/RoleUpdate'
  | 'roles-api/RoleDelete'
  | 'roles-api/ProjectMemberRoleChange'
  | 'roles-api/ProjectMemberRemove'
  | 'roles-api/Authorize';
