import type { ApplicationAuthUiLocale } from "../../../../auth/applicationAuthConfiguration.js";

export type ApplicationAuthUiMessageKey = keyof typeof messages.en;

const messages = {
  en: {
    signInTitle: "Sign in",
    signInHint: "Continue securely to the application.",
    signUpTitle: "Create account",
    signUpHint: "Create an account for this application.",
    email: "Email",
    password: "Password",
    name: "Name",
    newPassword: "New password",
    signIn: "Sign in",
    signUp: "Create account",
    continueWithGoogle: "Continue with Google",
    continueWithFacebook: "Continue with Facebook",
    connectionsTitle: "Connected sign-in methods",
    connectionsHint: "Manage social accounts for this application.",
    googleProvider: "Google",
    facebookProvider: "Facebook",
    providerConnected: "Connected",
    providerNotConnected: "Not connected",
    connectProvider: "Connect",
    disconnectProvider: "Disconnect",
    freshSessionRequired: "Sign in again to change connected accounts.",
    providerConflict: "This connection needs support review.",
    connectionFailed: "The social account could not be connected.",
    connectionsUpdated: "Connected sign-in methods were updated.",
    noSocialProviders: "No social sign-in providers are available.",
    emailOtpTitle: "Sign in with an email code",
    emailOtpRequestHint: "We will send a six-digit code if this email can sign in.",
    sendEmailOtp: "Send code",
    emailOtpAccepted: "If this email can sign in, check your inbox for a code.",
    emailOtpVerifyTitle: "Enter email code",
    emailOtpVerifyHint:
      "Enter the email address and six-digit code. The code expires in five minutes.",
    emailOtpCode: "Six-digit code",
    verifyEmailOtp: "Verify and sign in",
    resendEmailOtp: "Send another code",
    phone: "Phone number",
    phoneOtpTitle: "Sign in with a phone code",
    phoneOtpRequestHint: "Enter a phone number in international format.",
    phoneOtpAccepted: "Check your phone for a six-digit code.",
    phoneOtpVerifyTitle: "Enter phone code",
    phoneOtpVerifyHint:
      "Enter the phone number and six-digit code. The code expires in five minutes.",
    sendPhoneOtp: "Send code",
    verifyPhoneOtp: "Verify and sign in",
    resendPhoneOtp: "Send another code",
    forgotPassword: "Forgot password?",
    resetPasswordTitle: "Reset password",
    resetPasswordRequestHint: "If an account exists, a reset link will be sent.",
    sendResetLink: "Send reset link",
    resetRequestAccepted: "If the account exists, check your email for a reset link.",
    resetPassword: "Reset password",
    resetComplete: "Your password has been reset.",
    verificationPendingTitle: "Verify your email",
    verificationPendingHint: "Check your inbox and follow the verification link before signing in.",
    resendVerification: "Resend verification",
    verificationResent: "If verification is required, check your email for a new link.",
    verifiedTitle: "Email verified",
    verifiedHint: "Your email is verified. You can now sign in.",
    accountCreatedTitle: "Account created",
    accountCreatedHint:
      "Your account was created. Sign-in remains controlled by this application's policy.",
    consentTitle: "Approve access",
    consentHint: "This application is requesting access to:",
    allow: "Allow",
    deny: "Deny",
    logoutTitle: "Sign out?",
    logoutHint: "Confirm that you want to end this application session.",
    logout: "Sign out",
    cancel: "Cancel",
    backToSignIn: "Back to sign in",
    genericAuthError: "The request could not be completed. Check your details and try again.",
    unavailableTitle: "Authentication unavailable",
    unavailableHint: "This authentication request is unavailable or has expired.",
    securityFooter: "Secure authentication provided by Shopana IAM.",
  },
} as const;

export function createApplicationAuthTranslator(locale: ApplicationAuthUiLocale) {
  return (key: ApplicationAuthUiMessageKey): string => messages[locale]?.[key] ?? messages.en[key];
}
