import type { ApplicationAuthUiLocale } from "../../../../auth/applicationAuthConfiguration.js";

export type ApplicationAuthUiMessageKey = keyof typeof messages.en;

const messages = {
  en: {
    signInTitle: "Sign in",
    signInHint: "Continue securely to the application.",
    signUpTitle: "Create account",
    signUpHint: "Create an account for this application.",
    email: "Email",
    password: "Password",
    name: "Name",
    newPassword: "New password",
    signIn: "Sign in",
    signUp: "Create account",
    continueWithGoogle: "Continue with Google",
    continueWithFacebook: "Continue with Facebook",
    connectionsTitle: "Connected sign-in methods",
    connectionsHint: "Manage social accounts for this application.",
    googleProvider: "Google",
    facebookProvider: "Facebook",
    providerConnected: "Connected",
    providerNotConnected: "Not connected",
    connectProvider: "Connect",
    disconnectProvider: "Disconnect",
    freshSessionRequired: "Sign in again to change connected accounts.",
    providerConflict: "This connection needs support review.",
    connectionFailed: "The social account could not be connected.",
    connectionsUpdated: "Connected sign-in methods were updated.",
    noSocialProviders: "No social sign-in providers are available.",
    emailOtpTitle: "Sign in with an email code",
    emailOtpRequestHint: "We will send a six-digit code if this email can sign in.",
    sendEmailOtp: "Send code",
    emailOtpAccepted: "If this email can sign in, check your inbox for a code.",
    emailOtpVerifyTitle: "Enter email code",
    emailOtpVerifyHint: "Enter the email address and six-digit code. The code expires in five minutes.",
    emailOtpCode: "Six-digit code",
    verifyEmailOtp: "Verify and sign in",
    resendEmailOtp: "Send another code",
    forgotPassword: "Forgot password?",
    resetPasswordTitle: "Reset password",
    resetPasswordRequestHint: "If an account exists, a reset link will be sent.",
    sendResetLink: "Send reset link",
    resetRequestAccepted: "If the account exists, check your email for a reset link.",
    resetPassword: "Reset password",
    resetComplete: "Your password has been reset.",
    verificationPendingTitle: "Verify your email",
    verificationPendingHint: "Check your inbox and follow the verification link before signing in.",
    resendVerification: "Resend verification",
    verificationResent: "If verification is required, check your email for a new link.",
    verifiedTitle: "Email verified",
    verifiedHint: "Your email is verified. You can now sign in.",
    accountCreatedTitle: "Account created",
    accountCreatedHint: "Your account was created. Sign-in remains controlled by this application's policy.",
    consentTitle: "Approve access",
    consentHint: "This application is requesting access to:",
    allow: "Allow",
    deny: "Deny",
    logoutTitle: "Sign out?",
    logoutHint: "Confirm that you want to end this application session.",
    logout: "Sign out",
    cancel: "Cancel",
    backToSignIn: "Back to sign in",
    genericAuthError: "The request could not be completed. Check your details and try again.",
    unavailableTitle: "Authentication unavailable",
    unavailableHint: "This authentication request is unavailable or has expired.",
    securityFooter: "Secure authentication provided by Shopana IAM.",
  },
  uk: {
    signInTitle: "Увійти",
    signInHint: "Безпечно продовжити до застосунку.",
    signUpTitle: "Створити обліковий запис",
    signUpHint: "Створіть обліковий запис для цього застосунку.",
    email: "Електронна пошта",
    password: "Пароль",
    name: "Ім’я",
    newPassword: "Новий пароль",
    signIn: "Увійти",
    signUp: "Створити обліковий запис",
    continueWithGoogle: "Продовжити з Google",
    continueWithFacebook: "Продовжити з Facebook",
    connectionsTitle: "Підключені способи входу",
    connectionsHint: "Керуйте соціальними обліковими записами цього застосунку.",
    googleProvider: "Google",
    facebookProvider: "Facebook",
    providerConnected: "Підключено",
    providerNotConnected: "Не підключено",
    connectProvider: "Підключити",
    disconnectProvider: "Відключити",
    freshSessionRequired: "Увійдіть знову, щоб змінити підключені облікові записи.",
    providerConflict: "Це підключення потребує перевірки підтримкою.",
    connectionFailed: "Не вдалося підключити соціальний обліковий запис.",
    connectionsUpdated: "Підключені способи входу оновлено.",
    noSocialProviders: "Соціальні провайдери входу недоступні.",
    emailOtpTitle: "Увійти за кодом з електронної пошти",
    emailOtpRequestHint: "Ми надішлемо шестизначний код, якщо ця адреса може увійти.",
    sendEmailOtp: "Надіслати код",
    emailOtpAccepted: "Якщо ця адреса може увійти, перевірте пошту — там буде код.",
    emailOtpVerifyTitle: "Введіть код із пошти",
    emailOtpVerifyHint: "Введіть адресу електронної пошти та шестизначний код. Код діє п’ять хвилин.",
    emailOtpCode: "Шестизначний код",
    verifyEmailOtp: "Перевірити та увійти",
    resendEmailOtp: "Надіслати інший код",
    forgotPassword: "Забули пароль?",
    resetPasswordTitle: "Відновлення пароля",
    resetPasswordRequestHint: "Якщо обліковий запис існує, ми надішлемо посилання для відновлення.",
    sendResetLink: "Надіслати посилання",
    resetRequestAccepted: "Якщо обліковий запис існує, перевірте електронну пошту.",
    resetPassword: "Змінити пароль",
    resetComplete: "Пароль змінено.",
    verificationPendingTitle: "Підтвердьте електронну пошту",
    verificationPendingHint: "Перевірте пошту та перейдіть за посиланням підтвердження перед входом.",
    resendVerification: "Надіслати підтвердження ще раз",
    verificationResent: "Якщо підтвердження потрібне, перевірте пошту — ми надіслали нове посилання.",
    verifiedTitle: "Пошту підтверджено",
    verifiedHint: "Електронну пошту підтверджено. Тепер можна увійти.",
    accountCreatedTitle: "Обліковий запис створено",
    accountCreatedHint: "Обліковий запис створено. Вхід залишається керованим політикою цього застосунку.",
    consentTitle: "Підтвердити доступ",
    consentHint: "Цей застосунок запитує доступ до:",
    allow: "Дозволити",
    deny: "Відхилити",
    logoutTitle: "Вийти?",
    logoutHint: "Підтвердьте завершення сеансу цього застосунку.",
    logout: "Вийти",
    cancel: "Скасувати",
    backToSignIn: "Повернутися до входу",
    genericAuthError: "Не вдалося виконати запит. Перевірте дані та спробуйте ще раз.",
    unavailableTitle: "Автентифікація недоступна",
    unavailableHint: "Цей запит автентифікації недоступний або прострочений.",
    securityFooter: "Безпечна автентифікація Shopana IAM.",
  },
  ru: {
    signInTitle: "Войти",
    signInHint: "Безопасно продолжить в приложение.",
    signUpTitle: "Создать аккаунт",
    signUpHint: "Создайте аккаунт для этого приложения.",
    email: "Электронная почта",
    password: "Пароль",
    name: "Имя",
    newPassword: "Новый пароль",
    signIn: "Войти",
    signUp: "Создать аккаунт",
    continueWithGoogle: "Продолжить с Google",
    continueWithFacebook: "Продолжить с Facebook",
    connectionsTitle: "Подключённые способы входа",
    connectionsHint: "Управляйте социальными аккаунтами этого приложения.",
    googleProvider: "Google",
    facebookProvider: "Facebook",
    providerConnected: "Подключён",
    providerNotConnected: "Не подключён",
    connectProvider: "Подключить",
    disconnectProvider: "Отключить",
    freshSessionRequired: "Войдите снова, чтобы изменить подключённые аккаунты.",
    providerConflict: "Это подключение требует проверки службой поддержки.",
    connectionFailed: "Не удалось подключить социальный аккаунт.",
    connectionsUpdated: "Подключённые способы входа обновлены.",
    noSocialProviders: "Социальные провайдеры входа недоступны.",
    emailOtpTitle: "Войти по коду из электронной почты",
    emailOtpRequestHint: "Мы отправим шестизначный код, если этот адрес может войти.",
    sendEmailOtp: "Отправить код",
    emailOtpAccepted: "Если этот адрес может войти, проверьте почту — там будет код.",
    emailOtpVerifyTitle: "Введите код из письма",
    emailOtpVerifyHint: "Введите адрес электронной почты и шестизначный код. Код действует пять минут.",
    emailOtpCode: "Шестизначный код",
    verifyEmailOtp: "Проверить и войти",
    resendEmailOtp: "Отправить другой код",
    forgotPassword: "Забыли пароль?",
    resetPasswordTitle: "Восстановление пароля",
    resetPasswordRequestHint: "Если аккаунт существует, мы отправим ссылку для восстановления.",
    sendResetLink: "Отправить ссылку",
    resetRequestAccepted: "Если аккаунт существует, проверьте электронную почту.",
    resetPassword: "Изменить пароль",
    resetComplete: "Пароль изменён.",
    verificationPendingTitle: "Подтвердите электронную почту",
    verificationPendingHint: "Проверьте почту и перейдите по ссылке подтверждения перед входом.",
    resendVerification: "Отправить подтверждение повторно",
    verificationResent: "Если подтверждение требуется, проверьте почту — мы отправили новую ссылку.",
    verifiedTitle: "Почта подтверждена",
    verifiedHint: "Электронная почта подтверждена. Теперь можно войти.",
    accountCreatedTitle: "Аккаунт создан",
    accountCreatedHint: "Аккаунт создан. Возможность входа определяется политикой этого приложения.",
    consentTitle: "Подтвердить доступ",
    consentHint: "Это приложение запрашивает доступ к:",
    allow: "Разрешить",
    deny: "Отклонить",
    logoutTitle: "Выйти?",
    logoutHint: "Подтвердите завершение сессии этого приложения.",
    logout: "Выйти",
    cancel: "Отмена",
    backToSignIn: "Вернуться ко входу",
    genericAuthError: "Не удалось выполнить запрос. Проверьте данные и попробуйте ещё раз.",
    unavailableTitle: "Аутентификация недоступна",
    unavailableHint: "Этот запрос аутентификации недоступен или истёк.",
    securityFooter: "Безопасная аутентификация Shopana IAM.",
  },
} as const;

export function createApplicationAuthTranslator(locale: ApplicationAuthUiLocale) {
  return (key: ApplicationAuthUiMessageKey): string =>
    messages[locale]?.[key] ?? messages.en[key];
}
