import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Project Settings Admin API - store lifecycle', [
  ['PRJ-LIFE-001', 'storeCreate requires org.stores write permission in the selected organization'],
  ['PRJ-LIFE-002', 'valid create returns one store with empty userErrors and generated Store global ID'],
  ['PRJ-LIFE-003', 'create persists organization, slug, display name, status, timezone, email, and currency'],
  ['PRJ-LIFE-004', 'create persists every initial locale as active and selects the first as default'],
  ['PRJ-LIFE-005', 'omitted status, timezone, and measurement settings use server-owned defaults'],
  ['PRJ-LIFE-006', 'store slug accepts only lowercase URL-safe values within length limits'],
  ['PRJ-LIFE-007', 'blank or oversized display name returns a field validation error without state'],
  ['PRJ-LIFE-008', 'empty locale list is rejected without starting the creation saga'],
  ['PRJ-LIFE-009', 'duplicate initial locales are rejected without partial locale rows'],
  ['PRJ-LIFE-010', 'invalid currency, locale, timezone, or email is rejected safely'],
  ['PRJ-LIFE-011', 'duplicate active store slug returns DUPLICATE_VALUE without another store'],
  ['PRJ-LIFE-012', 'store create saga provisions the complete store role catalog in IAM'],
  ['PRJ-LIFE-013', 'store create saga assigns the creator the store admin role'],
  ['PRJ-LIFE-014', 'store create saga creates one Media asset group owned by the new store'],
  ['PRJ-LIFE-015', 'successful create emits one storeCreated event with safe canonical payload'],
  ['PRJ-LIFE-016', 'role provisioning failure compensates the Project store and locale state'],
  ['PRJ-LIFE-017', 'role assignment or Media failure cannot return a partially usable store'],
  ['PRJ-LIFE-018', 'retry after ambiguous create completion does not create duplicate stores or side effects'],
  ['PRJ-LIFE-019', 'storeDelete requires org.stores admin permission'],
  ['PRJ-LIFE-020', 'storeDelete cross-checks Store ID and Organization ID ownership'],
  ['PRJ-LIFE-021', 'successful delete soft-deletes the store and excludes it from all Admin reads'],
  ['PRJ-LIFE-022', 'delete requests removal of the store Media asset group and entity back-references'],
  ['PRJ-LIFE-023', 'successful delete emits one storeDeleted event with correct actor and organization'],
  ['PRJ-LIFE-024', 'unknown, foreign, malformed, or type-confused Store ID changes no store'],
  ['PRJ-LIFE-025', 'repeated delete is safe and cannot delete a different store'],
  ['PRJ-LIFE-026', 'Media cleanup failure follows the documented best-effort delete contract without leaking internals'],
  ['PRJ-LIFE-027', 'store lifecycle events and saga inputs never include Admin session credentials'],
] as const);
