import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Project Settings Admin API - unified store update', [
  ['PRJ-UPD-001', 'storeUpdate requires a valid Store global ID'],
  ['PRJ-UPD-002', 'storeUpdate requires clientMutationId between one and 128 trimmed characters'],
  ['PRJ-UPD-003', 'storeUpdate requires a non-negative safe integer expectedRevision'],
  ['PRJ-UPD-004', 'storeUpdate requires store.profile write permission in the target store domain'],
  ['PRJ-UPD-005', 'storeUpdate derives organization ownership from the persisted target store'],
  ['PRJ-UPD-006', 'valid single-section update increments store revision exactly once'],
  ['PRJ-UPD-007', 'valid multi-section update increments store revision once rather than per section'],
  ['PRJ-UPD-008', 'operationResults contains every requested section in deterministic schema input order'],
  ['PRJ-UPD-009', 'successful section result has applied true and an empty errors list'],
  ['PRJ-UPD-010', 'failed section result has applied false and section-prefixed field errors'],
  ['PRJ-UPD-011', 'payload userErrors aggregates section errors without losing operation-level errors'],
  ['PRJ-UPD-012', 'batch mapping validation failure prevents every section from being applied'],
  ['PRJ-UPD-013', 'unrequested sections remain byte-for-byte unchanged'],
  ['PRJ-UPD-014', 'stale expectedRevision returns REVISION_CONFLICT without applying operations'],
  ['PRJ-UPD-015', 'parallel updates with one revision produce exactly one revision owner'],
  ['PRJ-UPD-016', 'foreign or deleted store returns NOT_FOUND without existence or ownership disclosure'],
  ['PRJ-UPD-017', 'authorization failure marks every requested operation unapplied'],
  ['PRJ-UPD-018', 'empty operations follows the approved no-op contract without ambiguous partial state'],
  ['PRJ-UPD-019', 'same clientMutationId and identical content reuses one durable saga result'],
  ['PRJ-UPD-020', 'same clientMutationId cannot be reused with different revision or operation content'],
  ['PRJ-UPD-021', 'retry after response loss does not apply a section twice or consume another revision'],
  ['PRJ-UPD-022', 'infrastructure failure restores the captured settings snapshot and reserved revision'],
  ['PRJ-UPD-023', 'compensation never overwrites a newer revision acquired by another update'],
  ['PRJ-UPD-024', 'storeUpdate returns the freshly committed Store projection after success'],
  ['PRJ-UPD-025', 'all negative update cases verify no changes in target and foreign stores'],
] as const);
