export {
  PRODUCT_CREATE_MUTATION,
  PRODUCT_DELETE_MUTATION,
  PRODUCT_OPTION_CREATE_MUTATION,
  PRODUCT_PUBLISH_MUTATION,
  PRODUCT_UPDATE_MUTATION,
  PRODUCT_UPDATE_STATUS_MUTATION,
  VARIANT_SET_MEDIA_MUTATION,
} from "../products/graphql/mutations";
