query CheckoutByIdFull($id: ID!) {
  checkoutQuery {
    checkout(id: $id) {
      id
      createdAt
      updatedAt
      totalQuantity
      cost {
        totalShippingAmount {
          amount
          currencyCode
        }
        subtotalAmount {
          amount
          currencyCode
        }
        totalAmount {
          amount
          currencyCode
        }
        totalDiscountAmount {
          amount
          currencyCode
        }
        totalTaxAmount {
          amount
          currencyCode
        }
      }
      notifications {
        id
        code
        severity
        isDismissed
      }
      customerIdentity {
        email
        phone
        countryCode
        firstName
        lastName
        middleName
        customer { id }
      }
      customerNote
      lines {
        id
        quantity
        purchasableId
        sku
        title
        imageSrc
        tag {
          id
          slug
          unique
        }
        children {
          id
        }
        cost {
          compareAtUnitPrice {
            amount
            currencyCode
          }
          discountAmount {
            amount
            currencyCode
          }
          subtotalAmount {
            amount
            currencyCode
          }
          taxAmount {
            amount
            currencyCode
          }
          totalAmount {
            amount
            currencyCode
          }
          unitPrice {
            amount
            currencyCode
          }
        }
        purchasableSnapshot
      }
      tags {
        id
        slug
        unique
        createdAt
        updatedAt
      }
      deliveryGroups {
        id
        checkoutLines { id }
        deliveryAddress {
          id
          address1
          address2
          city
          countryCode
          provinceCode
          postalCode
          data
        }
        recipient {
          firstName
          lastName
          middleName
          email
          phone
        }
        deliveryMethods {
          code
          deliveryMethodType
          provider { code }
          data
        }
        selectedDeliveryMethod {
          code
          deliveryMethodType
          provider { code }
          data
        }
        estimatedCost {
          amount { amount currencyCode }
          paymentModel
        }
      }
      appliedPromoCodes {
        code
        appliedAt
      }
      payment {
        paymentMethods {
          code
          provider { code }
          flow
          data
        }
        selectedPaymentMethod {
          code
          provider { code }
          flow
          data
        }
        payableAmount {
          amount
          currencyCode
        }
      }
    }
  }
}
