mutation CheckoutTagUpdate($input: CheckoutTagUpdateInput!) {
  checkoutMutation {
    checkoutTagUpdate(input: $input) {
      id
      tags {
        id
        slug
        unique
        createdAt
        updatedAt
      }
      lines {
        id
        quantity
        purchasableId
        tag {
          id
          slug
          unique
        }
      }
    }
  }
}
