mutation CollectionUpdateRules($input: CollectionUpdateRulesInput!) {
  catalogMutation {
    collectionUpdateRules(input: $input) {
      collection {
        id
        handle
        type
        name
        rules {
          __typename
          id
          field
          sortIndex
          referenceStatus
          ... on CollectionCategoryRule { operator categoryIds }
          ... on CollectionTagRule { operator tagIds }
          ... on CollectionVendorRule { vendorIds }
          ... on CollectionFeatureRule { operator values { sourceHandle valueHandle } }
          ... on CollectionOptionRule { operator values { sourceHandle valueHandle } }
          ... on CollectionPriceComparisonRule { operator currencyCode amountMinor }
          ... on CollectionPriceRangeRule { currencyCode minAmountMinor maxAmountMinor }
          ... on CollectionInStockRule { value }
          ... on CollectionCreatedAtComparisonRule { operator instant }
          ... on CollectionCreatedAtRangeRule { from to }
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
