mutation CollectionRulesPreviewCount($input: CollectionRulesPreviewCountInput!) {
  catalogMutation {
    collectionRulesPreviewCount(input: $input) {
      count
      rulesHash
      indexObservedAt
      userErrors {
        message
        code
        field
      }
    }
  }
}
