mutation CollectionDelete($input: CollectionDeleteInput!) {
  catalogMutation {
    collectionDelete(input: $input) {
      deletedCollectionId
      userErrors {
        message
        code
        field
      }
    }
  }
}
