mutation CollectionUpdate($input: CollectionUpdateInput!) {
  catalogMutation {
    collectionUpdate(input: $input) {
      collection {
        id
        handle
        type
        name
        description {
          html
          text
          json
        }
        excerpt {
          html
          text
          json
        }
        defaultSort
        defaultSortDirection
        activeFrom
        activeTo
        isActive
        publishedAt
        isPublished
        createdAt
        updatedAt
        rules {
          __typename
          id
          field
          sortIndex
          referenceStatus
          ... on CollectionCategoryRule { operator categoryIds }
          ... on CollectionTagRule { operator tagIds }
          ... on CollectionVendorRule { vendorIds }
          ... on CollectionFeatureRule { operator values { sourceHandle valueHandle } }
          ... on CollectionOptionRule { operator values { sourceHandle valueHandle } }
          ... on CollectionPriceComparisonRule { operator currencyCode amountMinor }
          ... on CollectionPriceRangeRule { currencyCode minAmountMinor maxAmountMinor }
          ... on CollectionInStockRule { value }
          ... on CollectionCreatedAtComparisonRule { operator instant }
          ... on CollectionCreatedAtRangeRule { from to }
        }
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
