query CollectionFindOne($id: ID!) {
  catalogQuery {
    collection(id: $id) {
      id
      handle
      type
      name
      description {
        html
        text
        json
      }
      defaultSort
      defaultSortDirection
      activeFrom
      activeTo
      isActive
      publishedAt
      isPublished
      createdAt
      updatedAt
      rules {
        id
        field
        operator
        value
        sortIndex
      }
    }
  }
}
