query VariantFindMany(
  $first: Int
  $after: String
  $last: Int
  $before: String
  $where: VariantWhereInput
  $orderBy: [VariantOrderByInput!]
) {
  catalogQuery {
    variants(
      first: $first
      after: $after
      last: $last
      before: $before
      where: $where
      orderBy: $orderBy
    ) {
      edges {
        node {
          id
          handle
          isDefault
          externalSystem
          externalId
          createdAt
          updatedAt
          deletedAt
          title
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
}
