ARG POSTGRES_IMAGE=postgres:18
FROM ${POSTGRES_IMAGE}

ARG POSTGRES_MAJOR=18
ARG PG_ROARINGBITMAP_VERSION=1.2.0

USER root

COPY bin/install-roaringbitmap.sh /usr/local/bin/install-roaringbitmap

RUN chmod +x /usr/local/bin/install-roaringbitmap \
  && POSTGRES_MAJOR="${POSTGRES_MAJOR}" \
     PG_ROARINGBITMAP_VERSION="${PG_ROARINGBITMAP_VERSION}" \
     /usr/local/bin/install-roaringbitmap

USER postgres
