ARG PARADEDB_IMAGE=paradedb/paradedb:0.24.1-pg17
FROM ${PARADEDB_IMAGE}

ARG POSTGRES_MAJOR=17
ARG PG_ROARINGBITMAP_VERSION=1.2.0

USER root

COPY bin/install-roaringbitmap.sh /usr/local/bin/install-roaringbitmap

RUN chmod +x /usr/local/bin/install-roaringbitmap \
  && POSTGRES_MAJOR="${POSTGRES_MAJOR}" \
     PG_ROARINGBITMAP_VERSION="${PG_ROARINGBITMAP_VERSION}" \
     /usr/local/bin/install-roaringbitmap

USER postgres
