mutation LocaleSetDefault($input: LocaleSetDefaultInput!) {
  storeMutation {
    localeSetDefault(input: $input) {
      success
      userErrors {
        code
        message
        field
      }
    }
  }
}
