mutation LocaleDelete($input: LocaleDeleteInput!) {
  storeMutation {
    localeDelete(input: $input) {
      deletedLocaleCode
      userErrors {
        code
        message
        field
      }
    }
  }
}
