mutation StoreDelete($input: StoreDeleteInput!) {
  storeMutation {
    storeDelete(input: $input) {
      deletedStoreId
      userErrors {
        code
        message
        field
      }
    }
  }
}
