query CurrentStore {
  storeQuery {
    currentStore {
      id
      revision
      name
      displayName
      status
      timezone
      email
      locales
      defaultLocale
      currencyCode
      defaultWeightUnit
      defaultDimensionUnit
      createdAt
      updatedAt
    }
  }
}
