query StoreMembers($slug: String!) {
  storeQuery {
    store(slug: $slug) {
      id
      name
      slug
      membership {
        members {
          id
          user {
            id
            email
            firstName
            lastName
          }
          role
          grantedAt
        }
      }
    }
  }
}
