mutation StoreUpdate(
  $storeId: ID!
  $clientMutationId: String!
  $expectedRevision: Int!
  $operations: StoreUpdateInput
) {
  storeMutation {
    storeUpdate(
      storeId: $storeId
      clientMutationId: $clientMutationId
      expectedRevision: $expectedRevision
      operations: $operations
    ) {
      store {
        id
        revision
        name
        displayName
        status
        email
        timezone
        locales
        defaultLocale
        currencyCode
        defaultWeightUnit
        defaultDimensionUnit
        contactDetails {
          name
          slug
          email
          phoneNumbers
        }
        address {
          companyName
          countryCode
          addressLine1
          addressLine2
          city
          administrativeArea
          postalCode
        }
        brand {
          defaultLogo {
            id
          }
          squareLogo {
            id
          }
          coverImage {
            id
          }
          primaryColor
          secondaryColor
          slogan
          shortDescription
          socialLinks {
            platform
            url
          }
        }
        orderProcessing {
          orderNumberPrefix
          orderNumberSuffix
          requireCheckoutConfirmation
          automaticFulfillmentMode
          automaticallyArchiveOrders
        }
        defaults {
          unitSystem
          defaultWeightUnit
          defaultDimensionUnit
          timezone
        }
        currencySettings {
          currencyCode
          currencyDisplay
          currencySign
          grouping
          signDisplay
          minimumFractionDigits
          maximumFractionDigits
          roundingMode
          trailingZeroDisplay
        }
        createdAt
        updatedAt
      }
      operationResults {
        type
        applied
        errors {
          code
          message
          field
        }
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
