query ProjectRoles($slug: String!) {
  projectQuery {
    project(slug: $slug) {
      id
      name
      slug
      roles {
        name
        displayName
        description
        isSystem
        permissions {
          resource
          actions
          effect
        }
        createdAt
      }
    }
  }
}
