query ProjectAvailableResources($slug: String!) {
  projectQuery {
    project(slug: $slug) {
      id
      availableResources {
        service
        name
        actions
        displayName
      }
    }
  }
}
