query Stores($organizationId: ID!) {
  storeQuery {
    stores(organizationId: $organizationId) {
      id
      name
      displayName
      status
      timezone
      email
      locales
      currencies
      baseCurrency
      defaultLocale
      defaultCurrency
      defaultWeightUnit
      defaultDimensionUnit
      createdAt
      updatedAt
    }
  }
}
