query StoreAvailableResources($slug: String!) {
  storeQuery {
    store(slug: $slug) {
      id
      membership {
        availableResources {
          name
          actions
          displayName
        }
      }
    }
  }
}
