mutation ProjectUpdate($input: ProjectUpdateInput!) {
  projectMutation {
    projectUpdate(input: $input) {
      project {
        id
        name
        slug
        email
        timezone
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
