query Stores {
  storeQuery {
    stores {
      id
      name
      slug
      status
      timezone
      email
      locales
      currencies
      baseCurrency
      defaultLocale
      defaultCurrency
      defaultWeightUnit
      defaultDimensionUnit
      createdAt
      updatedAt
    }
  }
}
