mutation StoreUpdate(
  $storeId: ID!
  $clientMutationId: String!
  $operations: StoreUpdateInput
) {
  storeMutation {
    storeUpdate(
      storeId: $storeId
      clientMutationId: $clientMutationId
      operations: $operations
    ) {
      store {
        id
        name
        displayName
        email
        timezone
      }
      operationResults {
        type
        applied
        errors {
          code
          message
          field
        }
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
