query StoreRoles($slug: String!) {
  storeQuery {
    store(slug: $slug) {
      id
      name
      slug
      membership {
        roles {
          id
          name
          displayName
          description
          isSystem
          permissions {
            resource
            actions
            effect
          }
          createdAt
        }
      }
    }
  }
}
