mutation StoreCreate($input: StoreCreateInput!) {
  storeMutation {
    storeCreate(input: $input) {
      store {
        id
        name
        displayName
        status
        timezone
        email
        locales
        currencies
        baseCurrency
        defaultLocale
        defaultCurrency
        defaultWeightUnit
        defaultDimensionUnit
        createdAt
        updatedAt
        membership {
          domain
        }
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
