mutation StoreCreate($input: StoreCreateInput!) {
  storeMutation {
    storeCreate(input: $input) {
      store {
        id
        name
        slug
        status
        timezone
        email
        locales
        currencies
        baseCurrency
        defaultLocale
        defaultCurrency
        defaultWeightUnit
        defaultDimensionUnit
        createdAt
        updatedAt
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
