mutation SignUp($input: UserSignUpInput!) {
  authMutation {
    signUp(input: $input) {
      user {
        id
        email
        emailVerified
        firstName
        lastName
        isAdmin
        createdAt
        updatedAt
      }
      token {
        accessToken
        refreshToken
        expiresIn
      }
      userErrors {
        code
        message
        field
      }
    }
  }
}
