"""A published category in the storefront catalog hierarchy."""
type Category implements Node @key(fields: "id") {
  id: ID!
  handle: String!
  name: String!
  description: RichText
  excerpt: RichText
  seo: SEO!
  parent: Category
  ancestors: [Category!]!
  children(
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): CategoryConnection!
  media(
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): CategoryMediaConnection!
  featuredMedia: Media
  publishedAt: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

"""A Relay connection to categories."""
type CategoryConnection implements Connection {
  edges: [CategoryEdge!]!
  nodes: [Category!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

"""A category and its opaque position in a category connection."""
type CategoryEdge {
  cursor: Cursor!
  node: Category!
}
