query Categories(
  $first: Int
  $after: Cursor
  $last: Int
  $before: Cursor
  $sort: CategorySort
  $childrenFirst: Int
  $childrenLast: Int
) {
  categories(first: $first, after: $after, last: $last, before: $before, sort: $sort) {
    edges {
      cursor
      node {
        id
        iid
        title
        handle
        description
        excerpt
        # listingType
        createdAt
        updatedAt
        seoTitle
        seoDescription
        cover {
          id
          iid
          url
          source
        }
        children(first: $childrenFirst, last: $childrenLast, sort: $sort) {
          edges {
            node {
              title
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
