query ProductContainerTagsConnection(
  $handle: String!
  $first: Int
  $after: Cursor
  $last: Int
  $before: Cursor
  $sort: TagSort
) {
  variant(handle: $handle) {
    product {
      tags(first: $first, after: $after, last: $last, before: $before, sort: $sort) {
        edges {
          cursor
          node {
            id
            title
            handle
          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }
  }
}
