query ProductContainerTagsList($handle: String!, $first: Int = 10) {
  variant(handle: $handle) {
    id
    handle
    product {
      id
      handle
      tags(first: $first) {
        edges {
          node {
            id
            handle
            title
          }
        }
      }
    }
  }
}
