"use client";
import { useMutation, useQuery } from "@apollo/client/react";
import type { ApiCustomerDataRequest, ApiCustomerDataRequestConnection, ApiCustomerDataRequestCreateInput, ApiCustomerDataRequestCreatePayload, ApiCustomerDataRequestDeleteInput, ApiCustomerDataRequestDeletePayload, ApiCustomerDataRequestOrderByInput, ApiCustomerDataRequestUpdateInput, ApiCustomerDataRequestUpdatePayload, ApiCustomerDataRequestWhereInput, ApiCustomerMerge, ApiCustomerMergeConnection, ApiCustomerMergeCreateInput, ApiCustomerMergeCreatePayload, ApiCustomerMergeDeleteInput, ApiCustomerMergeDeletePayload, ApiCustomerMergeOrderByInput, ApiCustomerMergeUpdateInput, ApiCustomerMergeUpdatePayload, ApiCustomerMergeWhereInput, ApiCustomersMutation, ApiCustomersQuery, ApiGenericUserError } from "@/graphql/types";
import { CUSTOMER_DATA_REQUEST_CREATE_MUTATION, CUSTOMER_DATA_REQUEST_DELETE_MUTATION, CUSTOMER_DATA_REQUEST_QUERY, CUSTOMER_DATA_REQUEST_UPDATE_MUTATION, CUSTOMER_DATA_REQUESTS_QUERY, CUSTOMER_MERGE_CREATE_MUTATION, CUSTOMER_MERGE_DELETE_MUTATION, CUSTOMER_MERGE_QUERY, CUSTOMER_MERGE_UPDATE_MUTATION, CUSTOMER_MERGES_QUERY } from "../graphql/operations";

export interface DataRequestVariables { first?: number; after?: string | null; where?: ApiCustomerDataRequestWhereInput | null; orderBy?: ApiCustomerDataRequestOrderByInput[] | null; }
export interface MergeVariables { first?: number; after?: string | null; where?: ApiCustomerMergeWhereInput | null; orderBy?: ApiCustomerMergeOrderByInput[] | null; }
export function useCustomerDataRequests(variables: DataRequestVariables) { const query = useQuery<{ customersQuery: Pick<ApiCustomersQuery, "customerDataRequests"> & { customerDataRequests: ApiCustomerDataRequestConnection } }, DataRequestVariables>(CUSTOMER_DATA_REQUESTS_QUERY, { variables, fetchPolicy: "cache-and-network" }); const connection = (query.data ?? query.previousData)?.customersQuery.customerDataRequests ?? null; return { requests: connection?.edges.map((edge) => edge.node) ?? [], totalCount: connection?.totalCount ?? 0, pageInfo: connection?.pageInfo ?? null, loading: query.loading, error: query.error ?? null, refetch: query.refetch }; }
export function useCustomerDataRequest(id?: string) { const query = useQuery<{ customersQuery: Pick<ApiCustomersQuery, "customerDataRequest"> & { customerDataRequest: ApiCustomerDataRequest | null } }, { id: string }>(CUSTOMER_DATA_REQUEST_QUERY, { variables: { id: id ?? "" }, skip: !id, fetchPolicy: "cache-and-network" }); return { request: (query.data ?? query.previousData)?.customersQuery.customerDataRequest ?? null, loading: query.loading, error: query.error ?? null, refetch: query.refetch }; }
export function useCustomerMerges(variables: MergeVariables) { const query = useQuery<{ customersQuery: Pick<ApiCustomersQuery, "customerMerges"> & { customerMerges: ApiCustomerMergeConnection } }, MergeVariables>(CUSTOMER_MERGES_QUERY, { variables, fetchPolicy: "cache-and-network" }); const connection = (query.data ?? query.previousData)?.customersQuery.customerMerges ?? null; return { merges: connection?.edges.map((edge) => edge.node) ?? [], totalCount: connection?.totalCount ?? 0, pageInfo: connection?.pageInfo ?? null, loading: query.loading, error: query.error ?? null, refetch: query.refetch }; }
export function useCustomerMerge(id?: string) { const query = useQuery<{ customersQuery: Pick<ApiCustomersQuery, "customerMerge"> & { customerMerge: ApiCustomerMerge | null } }, { id: string }>(CUSTOMER_MERGE_QUERY, { variables: { id: id ?? "" }, skip: !id, fetchPolicy: "cache-and-network" }); return { merge: (query.data ?? query.previousData)?.customersQuery.customerMerge ?? null, loading: query.loading, error: query.error ?? null, refetch: query.refetch }; }
const unexpected = (cause: unknown) => [{ code: "UNEXPECTED_ERROR", message: cause instanceof Error ? cause.message : "Unexpected error" }] as ApiGenericUserError[];
export function useCustomerDataRequestMutations() {
  const [createMutation, createState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerDataRequestCreate"> & { customerDataRequestCreate: ApiCustomerDataRequestCreatePayload } }, { input: ApiCustomerDataRequestCreateInput }>(CUSTOMER_DATA_REQUEST_CREATE_MUTATION);
  const [updateMutation, updateState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerDataRequestUpdate"> & { customerDataRequestUpdate: ApiCustomerDataRequestUpdatePayload } }, { dataRequestId: string; operations: ApiCustomerDataRequestUpdateInput }>(CUSTOMER_DATA_REQUEST_UPDATE_MUTATION);
  const [deleteMutation, deleteState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerDataRequestDelete"> & { customerDataRequestDelete: ApiCustomerDataRequestDeletePayload } }, { input: ApiCustomerDataRequestDeleteInput }>(CUSTOMER_DATA_REQUEST_DELETE_MUTATION);
  return { createRequest: async (input: ApiCustomerDataRequestCreateInput) => { try { const result = await createMutation({ variables: { input }, refetchQueries: [CUSTOMER_DATA_REQUESTS_QUERY] }); return result.data?.customersMutation.customerDataRequestCreate ?? { dataRequest: null, userErrors: [] }; } catch (cause) { return { dataRequest: null, userErrors: unexpected(cause) }; } }, updateRequest: async (dataRequestId: string, operations: ApiCustomerDataRequestUpdateInput) => { try { const result = await updateMutation({ variables: { dataRequestId, operations }, refetchQueries: [CUSTOMER_DATA_REQUESTS_QUERY] }); const payload = result.data?.customersMutation.customerDataRequestUpdate; return { dataRequest: payload?.dataRequest ?? null, userErrors: [...(payload?.userErrors ?? []), ...(payload?.operationResults.flatMap((item) => item.errors) ?? [])] }; } catch (cause) { return { dataRequest: null, userErrors: unexpected(cause) }; } }, deleteRequest: async (input: ApiCustomerDataRequestDeleteInput) => { try { const result = await deleteMutation({ variables: { input }, refetchQueries: [CUSTOMER_DATA_REQUESTS_QUERY] }); return result.data?.customersMutation.customerDataRequestDelete ?? { deletedDataRequestId: null, userErrors: [] }; } catch (cause) { return { deletedDataRequestId: null, userErrors: unexpected(cause) }; } }, loading: createState.loading || updateState.loading || deleteState.loading, error: createState.error ?? updateState.error ?? deleteState.error ?? null };
}
export function useCustomerMergeMutations() {
  const [createMutation, createState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerMergeCreate"> & { customerMergeCreate: ApiCustomerMergeCreatePayload } }, { input: ApiCustomerMergeCreateInput }>(CUSTOMER_MERGE_CREATE_MUTATION);
  const [updateMutation, updateState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerMergeUpdate"> & { customerMergeUpdate: ApiCustomerMergeUpdatePayload } }, { mergeId: string; operations: ApiCustomerMergeUpdateInput }>(CUSTOMER_MERGE_UPDATE_MUTATION);
  const [deleteMutation, deleteState] = useMutation<{ customersMutation: Pick<ApiCustomersMutation, "customerMergeDelete"> & { customerMergeDelete: ApiCustomerMergeDeletePayload } }, { input: ApiCustomerMergeDeleteInput }>(CUSTOMER_MERGE_DELETE_MUTATION);
  return { createMerge: async (input: ApiCustomerMergeCreateInput) => { try { const result = await createMutation({ variables: { input }, refetchQueries: [CUSTOMER_MERGES_QUERY] }); return result.data?.customersMutation.customerMergeCreate ?? { merge: null, userErrors: [] }; } catch (cause) { return { merge: null, userErrors: unexpected(cause) }; } }, updateMerge: async (mergeId: string, operations: ApiCustomerMergeUpdateInput) => { try { const result = await updateMutation({ variables: { mergeId, operations }, refetchQueries: [CUSTOMER_MERGES_QUERY] }); const payload = result.data?.customersMutation.customerMergeUpdate; return { merge: payload?.merge ?? null, userErrors: [...(payload?.userErrors ?? []), ...(payload?.operationResults.flatMap((item) => item.errors) ?? [])] }; } catch (cause) { return { merge: null, userErrors: unexpected(cause) }; } }, deleteMerge: async (input: ApiCustomerMergeDeleteInput) => { try { const result = await deleteMutation({ variables: { input }, refetchQueries: [CUSTOMER_MERGES_QUERY] }); return result.data?.customersMutation.customerMergeDelete ?? { deletedMergeId: null, userErrors: [] }; } catch (cause) { return { deletedMergeId: null, userErrors: unexpected(cause) }; } }, loading: createState.loading || updateState.loading || deleteState.loading, error: createState.error ?? updateState.error ?? deleteState.error ?? null };
}
