mutation ApplicationAdminApplicationAuthProviderCredentialsRotate(
  $input: ApplicationAuthProviderCredentialsRotateInput!
) {
  applicationMutation {
    applicationAuthProviderCredentialsRotate(input: $input) {
      provider {
        applicationId
        provider
        configured
        enabled
        maskedClientId
        scopes
        revision
        callbackUrl
      }
      userErrors {
        field
        message
        code
      }
    }
  }
}
