mutation ApplicationAdminApplicationAuthProviderCredentialsDelete(
  $input: ApplicationAuthProviderCredentialsDeleteInput!
) {
  applicationMutation {
    applicationAuthProviderCredentialsDelete(input: $input) {
      provider {
        applicationId
        provider
        configured
        enabled
        maskedClientId
        scopes
        revision
        callbackUrl
      }
      userErrors {
        field
        message
        code
      }
    }
  }
}
