mutation ApplicationAdminApplicationCreate($input: ApplicationCreateInput!) {
  applicationMutation {
    applicationCreate(input: $input) {
      application {
        id
        organizationId
        name
      }
      userErrors {
        field
        message
        code
      }
    }
  }
}
