mutation ApplicationAdminApplicationOAuthClientSecretRotate(
  $input: ApplicationOAuthClientSecretRotateInput!
) {
  applicationMutation {
    applicationOAuthClientSecretRotate(input: $input) {
      client {
        id
        applicationId
        clientId
        clientType
        disabled
        archived
        revision
        updatedAt
      }
      clientSecret
      userErrors {
        field
        message
        code
      }
    }
  }
}
