query ApplicationAdminApplicationUser($organizationId: ID!, $applicationId: ID!, $userId: ID!) {
  applicationQuery {
    application(organizationId: $organizationId, id: $applicationId) {
      id
      user(id: $userId) {
        id
        applicationId
        name
        firstName
        lastName
        email
        emailVerified
        imageUrl
        status
        security {
          activeSessionCount
          linkedAccountCount
          hasPasswordLogin
        }
        linkedAccounts {
          id
          provider
          isOnlyLoginMethod
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
}
