import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Apps Admin API - installation lifecycle', [
  ['APPS-LIFE-001', 'appInstall accepts a ready bundled App and creates one installation and INSTALL operation'],
  ['APPS-LIFE-002', 'successful install reaches ACTIVE with installed version, manifest hash, and healthy status'],
  ['APPS-LIFE-003', 'install invokes only the target manifest install workflow with server-owned installation context'],
  ['APPS-LIFE-004', 'install rejects blank, unknown, stopped, starting, or failed App runtime'],
  ['APPS-LIFE-005', 'install rejects a second non-terminal installation of the same App in one store'],
  ['APPS-LIFE-006', 'the same bundled App can be installed independently in two stores'],
  ['APPS-LIFE-007', 'failed install reaches INSTALL_FAILED with one safe operation error'],
  ['APPS-LIFE-008', 'retry after INSTALL_FAILED reuses the installation row and starts a new operation'],
  ['APPS-LIFE-009', 'appUpdate starts only from ACTIVE, SUSPENDED, or UPDATE_FAILED'],
  ['APPS-LIFE-010', 'successful update records the target manifest snapshot and installed version'],
  ['APPS-LIFE-011', 'update of a suspended installation returns to SUSPENDED after success'],
  ['APPS-LIFE-012', 'failed update reaches UPDATE_FAILED and preserves the last installed version'],
  ['APPS-LIFE-013', 'retry after UPDATE_FAILED restores the status that preceded the failed update'],
  ['APPS-LIFE-014', 'appSuspend transitions ACTIVE through SUSPENDING to SUSPENDED'],
  ['APPS-LIFE-015', 'suspend disables installation capability routes before terminal completion'],
  ['APPS-LIFE-016', 'failed suspend restores ACTIVE state and capability availability'],
  ['APPS-LIFE-017', 'appResume transitions SUSPENDED through RESUMING to ACTIVE'],
  ['APPS-LIFE-018', 'successful resume re-enables capability routes for the installation'],
  ['APPS-LIFE-019', 'failed resume preserves SUSPENDED state and disabled capabilities'],
  ['APPS-LIFE-020', 'appUninstall accepts every documented recoverable installation state'],
  ['APPS-LIFE-021', 'uninstall immediately disables capabilities and revokes installation secrets'],
  ['APPS-LIFE-022', 'successful uninstall reaches UNINSTALLED and revokes scopes without deleting history'],
  ['APPS-LIFE-023', 'failed uninstall reaches UNINSTALL_FAILED without re-enabling revoked access'],
  ['APPS-LIFE-024', 'uninstalled App can be installed again as a new current installation'],
  ['APPS-LIFE-025', 'invalid lifecycle transition returns userErrors and creates no operation'],
  ['APPS-LIFE-026', 'foreign installation ID cannot start update, suspend, resume, or uninstall'],
  ['APPS-LIFE-027', 'workflow completion is idempotent and cannot apply terminal side effects twice'],
  ['APPS-LIFE-028', 'lifecycle payload returns installation, operation, duplicate flag, and empty userErrors on acceptance'],
] as const);
