mutation CustomerTagDelete($input: CustomerTagDeleteInput!) {
  customersMutation {
    customerTagDelete(input: $input) {
      deletedTagId
      userErrors {
        code
        field
        message
      }
    }
  }
}
