mutation CustomerGroupDelete($input: CustomerGroupDeleteInput!) {
  customersMutation {
    customerGroupDelete(input: $input) {
      deletedGroupId
      userErrors {
        code
        field
        message
      }
    }
  }
}
