mutation CustomerSegmentDelete($input: CustomerSegmentDeleteInput!) {
  customersMutation {
    customerSegmentDelete(input: $input) {
      deletedSegmentId
      userErrors {
        code
        field
        message
      }
    }
  }
}
