mutation CustomerDataRequestDelete($input: CustomerDataRequestDeleteInput!) {
  customersMutation {
    customerDataRequestDelete(input: $input) {
      deletedDataRequestId
      userErrors {
        code
        field
        message
      }
    }
  }
}
