mutation CustomerGroupUpdate(
  $groupId: ID!
  
  $operations: CustomerGroupUpdateInput!
) {
  customersMutation {
    customerGroupUpdate(
      groupId: $groupId
      
      operations: $operations
    ) {
      group {
        id
        code
        name
        description
        isDefault
        isActive
        revision
        customersCount
        customerMemberships(first: 100) {
          edges {
            cursor
            node {
              id
              isPrimary
              source
              assignedById
              assignedAt
              expiresAt
              isActive
              customer {
                id
              }
            }
          }
          pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
          }
          totalCount
        }
      }
      operationResults {
        type
        applied
        errors {
          code
          field
          message
        }
      }
      userErrors {
        code
        field
        message
      }
    }
  }
}
