import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Notifications Admin API - webhooks', [
  ['NTF-WEB-001', 'webhookCapabilities returns every supported event and API version from server registries'],
  ['NTF-WEB-002', 'capabilities identify default, stable, unstable, and deprecated API versions correctly'],
  ['NTF-WEB-003', 'webhookSubscriptions returns current-store subscriptions in deterministic newest-first order'],
  ['NTF-WEB-004', 'createWebhook persists a valid event, format, HTTPS URL, API version, and ACTIVE status'],
  ['NTF-WEB-005', 'first webhook creation creates one store signing secret when none exists'],
  ['NTF-WEB-006', 'subsequent webhook creation reuses the current store signing secret'],
  ['NTF-WEB-007', 'unsupported event returns UNSUPPORTED_WEBHOOK_EVENT without persistence'],
  ['NTF-WEB-008', 'unsupported API version returns UNSUPPORTED_WEBHOOK_API_VERSION without persistence'],
  ['NTF-WEB-009', 'webhook URL requires HTTPS without embedded credentials or non-standard port'],
  ['NTF-WEB-010', 'webhook URL rejects localhost, link-local, private, metadata, multicast, and reserved networks'],
  ['NTF-WEB-011', 'hostname resolving to any forbidden IPv4 or IPv6 address is rejected'],
  ['NTF-WEB-012', 'DNS resolution failure is rejected without a permissive fallback'],
  ['NTF-WEB-013', 'URL validation prevents encoding, IPv4-mapped IPv6, and redirect-style SSRF bypasses'],
  ['NTF-WEB-014', 'updateWebhook changes only supplied mutable fields and increments version'],
  ['NTF-WEB-015', 'stale webhook expectedVersion returns VERSION_CONFLICT without changes'],
  ['NTF-WEB-016', 'parallel webhook updates with one version produce exactly one success'],
  ['NTF-WEB-017', 'webhook can be disabled and re-enabled without losing identity or version history'],
  ['NTF-WEB-018', 'disabled webhook is excluded from delivery resolution'],
  ['NTF-WEB-019', 'update to unsupported event, version, or unsafe URL preserves previous subscription'],
  ['NTF-WEB-020', 'deleteWebhook removes only the selected current-store subscription'],
  ['NTF-WEB-021', 'delete of unknown or foreign webhook returns WEBHOOK_NOT_FOUND'],
  ['NTF-WEB-022', 'revealWebhookSecret returns only the active current-store signing secret to an authorized admin'],
  ['NTF-WEB-023', 'reveal without a configured secret returns WEBHOOK_SIGNING_SECRET_NOT_FOUND'],
  ['NTF-WEB-024', 'signing secret from Store A is never revealed or used for Store B'],
  ['NTF-WEB-025', 'delivered webhook signature binds timestamp, delivery ID, and exact body'],
  ['NTF-WEB-026', 'webhook create, update, delete, and secret reveal write safe audit records'],
  ['NTF-WEB-027', 'audit, logs, and errors never include the webhook signing secret or signature material'],
  ['NTF-WEB-028', 'failed webhook mutation leaves subscription, secret, and audit state transactionally consistent'],
] as const);
