input DateFilter {
  _eq: Date
  _neq: Date
  _gt: Date
  _gte: Date
  _lt: Date
  _lte: Date
  _in: [Date!]
  _notIn: [Date!]
  _is: Boolean
  _isNot: Boolean
  _between: [Date!]
}

input BigIntFilter {
  _eq: BigInt
  _neq: BigInt
  _gt: BigInt
  _gte: BigInt
  _lt: BigInt
  _lte: BigInt
  _in: [BigInt!]
  _notIn: [BigInt!]
  _is: Boolean
  _isNot: Boolean
  _between: [BigInt!]
}

input CustomerLifecycleStatusFilter {
  _eq: CustomerLifecycleStatus
  _neq: CustomerLifecycleStatus
  _in: [CustomerLifecycleStatus!]
  _notIn: [CustomerLifecycleStatus!]
}

input CustomerAccountStatusFilter {
  _eq: CustomerAccountStatus
  _neq: CustomerAccountStatus
  _in: [CustomerAccountStatus!]
  _notIn: [CustomerAccountStatus!]
}

input CustomerConsentStateFilter {
  _eq: CustomerConsentState
  _neq: CustomerConsentState
  _in: [CustomerConsentState!]
  _notIn: [CustomerConsentState!]
}

input CustomerAddressValidationStatusFilter {
  _eq: CustomerAddressValidationStatus
  _neq: CustomerAddressValidationStatus
  _in: [CustomerAddressValidationStatus!]
  _notIn: [CustomerAddressValidationStatus!]
}

input CustomerTaxIdentifierStatusFilter {
  _eq: CustomerTaxIdentifierStatus
  _neq: CustomerTaxIdentifierStatus
  _in: [CustomerTaxIdentifierStatus!]
  _notIn: [CustomerTaxIdentifierStatus!]
}

input CustomerTaxExemptionStatusFilter {
  _eq: CustomerTaxExemptionStatus
  _neq: CustomerTaxExemptionStatus
  _in: [CustomerTaxExemptionStatus!]
  _notIn: [CustomerTaxExemptionStatus!]
}

input CustomerAssignmentSourceFilter {
  _eq: CustomerAssignmentSource
  _neq: CustomerAssignmentSource
  _in: [CustomerAssignmentSource!]
  _notIn: [CustomerAssignmentSource!]
}

input CustomerSegmentTypeFilter {
  _eq: CustomerSegmentType
  _neq: CustomerSegmentType
  _in: [CustomerSegmentType!]
  _notIn: [CustomerSegmentType!]
}

input CustomerSegmentStatusFilter {
  _eq: CustomerSegmentStatus
  _neq: CustomerSegmentStatus
  _in: [CustomerSegmentStatus!]
  _notIn: [CustomerSegmentStatus!]
}

input CustomerMergeStatusFilter {
  _eq: CustomerMergeStatus
  _neq: CustomerMergeStatus
  _in: [CustomerMergeStatus!]
  _notIn: [CustomerMergeStatus!]
}

input CustomerDataRequestTypeFilter {
  _eq: CustomerDataRequestType
  _neq: CustomerDataRequestType
  _in: [CustomerDataRequestType!]
  _notIn: [CustomerDataRequestType!]
}

input CustomerDataRequestStatusFilter {
  _eq: CustomerDataRequestStatus
  _neq: CustomerDataRequestStatus
  _in: [CustomerDataRequestStatus!]
  _notIn: [CustomerDataRequestStatus!]
}
