import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Application Admin API - applications and auth configuration', [
  ['APP-ADM-001', 'organization admin can create an application with generated ID and read-only canonical resource'],
  ['APP-ADM-002', 'application create rejects duplicate name inside one organization without partial auth configuration'],
  ['APP-ADM-003', 'same application name can exist in different organizations without leaking ownership'],
  ['APP-ADM-004', 'application query hides an existing application when organizationId does not own it'],
  ['APP-ADM-005', 'applications connection filters by lifecycle status and search within the selected organization only'],
  ['APP-ADM-006', 'applications connection order and cursor pagination are stable across same-timestamp records'],
  ['APP-ADM-007', 'application update requires expected revision and returns the incremented revision'],
  ['APP-ADM-008', 'stale application update returns a revision conflict user error and changes no fields'],
  ['APP-ADM-009', 'application archive disables the realm and prevents new public auth traffic'],
  ['APP-ADM-010', 'archived application remains readable to authorized admins but is absent from active-only lists'],
  ['APP-ADM-011', 'application resource cannot be supplied or changed through create or update inputs'],
  ['APP-ADM-012', 'auth configuration query requires org.application-auth read permission'],
  ['APP-ADM-013', 'auth update changes TTL policy only inside allowed platform ranges'],
  ['APP-ADM-014', 'auth update rejects out-of-range token and session TTL values without partial changes'],
  ['APP-ADM-015', 'trusted origins are normalized, deduplicated, and exposed only as exact origins'],
  ['APP-ADM-016', 'trusted origins reject wildcards, path/query components, and malformed origins'],
  ['APP-ADM-017', 'branding update accepts allowlisted colors and HTTPS logo URL only'],
  ['APP-ADM-018', 'branding update rejects scriptable or insecure logo URL without changing existing branding'],
  ['APP-ADM-019', 'email delivery update stores only profile and template references, never transport secrets'],
  ['APP-ADM-020', 'enabling password reset or verified signup requires configured email delivery'],
  ['APP-ADM-021', 'auth method update cannot remove the last sign-in method while realm is enabled'],
  ['APP-ADM-022', 'realm enabled set validates required methods, delivery, and provider state before enabling'],
  ['APP-ADM-023', 'realm disabled set preserves users, clients, providers, and configuration rows'],
  ['APP-ADM-024', 'protocol URLs are built from IAM public base URL and target application ID only'],
  ['APP-ADM-025', 'all application and auth mutations emit secret-free success and failure admin audit records'],
] as const);
