import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Application Admin API - OAuth client management', [
  ['APP-OAUTH-001', 'admin can create a public client with server-owned protocol policy'],
  ['APP-OAUTH-002', 'admin can create a confidential client and receives plaintext secret exactly once'],
  ['APP-OAUTH-003', 'created confidential client stores only a hashed secret and never returns the hash'],
  ['APP-OAUTH-004', 'client create rejects caller-supplied resource, grant type, response type, auth method, or secret hash'],
  ['APP-OAUTH-005', 'client create rejects invalid redirect URI without creating a client row'],
  ['APP-OAUTH-006', 'production client accepts only HTTPS redirect and post-logout URIs'],
  ['APP-OAUTH-007', 'development client allows loopback HTTP redirect URI and rejects non-loopback HTTP'],
  ['APP-OAUTH-008', 'redirect and post-logout URIs are exact, deduplicated, and reject wildcard or fragment'],
  ['APP-OAUTH-009', 'client list and get require org.application-oauth-clients read permission'],
  ['APP-OAUTH-010', 'client connection filters by type, environment, disabled, archived, and search inside application scope'],
  ['APP-OAUTH-011', 'client connection pagination remains stable with multiple clients sharing updatedAt'],
  ['APP-OAUTH-012', 'client update changes only mutable metadata and increments revision'],
  ['APP-OAUTH-013', 'stale client update returns revision conflict and preserves previous values'],
  ['APP-OAUTH-014', 'client disable prevents authorize, token exchange, refresh, and introspection active state'],
  ['APP-OAUTH-015', 'client re-enable restores only the client state and does not revive revoked sessions or token families'],
  ['APP-OAUTH-016', 'client archive disables the client and excludes it from active default lists'],
  ['APP-OAUTH-017', 'archived client cannot be updated, enabled, receive skipConsent changes, or rotate secret'],
  ['APP-OAUTH-018', 'public client secret rotation is rejected without changing revision'],
  ['APP-OAUTH-019', 'confidential client secret rotation returns a new plaintext secret once and invalidates the old secret'],
  ['APP-OAUTH-020', 'secret rotation requires admin permission and records a secret-free audit diff'],
  ['APP-OAUTH-021', 'skipConsent can be enabled only for a confirmed first-party client'],
  ['APP-OAUTH-022', 'skipConsent disable is allowed without weakening normal consent requirements for other clients'],
  ['APP-OAUTH-023', 'client ID from another application cannot be read or mutated through this application scope'],
  ['APP-OAUTH-024', 'member without explicit OAuth client permission cannot list, create, update, disable, archive, or rotate clients'],
  ['APP-OAUTH-025', 'application user session cannot access OAuth client management through public application routes'],
] as const);
