mutation DiscountCreate($input: DiscountCreateInput!) {
  pricingMutation {
    discountCreate(input: $input) {
      discount {
        id
      }
      userErrors {
        code
        field
        message
      }
    }
  }
}
