import { definePendingContractSuite } from './contract-case';

definePendingContractSuite('Application password auth — OAuth Authorization Code', [
  ['PWD-OAUTH-001', 'public client completes password signin and Authorization Code with S256 PKCE'],
  ['PWD-OAUTH-002', 'confidential client requires both client authentication and S256 PKCE'],
  ['PWD-OAUTH-003', 'missing PKCE challenge cannot produce an authorization code'],
  ['PWD-OAUTH-004', 'PKCE method other than S256 is rejected'],
  ['PWD-OAUTH-005', 'missing or invalid verifier cannot exchange the code'],
  ['PWD-OAUTH-006', 'authorization code replay is rejected'],
  ['PWD-OAUTH-007', 'code from A cannot be exchanged through issuer or client B'],
  ['PWD-OAUTH-008', 'client A cannot authorize through issuer B'],
  ['PWD-OAUTH-009', 'redirect URI requires an exact registered match'],
  ['PWD-OAUTH-010', 'authorization errors never redirect to an untrusted URI'],
  ['PWD-OAUTH-011', 'state is preserved and mismatch is rejected by the client flow'],
  ['PWD-OAUTH-012', 'ID token nonce is bound to the authorization request'],
  ['PWD-OAUTH-013', 'authorize, exchange, and refresh require the exact canonical resource'],
  ['PWD-OAUTH-014', 'missing, empty, duplicate, or foreign resource returns invalid_target'],
  ['PWD-OAUTH-015', 'resource A cannot produce an audience through issuer or client B'],
  ['PWD-OAUTH-016', 'tokens contain only granted and approved scopes and claims'],
  ['PWD-OAUTH-017', 'unknown scope cannot silently expand privileges'],
  ['PWD-OAUTH-018', 'client_credentials never issues a userless token'],
  ['PWD-OAUTH-019', 'password and implicit grants are unavailable'],
  ['PWD-OAUTH-020', 'ID token has valid signature, issuer, audience, subject, times, nonce, and email claims'],
  ['PWD-OAUTH-021', 'access token has exact realm, resource, user, client, scope, and actor claims'],
  ['PWD-OAUTH-022', 'tokens contain no password secrets, provider tokens, or platform roles'],
  ['PWD-OAUTH-023', 'JWKS from issuer A cannot validate a token as issuer B'],
  ['PWD-OAUTH-024', 'consent is bound to exact user, application, client, scopes, and resource'],
  ['PWD-OAUTH-025', 'expired authorization context cannot issue a code'],
  ['PWD-OAUTH-026', 'authorization context is single-use'],
  ['PWD-OAUTH-027', 'context substitution across browser, client, or application is rejected'],
  ['PWD-OAUTH-028', 'application or client disable after code issuance prevents token exchange'],
  ['PWD-OAUTH-029', 'user block after code issuance prevents token exchange'],
  ['PWD-OAUTH-030', 'ambiguous or malformed protocol request cannot issue tokens'],
] as const);
