import { bigint, check, index, integer, jsonb, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { discount } from "./discounts.js";
import { discountFunctionBindingStatusEnum, discountFunctionFailureModeEnum, discountFunctionTargetEnum, pricingSchema } from "./schema.js";

export const discountFunctionBinding = pricingSchema.table("discount_function_binding", {
  id: uuid("id").primaryKey().default(sql`uuidv7()`), storeId: uuid("store_id").notNull(), discountId: uuid("discount_id").notNull().references(() => discount.id, { onDelete: "cascade" }), target: discountFunctionTargetEnum("target").notNull(), contractVersion: integer("contract_version").notNull(), installationId: uuid("installation_id").notNull(), functionKey: text("function_key").notNull(), precedence: integer("precedence").notNull(), activationSequence: bigint("activation_sequence", { mode: "number" }).notNull(), status: discountFunctionBindingStatusEnum("status").notNull(), failureMode: discountFunctionFailureModeEnum("failure_mode").notNull(), configurationSnapshot: jsonb("configuration_snapshot").notNull(), configurationRevision: text("configuration_revision").notNull(), routeRevision: text("route_revision").notNull(), createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [unique("discount_function_binding_store_id_id_unique").on(table.storeId, table.id), unique("discount_function_binding_discount_target_unique").on(table.discountId, table.target), check("discount_function_binding_contract_check", sql`${table.contractVersion} > 0`), check("discount_function_binding_order_check", sql`${table.precedence} >= 0 AND ${table.activationSequence} >= 0`), check("discount_function_binding_configuration_check", sql`jsonb_typeof(${table.configurationSnapshot}) = 'object'`), check("discount_function_binding_revision_check", sql`length(${table.configurationRevision}) > 0 AND length(${table.routeRevision}) > 0 AND length(${table.functionKey}) > 0`), index("discount_function_binding_active_target_idx").on(table.storeId, table.target, table.precedence, table.activationSequence, table.id).where(sql`${table.status} = 'ACTIVE'`)]);

export type DiscountFunctionBinding = typeof discountFunctionBinding.$inferSelect;
export type NewDiscountFunctionBinding = typeof discountFunctionBinding.$inferInsert;
