import { createStyles } from "antd-style";

export const useStyles = createStyles(({ token }) => ({
  mediaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gridGap: 16,
    position: "relative",
    "& > *:nth-child(1)": {
      gridColumnStart: "span 2",
      gridRowStart: "span 2",
    },
  },
  mediaItem: {
    position: "relative",
    borderRadius: 8,
    overflow: "hidden",
    border: `1px solid ${token.colorBorderSecondary}`,
    background: token.colorBgContainer,
    aspectRatio: "1/1",
    cursor: "grab",
    "&:hover": {
      borderColor: token.colorPrimary,
    },
    "&:hover .media-actions": {
      opacity: 1,
    },
  },
  mediaItemDragging: {
    opacity: 0.5,
  },
  mediaImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  mediaActions: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0, 0, 0, 0.5)",
    opacity: 0,
    transition: "opacity 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mediaActionButton: {
    color: "#fff",
    background: "rgba(0, 0, 0, 0.4)",
    border: "none",
    "&:hover": {
      color: "#fff",
      background: "rgba(0, 0, 0, 0.6)",
    },
  },
  coverBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    background: token.colorPrimary,
    color: "#fff",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: 4,
    zIndex: 1,
  },
  uploadArea: {
    width: "100%",
    aspectRatio: "1/1",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: token.colorBgLayout,
    border: `2px dashed ${token.colorBorder}`,
    borderRadius: 8,
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      borderColor: token.colorPrimary,
      background: token.colorPrimaryBg,
    },
  },
  uploadIcon: {
    fontSize: 24,
    color: token.colorTextSecondary,
    marginBottom: 8,
  },
  draggerIcon: {
    fontSize: 24,
    color: token.colorIcon,
    marginBottom: token.marginXS,
  },
  draggerTitle: {
    fontSize: token.fontSizeLG,
  },
  uploadText: {
    fontSize: 12,
    color: token.colorTextSecondary,
  },
  fileInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: "4px 8px",
    background: "linear-gradient(transparent, rgba(0,0,0,0.7))",
    color: "#fff",
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    fontSize: 12,
    color: token.colorTextSecondary,
  },
  emptyContainer: {
    gridColumn: "1 / -1",
    padding: "40px 20px",
  },
  // List view styles
  listContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  listItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 8,
    borderRadius: 8,
    border: `1px solid ${token.colorBorderSecondary}`,
    background: token.colorBgContainer,
    cursor: "grab",
    "&:hover": {
      borderColor: token.colorPrimary,
      background: token.colorBgLayout,
    },
  },
  listItemDragging: {
    opacity: 0.5,
  },
  listItemImage: {
    width: 64,
    height: 64,
    borderRadius: 6,
    objectFit: "cover",
    flexShrink: 0,
  },
  listItemInfo: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  listItemName: {
    fontSize: 13,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listItemMeta: {
    fontSize: 12,
    color: token.colorTextSecondary,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  listItemActions: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  dragHandle: {
    cursor: "grab",
    color: token.colorTextSecondary,
    padding: 4,
    "&:hover": {
      color: token.colorText,
    },
  },
}));
