federation_version: 2
subgraphs:
  apps:
    routing_url: http://localhost:10001/graphql
    schema:
      file: ./schema/apps-admin.graphql
  inventory:
    routing_url: http://localhost:10005/graphql
    schema:
      file: ./schema/inventory-admin.graphql
  media:
    routing_url: http://localhost:10007/graphql
    schema:
      file: ./schema/media-admin.graphql
  orders:
    routing_url: http://localhost:10003/graphql
    schema:
      file: ./schema/orders-admin.graphql
  project:
    routing_url: http://localhost:10004/graphql
    schema:
      file: ./schema/project-admin.graphql
  users:
    routing_url: http://localhost:10006/graphql
    schema:
      file: ./schema/users-admin.graphql
