query CustomerFindMany($input: CustomersInput) {
  customerQuery {
    findMany(input: $input) {
      data {
        id
        firstName
        lastName
        email
        isVerified
        createdAt
        updatedAt
      }
      meta {
        page
        pageSize
        count
        total
        pageCount
      }
    }
  }
}
