mutation UserSignUp($input: SignUpInput!) {
  userMutation {
    signUp(input: $input) {
      user {
        email
        firstName
        id
        isVerified
        lastName
        phoneNumber
      }
      jwt
    }
  }
}
