query FileFindOne($id: ID!) {
  mediaQuery {
    file(id: $id) {
      id
      provider
      url
      mimeType
      ext
      sizeBytes
      originalName
      altText
      sourceUrl
      isProcessed
      meta
      createdAt
      updatedAt
      deletedAt
      dimensions {
        width
        height
      }
      durationMs
      s3Data {
        bucketId
        objectKey
        etag
        storageClass
      }
      externalData {
        externalId
        providerMeta
      }
    }
  }
}
