"use client";
import { useEffect, useState } from "react";
import { Alert, App, Button, Descriptions, Flex, Input, Skeleton, Tag, Typography } from "antd";
import { DeleteOutlined, MergeCellsOutlined, UserOutlined } from "@ant-design/icons";
import { CustomerMergeStatus } from "@/graphql/types";
import { ModalHeader, ModalLayout, useModalStackContext } from "@/layouts/modals"; import { Paper, PaperHeader } from "@/ui-kit/paper";
import { useEntityPicker } from "@/shared/components/entity-picker-modal"; import type { IPickableEntity } from "@/shared/components/entity-picker-modal/types"; import "@/domains/customers/all-customers/picker/customer-picker-config";
import { useCustomerMerge, useCustomerMergeMutations } from "../../hooks"; import type { CustomerMergeModalPayload } from "../../modals";

export function CustomerMergeModal() {
  const { message, modal } = App.useApp(); const { payload, pop, forcePop, setDirty } = useModalStackContext(); const value = payload as CustomerMergeModalPayload; const isEdit = value.mode === "edit"; const query = useCustomerMerge(isEdit ? value.entityId : undefined); const mutations = useCustomerMergeMutations(); const [sourceId, setSourceId] = useState(value.sourceCustomerId ?? ""); const [sourceLabel, setSourceLabel] = useState(value.sourceCustomerId ?? ""); const [targetId, setTargetId] = useState(""); const [targetLabel, setTargetLabel] = useState(""); const [reason, setReason] = useState(""); const [dirty, setLocalDirty] = useState(false); const [error, setError] = useState<string | null>(null); const merge = query.merge;
  useEffect(() => {
    if (!merge) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate the edit draft when the requested merge arrives.
    setSourceId(merge.sourceCustomer.id);
    setSourceLabel(merge.sourceCustomer.displayName);
    setTargetId(merge.targetCustomer.id);
    setTargetLabel(merge.targetCustomer.displayName);
    setReason(merge.reason ?? "");
    setLocalDirty(false);
  }, [merge]);
  useEffect(() => setDirty(dirty), [dirty, setDirty]);
  const sourcePicker = useEntityPicker<IPickableEntity>({ entityType: "customer", selectionMode: "single", initialSelection: sourceId ? [sourceId] : [], excludeIds: targetId ? [targetId] : [], onConfirm: (items, ids) => { setSourceId(ids[0] ?? ""); setSourceLabel(items[0]?.title ?? ids[0] ?? ""); setLocalDirty(true); } });
  const targetPicker = useEntityPicker<IPickableEntity>({ entityType: "customer", selectionMode: "single", initialSelection: targetId ? [targetId] : [], excludeIds: sourceId ? [sourceId] : [], onConfirm: (items, ids) => { setTargetId(ids[0] ?? ""); setTargetLabel(items[0]?.title ?? ids[0] ?? ""); setLocalDirty(true); } });
  const save = async () => { setError(null); if (!sourceId || !targetId) return setError("Select source and target customers."); if (sourceId === targetId) return setError("Source and target must be different customers."); const input = { sourceCustomerId: sourceId, targetCustomerId: targetId, reason: reason.trim() || null }; const result = merge ? await mutations.updateMerge(merge.id, input) : await mutations.createMerge(input); if (!result.merge || result.userErrors.length) return setError(result.userErrors.map((item) => item.message).join(" ") || "Unable to save merge"); await value.onSaved?.(); setDirty(false); message.success(merge ? "Merge updated" : "Merge requested"); forcePop(); };
  const remove = async () => { if (!merge) return; const confirmed = await modal.confirm({ title: "Delete merge record?", okText: "Delete", okButtonProps: { danger: true } }); if (!confirmed) return; const result = await mutations.deleteMerge({ id: merge.id }); if (!result.deletedMergeId) return setError(result.userErrors.map((item) => item.message).join(" ") || "Unable to delete merge"); await value.onSaved?.(); forcePop(); };
  if (isEdit && query.loading && !merge) return <ModalLayout name="customer-merge" headerProps={{ title: "Customer merge", onClose: pop, submitButtonProps: null }}><Skeleton active /></ModalLayout>;
  const editable = !merge || merge.status === CustomerMergeStatus.Requested;
  return <ModalLayout name="customer-merge" header={<ModalHeader title={merge ? "Customer merge" : "Merge customers"} onClose={pop} extra={merge ? <Tag>{merge.status.toLowerCase().replaceAll("_", " ")}</Tag> : null} submitButtonProps={editable ? { children: merge ? "Save" : "Request merge", loading: mutations.loading, disabled: !!merge && !dirty, onClick: save } : null} />}><Flex vertical gap={12}>{query.error || mutations.error ? <Alert type="error" showIcon message={(query.error ?? mutations.error)?.message} /> : null}{error ? <Alert type="error" showIcon message={error} /> : null}<Paper><PaperHeader title="Customers" icon={<MergeCellsOutlined />} /><Flex vertical gap="middle"><div><Typography.Text strong>Source customer</Typography.Text><Flex gap="small" style={{ marginTop: 8 }}><Input readOnly value={sourceLabel} /><Button icon={<UserOutlined />} onClick={sourcePicker.openPicker} disabled={!editable}>Select</Button></Flex><Typography.Text type="secondary">This profile will be merged and closed.</Typography.Text></div><div><Typography.Text strong>Target customer</Typography.Text><Flex gap="small" style={{ marginTop: 8 }}><Input readOnly value={targetLabel} /><Button icon={<UserOutlined />} onClick={targetPicker.openPicker} disabled={!editable}>Select</Button></Flex><Typography.Text type="secondary">This profile remains active and receives consolidated data.</Typography.Text></div><div><Typography.Text strong>Reason</Typography.Text><Input.TextArea value={reason} disabled={!editable} onChange={(event) => { setReason(event.target.value); setLocalDirty(true); }} rows={4} style={{ marginTop: 8 }} /></div></Flex></Paper>{merge ? <Paper><PaperHeader title="Workflow" /><Descriptions column={1} items={[{ key: "requested", label: "Requested", children: new Date(merge.requestedAt).toLocaleString() }, { key: "started", label: "Started", children: merge.startedAt ? new Date(merge.startedAt).toLocaleString() : "—" }, { key: "finished", label: "Finished", children: merge.finishedAt ? new Date(merge.finishedAt).toLocaleString() : "—" }, { key: "resolution", label: "Resolution", children: <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(merge.resolution, null, 2)}</pre> }, { key: "error", label: "Error", children: merge.errorMessage ? `${merge.errorCode ?? "ERROR"}: ${merge.errorMessage}` : "—" }, { key: "idempotency", label: "Idempotency key", children: merge.idempotencyKey }]} /></Paper> : null}{merge && editable ? <Paper><PaperHeader title="Danger zone" /><Button danger icon={<DeleteOutlined />} onClick={remove}>Delete merge record</Button></Paper> : null}</Flex></ModalLayout>;
}
