appname=casdoor
httpport=9011
runmode=dev

driverName=postgres
dataSourceName=user=postgres password=postgres host=pgbouncer port=6432 sslmode=disable dbname=casdoor
dbName=casdoor

domain=http://localhost:9011

copyrequestbody = true
tableNamePrefix = casdoor

tableNamePrefix =
showSql = true
