enum UnitSystem {
  METRIC
  IMPERIAL
}

enum AutomaticFulfillmentMode {
  ALL_LINE_ITEMS
  GIFT_CARDS_ONLY
  DISABLED
}

enum CurrencyDisplay {
  SYMBOL
  NARROW_SYMBOL
  CODE
  NAME
}

enum CurrencySign {
  STANDARD
  ACCOUNTING
}

enum CurrencyGrouping {
  AUTO
  ALWAYS
  MIN2
  NEVER
}

enum CurrencySignDisplay {
  AUTO
  ALWAYS
  EXCEPT_ZERO
  NEGATIVE
  NEVER
}

enum CurrencyRoundingMode {
  CEIL
  FLOOR
  EXPAND
  TRUNC
  HALF_CEIL
  HALF_FLOOR
  HALF_EXPAND
  HALF_TRUNC
  HALF_EVEN
}

enum CurrencyTrailingZeroDisplay {
  AUTO
  STRIP_IF_INTEGER
}

type StoreOrderSettings implements Node @key(fields: "id") {
  id: ID!
}

type StoreCurrencyFormatting implements Node @key(fields: "id") {
  id: ID!
}

type StoreDefaults {
  unitSystem: UnitSystem!
  defaultWeightUnit: WeightUnit!
  defaultDimensionUnit: DimensionUnit!
  timezone: String!
}

type StoreCurrencySettings {
  currencyCode: CurrencyCode!
  currencyDisplay: CurrencyDisplay!
  currencySign: CurrencySign!
  grouping: CurrencyGrouping!
  signDisplay: CurrencySignDisplay!
  minimumFractionDigits: Int!
  maximumFractionDigits: Int!
  roundingMode: CurrencyRoundingMode!
  trailingZeroDisplay: CurrencyTrailingZeroDisplay!
}
