mutation ProductCreateSimple($input: ProductCreateInput!) {
  catalogMutation {
    productCreate(input: $input) {
      product {
        id
        title
        handle
        isPublished
        publishedAt
        updatedAt
        revision
        media {
          file {
            id
          }
          sortIndex
        }
        options {
          id
          name
          slug
          displayType
          values {
            id
            name
            slug
          }
        }
        variants(first: 10) {
          edges {
            node {
              id
              isDefault
              handle
              inventoryItem {
                id
                sku
                trackInventory
              }
              media {
                file {
                  id
                }
                sortIndex
              }
            }
          }
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
