query ProductFindMany($first: Int, $after: String) {
  catalogQuery {
    products(first: $first, after: $after) {
      edges {
        node {
          id
          handle
          publishedAt
          isPublished
          createdAt
          updatedAt
          title
          description {
            text
            html
            json
          }
          media {
            file {
              id
              originalName
            }
            sortIndex
          }
          options {
            id
            name
            slug
            displayType
            sortIndex
            values {
              id
              name
              slug
              sortIndex
            }
          }
          variantsCount
          variants(first: 10) {
            edges {
              node {
                id
                handle
                isDefault
              }
            }
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
}
