mutation ProductBulkUpdateCancel($jobId: ID!) {
  inventoryMutation {
    productBulkUpdateCancel(jobId: $jobId) {
      job {
        id
        status
      }
      userErrors {
        message
        code
      }
    }
  }
}
