mutation ProductCreateSimple($input: ProductCreateInput!) {
  catalogMutation {
    productCreate(input: $input) {
      product {
        id
        title
        handle
        isPublished
        publishedAt
        updatedAt
        revision
        media {
          file {
            id
          }
          sortIndex
        }
        options {
          id
          name
          slug
          displayType
          sortIndex
          values {
            id
            name
            slug
            sortIndex
          }
        }
        variants(first: 10) {
          edges {
            node {
              id
              isDefault
              handle
              createdAt
              updatedAt
              deletedAt
              inventoryItem {
                id
                variantId
                sku
                trackInventory
                continueSellingWhenOutOfStock
                dimensions {
                  widthMm
                  heightMm
                  lengthMm
                  displayUnit
                }
                weight {
                  weightGrams
                  displayUnit
                }
                stock {
                  id
                  quantityOnHand
                  createdAt
                  updatedAt
                  warehouse {
                    id
                    code
                    name
                    isDefault
                    createdAt
                    updatedAt
                    variantsCount
                  }
                  variant {
                    id
                    handle
                    title
                    isDefault
                  }
                }
                totalAvailable
                unitCost {
                  currency
                  amountMinor
                  effectiveFrom
                }
                createdAt
                updatedAt
              }
              media {
                file {
                  id
                }
                sortIndex
              }
            }
          }
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
