query ProductFindOne($id: ID!) {
  catalogQuery {
    product(id: $id) {
      id
      handle
      publishedAt
      isPublished
      createdAt
      updatedAt
      deletedAt
      title
      variantsCount
      variants(first: 10) {
        edges {
          node {
            id
            handle
            isDefault
            inventoryItem {
              id
              sku
              trackInventory
            }
          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
        }
        totalCount
      }
    }
  }
}
