mutation ProductDelete($input: ProductDeleteInput!) {
  catalogMutation {
    productDelete(input: $input) {
      deletedProductId
      userErrors {
        message
        code
        field
      }
    }
  }
}
