mutation ProductOptionsSync($input: ProductOptionsSyncInput!) {
  catalogMutation {
    productOptionsSync(input: $input) {
      product {
        id
        title
        options {
          id
          name
          slug
          displayType
          sortIndex
          values {
            id
            name
            slug
            sortIndex
            swatch {
              id
              swatchType
              colorOne
              colorTwo
              file {
                id
                url
              }
            }
          }
        }
      }
      options {
        id
        name
        slug
        displayType
        sortIndex
        values {
          id
          name
          slug
          sortIndex
          swatch {
            id
            swatchType
            colorOne
            colorTwo
            file {
              id
              url
            }
          }
        }
      }
      userErrors {
        message
        field
        code
      }
    }
  }
}
