mutation VariantSetMedia($input: VariantUpdateMediaInput!) {
  catalogMutation {
    variantUpdateMedia(input: $input) {
      variant {
        id
        media {
          file {
            id
          }
          sortIndex
        }
        inventoryItem {
          sku
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
