mutation VariantSetDimensions($input: InventoryItemUpdateInput!) {
  inventoryMutation {
    inventoryItemUpdate(input: $input) {
      inventoryItem {
        id
        variant {
          id
          dimensions {
            width
            height
            length
          }
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
