mutation VariantSetMedia($input: VariantUpdateMediaInput!) {
  inventoryMutation {
    variantUpdateMedia(input: $input) {
      variant {
        id
        sku
      }
      userErrors {
        message
        code
      }
    }
  }
}
