mutation VariantSetWeight(
  $productId: ID!
  $expectedRevision: Int
  $variantId: ID!
  $weight: Int!
) {
  catalogMutation {
    productUpdate(
      productId: $productId
      expectedRevision: $expectedRevision
      operations: {
        variants: [
          {
            variantId: $variantId
            weight: $weight
          }
        ]
      }
    ) {
      product {
        id
        revision
        variants(first: 10) {
          edges {
            node {
              id
              weight {
                value
              }
            }
          }
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
