mutation VariantSetCost($input: InventoryItemUpdateInput!) {
  inventoryMutation {
    inventoryItemUpdate(input: $input) {
      inventoryItem {
        id
        sku
        trackInventory
        unitCost {
          currency
          amountMinor
          effectiveFrom
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
