mutation VariantSetDimensions($input: VariantUpdateDimensionsInput!) {
  inventoryMutation {
    variantUpdateDimensions(input: $input) {
      variant {
        id
        dimensions {
          width
          length
          height
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
