mutation VariantSetCost($input: VariantUpdateInventoryInput!) {
  inventoryMutation {
    variantUpdateInventory(input: $input) {
      variant {
        id
        cost {
          id
          currency
          unitCostMinor
          effectiveFrom
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
