mutation VariantCreate($input: VariantCreateInput!) {
  catalogMutation {
    variantCreate(input: $input) {
      variant {
        id
        inventoryItem {
          sku
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
