mutation VariantSetDimensions(
  $productId: ID!
  $expectedRevision: Int
  $variantId: ID!
  $width: Int!
  $height: Int!
  $length: Int!
) {
  catalogMutation {
    productUpdate(
      productId: $productId
      expectedRevision: $expectedRevision
      operations: {
        variants: [
          {
            variantId: $variantId
            dimensions: {
              width: $width
              height: $height
              length: $length
            }
          }
        ]
      }
    ) {
      product {
        id
        revision
        variants(first: 10) {
          edges {
            node {
              id
              dimensions {
                width
                height
                length
              }
            }
          }
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
