mutation VariantSetStock($input: VariantUpdateInventoryInput!) {
  inventoryMutation {
    variantUpdateInventory(input: $input) {
      stock {
        id
        quantityOnHand
        createdAt
        updatedAt
      }
      variant {
        id
        sku
        weight {
          value
        }
        cost {
          id
          currency
          unitCostMinor
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
