mutation VariantSetWeight($input: VariantUpdateInventoryInput!) {
  inventoryMutation {
    variantUpdateInventory(input: $input) {
      variant {
        id
        weight {
          value
        }
      }
      userErrors {
        message
        code
      }
    }
  }
}
