mutation VendorCreate($input: VendorCreateInput!) {
  catalogMutation {
    vendorCreate(input: $input) {
      vendor {
        id
        name
      }
      userErrors {
        message
        code
        field
      }
    }
  }
}
