mutation VariantCreate($input: VariantCreateInput!) {
  inventoryMutation {
    variantCreate(input: $input) {
      variant {
        id
        sku
      }
      userErrors {
        message
        code
      }
    }
  }
}
