mutation WarehouseDelete($input: WarehouseDeleteInput!) {
  inventoryMutation {
    warehouseDelete(input: $input) {
      deletedWarehouseId
      userErrors {
        message
        code
      }
    }
  }
}
