query Listing(
  $first: Int!
  $after: String
  $scope: ListingScopeInput!
  $query: String
  $locale: LocaleCode
  $currency: CurrencyCode
  $facets: [ListingProductFilter!]
  $orderBy: ListingOrderByInput
) {
  listingQuery {
    listing(
      first: $first
      after: $after
      scope: $scope
      query: $query
      locale: $locale
      currency: $currency
      facets: $facets
      orderBy: $orderBy
    ) {
      totalCount
      edges {
        cursor
        node {
          __typename
          id
          ... on Product {
            title
            handle
            isPublished
          }
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      facets {
        id
        label
        type
        uiType
        values {
          id
          label
          count
          selected
          input
        }
      }
    }
  }
}
