mutation FileDelete($input: FileDeleteInput!) {
  mediaMutation {
    fileDelete(input: $input) {
      deletedFileId
      userErrors {
        message
        field
        code
      }
    }
  }
}
