query NodesFindMany($ids: [ID!]!) {
  mediaQuery {
    nodes(ids: $ids) {
      ... on File {
        id
        provider
        url
        mimeType
        ext
        sizeBytes
        originalName
        altText
        isProcessed
        createdAt
        updatedAt
      }
    }
  }
}
