query NodeCategoryListing(
  $id: ID!
  $first: Int
  $after: Cursor
  $last: Int
  $before: Cursor
  $sort: ListingSort
) {
  node(id: $id) {
    ... on Category {
      listing(first: $first, after: $after, last: $last, before: $before, sort: $sort) {
        edges {
          cursor
          node {
            ... on ProductVariant {
              id
              iid
              title
              handle
              createdAt
              updatedAt
              price {
                amount
                currencyCode
              }
            }
          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }
  }
}
