mutation PasswordSignIn($input: PasswordSignInInput!) {
  passwordSignIn(input: $input) {
    session {
      user {
        id
        iid
      }
      accessToken
    }
    errors {
      field
      message
      code
    }
  }
}
