mutation PasswordSignUp($input: PasswordSignUpInput!) {
  passwordSignUp(input: $input) {
    session {
      user {
        id
        iid
        email
        phone
      }
      accessToken
    }
    errors {
      field
      message
      code
    }
  }
}
