query ProductContainerCategory($handle: String!) {
  variant(handle: $handle) {
    id
    handle
    product {
      id
      handle
      category {
        id
        handle
        title
      }
    }
  }
}
