query ProductRatingBreakdown($handle: String!) {
  product(handle: $handle) {
    rating {
      rating
      count
      breakdown {
        star
        count
        percentage
      }
    }
  }
}
