mutation AppsAppResume($input: AppInstallationActionInput!) {
  appsMutation {
    appResume(input: $input) {
      installation {
        id
        appCode
        status
        capabilities {
          id
          capability
          status
          assignmentStatus
        }
      }
      operation {
        id
        type
        status
        previousInstallationStatus
        workflowId
      }
      duplicate
      userErrors {
        code
        message
        field
      }
    }
  }
}
