mutation AppsAppUpdate($input: AppUpdateInput!) {
  appsMutation {
    appUpdate(input: $input) {
      installation {
        id
        appCode
        status
        installedVersion
        targetVersion
        configuration
        configurationVersion
        scopes {
          scope
          grantedAt
          revokedAt
          granted
        }
        capabilities {
          id
          capability
          operation
          targetAction
          status
          assignmentStatus
        }
      }
      operation {
        id
        type
        status
        targetVersion
        previousInstallationStatus
        workflowId
        actorType
        actorId
        correlationId
        error {
          code
          message
        }
      }
      duplicate
      userErrors {
        code
        message
        field
      }
    }
  }
}
