query AppsAvailableApps($where: AppDefinitionWhereInput) {
  appsQuery {
    availableApps(where: $where) {
      code
      version
      displayName
      description
      runtimeStatus
      runtimeHealth {
        status
        message
      }
      permissions {
        scope
        granted
      }
      capabilities {
        key
        assignmentMode
        operations {
          name
          action
        }
      }
      graphql {
        admin
        storefront
      }
      installed
      installation {
        id
        appCode
        status
      }
    }
  }
}
