"""
A navigation menu owned by an Online Store installation.
"""
type OnlineStoreNavigationMenu implements Node @key(fields: "id") {
  id: ID!
  handle: String!
  name: String!
  revision: Int!
  items: [OnlineStoreNavigationMenuItem!]!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
}

enum OnlineStoreNavigationTargetType {
  URL
  PAGE
  PRODUCT
  CATEGORY
  COLLECTION
}

type OnlineStoreNavigationTarget {
  type: OnlineStoreNavigationTargetType!
  id: ID
  url: String
}

"""
A localized item in a navigation menu tree.
"""
type OnlineStoreNavigationMenuItem implements Node @key(fields: "id") {
  id: ID!
  handle: String!
  menu: OnlineStoreNavigationMenu!
  parent: OnlineStoreNavigationMenuItem
  children: [OnlineStoreNavigationMenuItem!]!
  label: String!
  target: OnlineStoreNavigationTarget!
  openInNewTab: Boolean!
  revision: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input OnlineStoreNavigationMenuCreateInput {
  handle: String!
  name: String!
}

input OnlineStoreNavigationMenuUpdateInput {
  fields: OnlineStoreNavigationMenuFieldsInput
  items: [OnlineStoreNavigationMenuItemOperationInput!]
}

input OnlineStoreNavigationMenuFieldsInput {
  handle: String
  name: String
}

input OnlineStoreNavigationTargetInput {
  type: OnlineStoreNavigationTargetType!
  id: ID
  url: String
}

input OnlineStoreNavigationMenuItemCreateInput {
  parentId: ID
  handle: String!
  label: String!
  afterItemId: ID
  beforeItemId: ID
  target: OnlineStoreNavigationTargetInput!
  openInNewTab: Boolean
}

input OnlineStoreNavigationMenuItemUpdateInput {
  parentId: ID
  handle: String
  label: String
  afterItemId: ID
  beforeItemId: ID
  target: OnlineStoreNavigationTargetInput
  openInNewTab: Boolean
}

enum OnlineStoreNavigationMenuItemOperationAction {
  CREATE
  UPDATE
  DELETE
  MOVE
}

input OnlineStoreNavigationMenuItemOperationInput {
  action: OnlineStoreNavigationMenuItemOperationAction!
  itemId: ID
  create: OnlineStoreNavigationMenuItemCreateInput
  update: OnlineStoreNavigationMenuItemUpdateInput
}

enum OnlineStoreNavigationMenuOperationType {
  FIELDS
  ITEM
}

type OnlineStoreNavigationMenuOperationResult {
  type: OnlineStoreNavigationMenuOperationType!
  applied: Boolean!
  entityId: ID
  navigationMenuItem: OnlineStoreNavigationMenuItem
  errors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuConnection {
  edges: [OnlineStoreNavigationMenuEdge!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type OnlineStoreNavigationMenuEdge {
  node: OnlineStoreNavigationMenu!
  cursor: String!
}

type OnlineStoreNavigationMenuCreatePayload {
  navigationMenu: OnlineStoreNavigationMenu
  userErrors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuUpdatePayload {
  navigationMenu: OnlineStoreNavigationMenu
  operationResults: [OnlineStoreNavigationMenuOperationResult!]!
  userErrors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuDeletePayload {
  deletedNavigationMenuId: ID
  userErrors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuItemCreatePayload {
  navigationMenuItem: OnlineStoreNavigationMenuItem
  userErrors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuItemUpdatePayload {
  navigationMenuItem: OnlineStoreNavigationMenuItem
  userErrors: [GenericUserError!]!
}

type OnlineStoreNavigationMenuItemDeletePayload {
  deletedNavigationMenuItemId: ID
  userErrors: [GenericUserError!]!
}
