"""
An object with a globally unique ID.
"""
interface Node {
  """
  The globally unique ID of the object.
  """
  id: ID!
}

"""
Information about a Relay connection page.
"""
type PageInfo @shareable {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

"""
A user-facing mutation error.
"""
interface UserError {
  message: String!
  field: [String!]
  code: String
}

"""
A generic user-facing mutation error.
"""
type GenericUserError implements UserError @shareable {
  message: String!
  field: [String!]
  code: String
}
