mutation HeadlessPrivateCredentialCreate($input: StorefrontPrivateCredentialCreateInput!) {
  headlessAppMutation {
    storefrontPrivateCredentialCreate(input: $input) {
      credential {
        id
        kind
        status
        label
        tokenHint
      }
      privateAccessToken
      userErrors {
        code
        message
        field
      }
    }
  }
}
